import { createScoreDocumentV2, type ScoreDocumentV2 } from '../../score-model-v2/src/index.js';
import { createNotationDocumentV2, type NotationDocumentV2 } from '../../notation-structure-v2/src/index.js';
import { addressEntityV2, type EventAddressV2, type GraceEventAddressV2, type GraceNoteAddressV2, type MeasureAddressV2, type NoteAddressV2 } from '../../addressing-v2/src/index.js';

export const EDITOR_HISTORY_V2_VERSION='2.0.0' as const;
export interface EditorRevisionSnapshotV2 { readonly score:Readonly<ScoreDocumentV2>; readonly notation:Readonly<NotationDocumentV2> }
export interface EditorHistoryStateV2 { readonly contractVersion:typeof EDITOR_HISTORY_V2_VERSION; readonly documentId:string; readonly past:readonly Readonly<EditorRevisionSnapshotV2>[]; readonly present:Readonly<EditorRevisionSnapshotV2>; readonly future:readonly Readonly<EditorRevisionSnapshotV2>[] }
export type EditorHistoryV2ErrorCode='SNAPSHOT_MISMATCH'|'DOCUMENT_MISMATCH'|'LINEAGE_MISMATCH'|'HISTORY_BOUNDARY'|'NOTATION_TARGET_DISAPPEARED';
export class EditorHistoryV2Error extends Error { readonly code:EditorHistoryV2ErrorCode; readonly details:Readonly<Record<string,unknown>>; constructor(message:string,code:EditorHistoryV2ErrorCode,details:Record<string,unknown>={}){super(message);this.name='EditorHistoryV2Error';this.code=code;this.details=Object.freeze({...details});Object.freeze(this);} }
const snapshot=(scoreInput:ScoreDocumentV2,notationInput:NotationDocumentV2):Readonly<EditorRevisionSnapshotV2>=>{const score=createScoreDocumentV2(scoreInput);let notation:Readonly<NotationDocumentV2>;try{notation=createNotationDocumentV2(score,notationInput);}catch(error){throw new EditorHistoryV2Error('Score and notation must form one valid v2 document/revision pair.','SNAPSHOT_MISMATCH',{cause:error instanceof Error?error.message:String(error)});}return Object.freeze({score,notation});};
const freeze=(value:EditorHistoryStateV2):Readonly<EditorHistoryStateV2>=>Object.freeze({contractVersion:EDITOR_HISTORY_V2_VERSION,documentId:value.documentId,past:Object.freeze([...value.past]),present:value.present,future:Object.freeze([...value.future])});
export const createEditorHistoryV2=(score:ScoreDocumentV2,notation:NotationDocumentV2):Readonly<EditorHistoryStateV2>=>{const present=snapshot(score,notation);return freeze({contractVersion:EDITOR_HISTORY_V2_VERSION,documentId:present.score.id,past:[],present,future:[]});};
export const commitEditorHistoryV2=(history:EditorHistoryStateV2,score:ScoreDocumentV2,notation:NotationDocumentV2):Readonly<EditorHistoryStateV2>=>{const next=snapshot(score,notation);if(next.score.id!==history.documentId)throw new EditorHistoryV2Error('Cannot commit another document into v2 history.','DOCUMENT_MISMATCH');if(next.score.revision.parentId!==history.present.score.revision.id)throw new EditorHistoryV2Error('Next v2 revision is not a direct child of present.','LINEAGE_MISMATCH',{expectedParent:history.present.score.revision.id,observedParent:next.score.revision.parentId});return freeze({contractVersion:EDITOR_HISTORY_V2_VERSION,documentId:history.documentId,past:[...history.past,history.present],present:next,future:[]});};
export const undoEditorHistoryV2=(history:EditorHistoryStateV2):Readonly<EditorHistoryStateV2>=>{const previous=history.past.at(-1);if(!previous)throw new EditorHistoryV2Error('No earlier v2 revision is available.','HISTORY_BOUNDARY');return freeze({contractVersion:EDITOR_HISTORY_V2_VERSION,documentId:history.documentId,past:history.past.slice(0,-1),present:previous,future:[history.present,...history.future]});};
export const redoEditorHistoryV2=(history:EditorHistoryStateV2):Readonly<EditorHistoryStateV2>=>{const next=history.future[0];if(!next)throw new EditorHistoryV2Error('No later v2 revision is available.','HISTORY_BOUNDARY');if(next.score.revision.parentId!==history.present.score.revision.id)throw new EditorHistoryV2Error('Redo lineage mismatch.','LINEAGE_MISMATCH');return freeze({contractVersion:EDITOR_HISTORY_V2_VERSION,documentId:history.documentId,past:[...history.past,history.present],present:next,future:history.future.slice(1)});};
const rebound=<T extends 'measure'|'event'|'note'|'grace-event'|'grace-note'>(score:ScoreDocumentV2,id:string,kind:T):Extract<ReturnType<typeof addressEntityV2>,{kind:T}>=>{try{const address=addressEntityV2(score,id);if(address.kind!==kind)throw new Error(`observed ${address.kind}`);return address as Extract<ReturnType<typeof addressEntityV2>,{kind:T}>;}catch(error){throw new EditorHistoryV2Error('A v2 notation target disappeared or changed kind during score edit.','NOTATION_TARGET_DISAPPEARED',{id,kind,cause:error instanceof Error?error.message:String(error)});}};
export const rebindNotationAfterScoreEditV2=(previousScoreInput:ScoreDocumentV2,previousNotationInput:NotationDocumentV2,nextScoreInput:ScoreDocumentV2):Readonly<NotationDocumentV2>=>{const previousScore=createScoreDocumentV2(previousScoreInput);const previousNotation=createNotationDocumentV2(previousScore,previousNotationInput);const nextScore=createScoreDocumentV2(nextScoreInput);if(nextScore.id!==previousScore.id||nextScore.revision.parentId!==previousScore.revision.id)throw new EditorHistoryV2Error('Score edit result is not a direct child of the notation base revision.','LINEAGE_MISMATCH');return createNotationDocumentV2(nextScore,{contractVersion:'2.0.0',documentId:nextScore.id,revisionId:nextScore.revision.id,measures:previousNotation.measures.map(entry=>({target:rebound(nextScore,entry.target.measureId,'measure') as MeasureAddressV2,notation:entry.notation})),events:previousNotation.events.map(entry=>({target:rebound(nextScore,entry.target.eventId,'event') as EventAddressV2,notation:entry.notation})),notes:previousNotation.notes.map(entry=>({target:rebound(nextScore,entry.target.noteId,'note') as NoteAddressV2,notation:entry.notation})),graceEvents:previousNotation.graceEvents.map(entry=>({target:rebound(nextScore,entry.target.graceEventId,'grace-event') as GraceEventAddressV2,notation:entry.notation})),graceNotes:previousNotation.graceNotes.map(entry=>({target:rebound(nextScore,entry.target.graceNoteId,'grace-note') as GraceNoteAddressV2,notation:entry.notation}))});};
