import test from 'node:test';
import assert from 'node:assert/strict';
import { createScoreDocument } from '../dist/packages/score-model/src/index.js';
import { emptyNotationDocument } from '../dist/packages/notation-structure/src/index.js';
import { createScoreDocumentV2, ScoreDocumentV2ValidationError } from '../dist/packages/score-model-v2/src/index.js';
import { createNotationDocumentV2, emptyNotationDocumentV2 } from '../dist/packages/notation-structure-v2/src/index.js';
import { addressEntityV2 } from '../dist/packages/addressing-v2/src/index.js';
import { createEditorSessionV2, createEditorSessionV2FromV1, selectSessionV2RenderToken } from '../dist/packages/editor-session-controller-v2/src/index.js';
import { createEditorHistoryV2, commitEditorHistoryV2, undoEditorHistoryV2, redoEditorHistoryV2, rebindNotationAfterScoreEditV2, EditorHistoryV2Error } from '../dist/packages/editor-history-v2/src/index.js';

const v1Score=()=>createScoreDocument({schemaVersion:'1.0.0',id:'doc-sse02',revision:{id:'rev-1',parentId:null},source:{sha256:'a'.repeat(64),format:'synthetic',byteLength:null},parts:[{id:'part-1',name:'Part',staves:[{id:'staff-1',ordinal:1,measures:[{id:'measure-1',ordinal:1,displayNumber:'1',voices:[{id:'voice-1',ordinal:1,events:[{id:'event-1',kind:'note',onset:{numerator:0,denominator:1},duration:{numerator:1,denominator:4},note:{id:'note-1',pitch:{step:'C',alter:0,octave:4}}}]}]}]}]}]});
const v2Raw=(revision='rev-v2-1',parentId=null)=>({schemaVersion:'2.0.0',id:'doc-v2-session',revision:{id:revision,parentId},source:{sha256:'b'.repeat(64),format:'synthetic',byteLength:null},parts:[{id:'part-1',name:'Part',staves:[{id:'staff-1',ordinal:1,measures:[{id:'measure-1',ordinal:1,displayNumber:'1',voices:[{id:'voice-1',ordinal:1,events:[{id:'event-1',kind:'note',onset:{numerator:0,denominator:1},duration:{numerator:1,denominator:4},note:{id:'note-1',pitch:{step:'C',alter:0,octave:4}}}],graceGroups:[]}]}]}]}]});
const graceRaw=()=>{const raw=v2Raw();raw.parts[0].staves[0].measures[0].voices[0].graceGroups=[{id:'grace-group-1',anchorEventId:'event-1',placement:'before',events:[{id:'grace-event-1',kind:'note',writtenDuration:{numerator:1,denominator:8},playback:{stealTimePreviousPercent:null,stealTimeFollowingPercent:null,makeTime:null},note:{id:'grace-note-1',pitch:{step:'D',alter:0,octave:4}}}]}];return raw;};

test('SSE-02 migrates v1 once at session boundary and stores only a v2 canonical pair',()=>{const score=v1Score(),notation=emptyNotationDocument(score);const session=createEditorSessionV2FromV1(score,notation,'osmd');assert.equal(session.schemaVersion,'2.0.0');assert.equal(session.history.present.score.schemaVersion,'2.0.0');assert.equal(session.history.present.notation.contractVersion,'2.0.0');assert.equal(session.history.present.score.id,score.id);assert.equal(session.history.present.score.revision.id,score.revision.id);assert.equal('legacyScore' in session,false);assert.equal('v1' in session,false);assert.equal(session.renderRequest.projectionStatus,'V1_COMPATIBLE_XML');assert.equal(typeof session.renderRequest.musicXml,'string');});

test('SSE-02 v2 session rejects v1 score input instead of silently mixing versions',()=>{const score=v1Score();assert.throws(()=>createEditorSessionV2(score,emptyNotationDocument(score)),ScoreDocumentV2ValidationError);});

test('v2 render request preserves v2-only semantics in manifest and refuses lossy v1 XML projection',()=>{const score=createScoreDocumentV2(graceRaw());const notation=emptyNotationDocumentV2(score);let session=createEditorSessionV2(score,notation,'osmd');assert.equal(session.renderRequest.projectionStatus,'VNEXT_XML_PENDING');assert.equal(session.renderRequest.musicXml,null);const entry=session.renderRequest.manifest.entries.find(x=>x.address.kind==='grace-note');assert.ok(entry);session=selectSessionV2RenderToken(session,entry.token);assert.equal(session.selection.primary.kind,'grace-note');assert.equal(session.inspector.targetKind,'grace-note');assert.equal(session.inspector.targetId,'grace-note-1');});

test('v2 history commits one score+notation pair and preserves direct-child lineage across undo/redo',()=>{const base=createScoreDocumentV2(v2Raw());const notation=emptyNotationDocumentV2(base);let history=createEditorHistoryV2(base,notation);const nextRaw=v2Raw('rev-v2-2','rev-v2-1');nextRaw.parts[0].staves[0].measures[0].voices[0].events[0].note.pitch.step='E';const next=createScoreDocumentV2(nextRaw);const nextNotation=rebindNotationAfterScoreEditV2(base,notation,next);history=commitEditorHistoryV2(history,next,nextNotation);assert.equal(history.present.score.revision.id,'rev-v2-2');history=undoEditorHistoryV2(history);assert.equal(history.present.score.revision.id,'rev-v2-1');history=redoEditorHistoryV2(history);assert.equal(history.present.score.revision.id,'rev-v2-2');});

test('v2 notation rebinding preserves surviving grace semantic targets and rejects orphaning',()=>{const base=createScoreDocumentV2(graceRaw());const graceEvent=addressEntityV2(base,'grace-event-1');const graceNote=addressEntityV2(base,'grace-note-1');const notation=createNotationDocumentV2(base,{contractVersion:'2.0.0',documentId:base.id,revisionId:base.revision.id,measures:[],events:[],notes:[],graceEvents:[{target:graceEvent,notation:{slash:true,dots:0,beams:[],articulations:[],ornaments:[]}}],graceNotes:[{target:graceNote,notation:{accidental:null,ties:[],slurs:[]}}]});const survivingRaw=graceRaw();survivingRaw.revision={id:'rev-v2-2',parentId:'rev-v2-1'};const surviving=createScoreDocumentV2(survivingRaw);const rebound=rebindNotationAfterScoreEditV2(base,notation,surviving);assert.equal(rebound.graceEvents[0].target.revisionId,'rev-v2-2');assert.equal(rebound.graceNotes[0].target.graceNoteId,'grace-note-1');const orphanRaw=graceRaw();orphanRaw.revision={id:'rev-v2-3',parentId:'rev-v2-1'};orphanRaw.parts[0].staves[0].measures[0].voices[0].graceGroups=[];const orphan=createScoreDocumentV2(orphanRaw);assert.throws(()=>rebindNotationAfterScoreEditV2(base,notation,orphan),(e)=>e instanceof EditorHistoryV2Error&&e.code==='NOTATION_TARGET_DISAPPEARED');});
