import test from 'node:test';
import assert from 'node:assert/strict';
import { createScoreDocumentV2 } from '../dist/packages/score-model-v2/src/index.js';
import { createNotationDocumentV2 } from '../dist/packages/notation-structure-v2/src/index.js';
import { addressEntityV2 } from '../dist/packages/addressing-v2/src/index.js';
import { migrateScoreNotationV2ToV3 } from '../dist/packages/schema-migration-v2-v3/src/index.js';
import { addressEntityV3 } from '../dist/packages/addressing-v3/src/index.js';
import { executeTopologyAuthoringV3, TopologyAuthoringV3Error } from '../dist/packages/editor-topology-authoring-v3/src/index.js';

const measure=(id,ordinal,display,voiceId,restId)=>({id,ordinal,displayNumber:display,voices:[{id:voiceId,ordinal:1,events:[{id:restId,kind:'rest',onset:{numerator:0,denominator:1},duration:{numerator:1,denominator:1}}],graceGroups:[]}]});
const base=()=>{const score=createScoreDocumentV2({schemaVersion:'2.0.0',id:'doc-v3-coverage',revision:{id:'rev-1',parentId:null},source:{sha256:'f'.repeat(64),format:'synthetic',byteLength:null},parts:[{id:'part-1',name:'Guitar',staves:[{id:'staff-1',ordinal:1,measures:[measure('m1',1,'1','v1','r1'),measure('m2',2,'2','v2','r2')]}]}]});const notation=createNotationDocumentV2(score,{contractVersion:'2.0.0',documentId:score.id,revisionId:score.revision.id,measures:[{target:addressEntityV2(score,'m1'),notation:{timeSignature:{beats:4,beatType:4},keySignature:null,clef:null,barlines:[]}}],events:[],notes:[],graceEvents:[],graceNotes:[]});return migrateScoreNotationV2ToV3(score,notation);};
const plans=(score,prefix)=>score.measureFrames.map((frame,i)=>({frameId:frame.id,measureId:`${prefix}-m${i+1}`,voiceId:`${prefix}-v${i+1}`,restEventId:`${prefix}-r${i+1}`}));
const tabProfile={stringCount:6,tuning:[['E',4],['B',3],['G',3],['D',3],['A',2],['E',2]].map(([step,octave],i)=>({stringNumber:i+1,openPitch:{step,alter:0,octave}})),capoFret:0};

test('SSE-09 reorders content staffs by ordinal without changing stable staff identities',()=>{const {score,notation}=base();let result=executeTopologyAuthoringV3(score,notation,{version:'1.0.0',type:'ADD_STANDARD_OR_PERCUSSION_STAFF',target:addressEntityV3(score,'part-1'),index:1,staffId:'staff-2',staffRole:'standard',frameRestIds:plans(score,'s2')},{nextRevisionId:'rev-2'});result=executeTopologyAuthoringV3(result.score,result.notation,{version:'1.0.0',type:'REORDER_STAFF',target:addressEntityV3(result.score,'staff-2'),toIndex:0},{nextRevisionId:'rev-3'});assert.deepEqual(result.score.parts[0].staves.map(staff=>[staff.id,staff.ordinal]),[['staff-2',1],['staff-1',2]]);assert.equal(addressEntityV3(result.score,'m1').staffId,'staff-1');});

test('SSE-09 removes a non-last content staff when no notation or TAB dependency would be orphaned',()=>{const {score,notation}=base();let result=executeTopologyAuthoringV3(score,notation,{version:'1.0.0',type:'ADD_STANDARD_OR_PERCUSSION_STAFF',target:addressEntityV3(score,'part-1'),index:1,staffId:'staff-2',staffRole:'standard',frameRestIds:plans(score,'s2')},{nextRevisionId:'rev-2'});result=executeTopologyAuthoringV3(result.score,result.notation,{version:'1.0.0',type:'REMOVE_CONTENT_STAFF',target:addressEntityV3(result.score,'staff-2')},{nextRevisionId:'rev-3'});assert.deepEqual(result.score.parts[0].staves.map(staff=>staff.id),['staff-1']);assert.equal(result.selectionEntityId,'part-1');});

test('SSE-09 linked TAB can be removed atomically without mutating its source standard staff',()=>{const {score,notation}=base();let result=executeTopologyAuthoringV3(score,notation,{version:'1.0.0',type:'ADD_LINKED_TAB_STAFF',target:addressEntityV3(score,'staff-1'),index:1,staffId:'tab-1',tabProfile},{nextRevisionId:'rev-2'});result=executeTopologyAuthoringV3(result.score,result.notation,{version:'1.0.0',type:'REMOVE_LINKED_TAB_STAFF',target:addressEntityV3(result.score,'tab-1')},{nextRevisionId:'rev-3'});assert.deepEqual(result.score.parts[0].staves.map(staff=>staff.id),['staff-1']);assert.equal(result.score.parts[0].staves[0].role,'standard');assert.equal(result.score.parts[0].staves[0].measures[0].id,'m1');});

test('SSE-09 refuses removal of the final part and final content staff',()=>{const {score,notation}=base();assert.throws(()=>executeTopologyAuthoringV3(score,notation,{version:'1.0.0',type:'REMOVE_PART',target:addressEntityV3(score,'part-1')},{nextRevisionId:'rev-p'}),e=>e instanceof TopologyAuthoringV3Error&&e.code==='LAST_PART_FORBIDDEN');assert.throws(()=>executeTopologyAuthoringV3(score,notation,{version:'1.0.0',type:'REMOVE_CONTENT_STAFF',target:addressEntityV3(score,'staff-1')},{nextRevisionId:'rev-s'}),e=>e instanceof TopologyAuthoringV3Error&&e.code==='LAST_CONTENT_STAFF_FORBIDDEN');});

test('SSE-09 removes a second part only when surviving notation remains addressable',()=>{const {score,notation}=base();let result=executeTopologyAuthoringV3(score,notation,{version:'1.0.0',type:'ADD_STANDARD_OR_PERCUSSION_PART',target:addressEntityV3(score,score.id),index:1,partId:'part-2',partName:'Piano',instrumentId:'inst-piano',instrumentName:'Piano',instrumentShortName:null,staffId:'staff-piano',staffRole:'standard',frameRestIds:plans(score,'p2')},{nextRevisionId:'rev-2'});result=executeTopologyAuthoringV3(result.score,result.notation,{version:'1.0.0',type:'REMOVE_PART',target:addressEntityV3(result.score,'part-2')},{nextRevisionId:'rev-3'});assert.deepEqual(result.score.parts.map(part=>[part.id,part.ordinal]),[['part-1',1]]);assert.equal(result.notation.measures[0].target.measureId,'m1');});
