import test from 'node:test';
import assert from 'node:assert/strict';
import { createScoreDocumentV2 } from '../dist/packages/score-model-v2/src/index.js';
import { createNotationDocumentV2 } from '../dist/packages/notation-structure-v2/src/index.js';
import { addressEntityV2 } from '../dist/packages/addressing-v2/src/index.js';
import { migrateScoreNotationV2ToV3 } from '../dist/packages/schema-migration-v2-v3/src/index.js';
import { addressEntityV3 } from '../dist/packages/addressing-v3/src/index.js';
import { executeTopologyAuthoringV3, TopologyAuthoringV3Error } from '../dist/packages/editor-topology-authoring-v3/src/index.js';
import { createEditorSessionV3, commitSessionTopologyIntentV3, navigateSessionHistoryV3 } from '../dist/packages/editor-session-controller-v3/src/index.js';
import { renderableMusicXmlV3, RendererContractV3Error } from '../dist/packages/renderer-contract-v3/src/index.js';

const rest=(id)=>({id,kind:'rest',onset:{numerator:0,denominator:1},duration:{numerator:1,denominator:1}});
const measure=(id,ordinal,display,voiceId,eventId)=>({id,ordinal,displayNumber:display,voices:[{id:voiceId,ordinal:1,events:[rest(eventId)],graceGroups:[]}]});
const v2raw=()=>({schemaVersion:'2.0.0',id:'doc-v3-authoring',revision:{id:'rev-1',parentId:null},source:{sha256:'e'.repeat(64),format:'synthetic',byteLength:null},parts:[{id:'part-1',name:'Guitar',staves:[{id:'staff-1',ordinal:1,measures:[measure('m1',1,'1','v1','r1'),measure('m2',2,'2','v2','r2')]}]}]});
const v2notation=(score,withMeter=true)=>createNotationDocumentV2(score,{contractVersion:'2.0.0',documentId:score.id,revisionId:score.revision.id,measures:withMeter?[{target:addressEntityV2(score,'m1'),notation:{timeSignature:{beats:4,beatType:4},keySignature:{fifths:0},clef:{sign:'G',line:2,octaveChange:0},barlines:[]}}]:[],events:[],notes:[],graceEvents:[],graceNotes:[]});
const base=(withMeter=true)=>{const score=createScoreDocumentV2(v2raw());return migrateScoreNotationV2ToV3(score,v2notation(score,withMeter));};
const plans=(score,prefix)=>score.measureFrames.map((frame,i)=>({frameId:frame.id,measureId:`${prefix}-m${i+1}`,voiceId:`${prefix}-v${i+1}`,restEventId:`${prefix}-r${i+1}`}));
const guitarProfile={stringCount:6,tuning:[['E',4],['B',3],['G',3],['D',3],['A',2],['E',2]].map(([step,octave],i)=>({stringNumber:i+1,openPitch:{step,alter:0,octave}})),capoFret:0};

test('SSE-09 adds a content staff only from effective frame meter and creates deterministic full-frame rests',()=>{const {score,notation}=base();const result=executeTopologyAuthoringV3(score,notation,{version:'1.0.0',type:'ADD_STANDARD_OR_PERCUSSION_STAFF',target:addressEntityV3(score,'part-1'),index:1,staffId:'staff-2',staffRole:'standard',frameRestIds:plans(score,'s2')},{nextRevisionId:'rev-2'});const staff=result.score.parts[0].staves[1];assert.equal(staff.role,'standard');assert.deepEqual(staff.measures.map(m=>m.frameId),score.measureFrames.map(f=>f.id));assert.deepEqual(staff.measures.map(m=>m.voices[0].events[0].duration),[{numerator:1,denominator:1},{numerator:1,denominator:1}]);assert.equal(result.score.revision.parentId,'rev-1');});

test('SSE-09 content staff creation fails closed when effective meter proof is absent',()=>{const {score,notation}=base(false);assert.throws(()=>executeTopologyAuthoringV3(score,notation,{version:'1.0.0',type:'ADD_STANDARD_OR_PERCUSSION_STAFF',target:addressEntityV3(score,'part-1'),index:1,staffId:'staff-x',staffRole:'standard',frameRestIds:plans(score,'sx')},{nextRevisionId:'rev-x'}),e=>e instanceof TopologyAuthoringV3Error&&e.code==='METER_EVIDENCE_MISSING');});

test('SSE-09 linked TAB stays derivative, owns no measures, blocks source removal and makes renderer projection pending',()=>{const {score,notation}=base();const added=executeTopologyAuthoringV3(score,notation,{version:'1.0.0',type:'ADD_LINKED_TAB_STAFF',target:addressEntityV3(score,'staff-1'),index:1,staffId:'tab-1',tabProfile:guitarProfile},{nextRevisionId:'rev-2'});const tab=added.score.parts[0].staves[1];assert.equal(tab.role,'tablature-linked');assert.deepEqual(tab.measures,[]);const session=createEditorSessionV3(added.score,added.notation);assert.equal(session.renderRequest.projectionStatus,'V3_XML_PENDING');assert.throws(()=>renderableMusicXmlV3(session.renderRequest),e=>e instanceof RendererContractV3Error);assert.throws(()=>executeTopologyAuthoringV3(added.score,added.notation,{version:'1.0.0',type:'REMOVE_CONTENT_STAFF',target:addressEntityV3(added.score,'staff-1')},{nextRevisionId:'rev-3'}),e=>e instanceof TopologyAuthoringV3Error&&(e.code==='LAST_CONTENT_STAFF_FORBIDDEN'||e.code==='TAB_SOURCE_IN_USE'));});

test('SSE-09 unified v3 session commits topology and undo restores exact prior pair',()=>{const {score,notation}=base();let session=createEditorSessionV3(score,notation);assert.equal(session.renderRequest.projectionStatus,'V2_COMPATIBLE_XML');assert.ok(renderableMusicXmlV3(session.renderRequest).includes('<score-partwise'));session=commitSessionTopologyIntentV3(session,{version:'1.0.0',type:'ADD_STANDARD_OR_PERCUSSION_STAFF',target:addressEntityV3(score,'part-1'),index:1,staffId:'staff-2',staffRole:'standard',frameRestIds:plans(score,'s2')},{nextRevisionId:'rev-2'});assert.equal(session.history.past.length,1);assert.equal(session.selection.kind,'staff');assert.equal(session.selection.staffId,'staff-2');session=navigateSessionHistoryV3(session,'UNDO');assert.equal(session.history.present.score.revision.id,'rev-1');assert.equal(session.history.present.score.parts[0].staves.length,1);assert.equal(session.selection,null);});

test('SSE-09 can add, reorder and rename a part while preserving stable identities',()=>{const {score,notation}=base();let result=executeTopologyAuthoringV3(score,notation,{version:'1.0.0',type:'ADD_STANDARD_OR_PERCUSSION_PART',target:addressEntityV3(score,score.id),index:1,partId:'part-2',partName:'Piano',instrumentId:'inst-piano',instrumentName:'Piano',instrumentShortName:'Pno.',staffId:'staff-piano',staffRole:'standard',frameRestIds:plans(score,'p2')},{nextRevisionId:'rev-2'});assert.deepEqual(result.score.parts.map(p=>[p.id,p.ordinal]),[['part-1',1],['part-2',2]]);result=executeTopologyAuthoringV3(result.score,result.notation,{version:'1.0.0',type:'REORDER_PART',target:addressEntityV3(result.score,'part-2'),toIndex:0},{nextRevisionId:'rev-3'});assert.deepEqual(result.score.parts.map(p=>[p.id,p.ordinal]),[['part-2',1],['part-1',2]]);result=executeTopologyAuthoringV3(result.score,result.notation,{version:'1.0.0',type:'RENAME_PART_OR_INSTRUMENT',target:addressEntityV3(result.score,'part-2'),partName:'Grand Piano',instrumentName:'Grand Piano',instrumentShortName:'Pno.'},{nextRevisionId:'rev-4'});assert.equal(result.score.parts[0].id,'part-2');assert.equal(result.score.parts[0].instrument.id,'inst-piano');assert.equal(result.score.parts[0].name,'Grand Piano');});

test('SSE-09 removal refuses notation orphaning instead of silently deleting staff notation',()=>{const {score,notation}=base();const added=executeTopologyAuthoringV3(score,notation,{version:'1.0.0',type:'ADD_STANDARD_OR_PERCUSSION_STAFF',target:addressEntityV3(score,'part-1'),index:1,staffId:'staff-2',staffRole:'standard',frameRestIds:plans(score,'s2')},{nextRevisionId:'rev-2'});assert.throws(()=>executeTopologyAuthoringV3(added.score,added.notation,{version:'1.0.0',type:'REMOVE_CONTENT_STAFF',target:addressEntityV3(added.score,'staff-1')},{nextRevisionId:'rev-3'}),e=>e instanceof TopologyAuthoringV3Error&&e.code==='NOTATION_ORPHAN_RISK');});

test('SSE-09 stale topology targets and identity collisions fail closed',()=>{const {score,notation}=base();const stale=addressEntityV3(score,'part-1');const first=executeTopologyAuthoringV3(score,notation,{version:'1.0.0',type:'RENAME_PART_OR_INSTRUMENT',target:stale,partName:'Guitar',instrumentName:'Guitar',instrumentShortName:null},{nextRevisionId:'rev-2'});assert.throws(()=>executeTopologyAuthoringV3(first.score,first.notation,{version:'1.0.0',type:'REORDER_PART',target:stale,toIndex:0},{nextRevisionId:'rev-3'}),e=>e instanceof TopologyAuthoringV3Error&&e.code==='STALE_TARGET');assert.throws(()=>executeTopologyAuthoringV3(score,notation,{version:'1.0.0',type:'ADD_STANDARD_OR_PERCUSSION_STAFF',target:addressEntityV3(score,'part-1'),index:1,staffId:'staff-1',staffRole:'standard',frameRestIds:plans(score,'dup')},{nextRevisionId:'rev-x'}),e=>e instanceof TopologyAuthoringV3Error&&e.code==='RESULT_INVALID');});
