import test from 'node:test';
import assert from 'node:assert/strict';
import { createScoreDocument, ScoreDocumentValidationError } from '../dist/packages/score-model/src/index.js';
import { createScoreDocumentV2, ScoreDocumentV2ValidationError } from '../dist/packages/score-model-v2/src/index.js';
import { addressEntityV2, resolveSemanticAddressV2 } from '../dist/packages/addressing-v2/src/index.js';
import { createNotationDocumentV2, NotationV2Error } from '../dist/packages/notation-structure-v2/src/index.js';

const baseV2=()=>({schemaVersion:'2.0.0',id:'doc-v2',revision:{id:'rev-v2-1',parentId:null},source:{sha256:'a'.repeat(64),format:'synthetic',byteLength:null},parts:[{id:'part-1',name:'Part',staves:[{id:'staff-1',ordinal:1,measures:[{id:'measure-1',ordinal:1,displayNumber:'1',voices:[{id:'voice-1',ordinal:1,events:[{id:'event-1',kind:'note',onset:{numerator:0,denominator:1},duration:{numerator:1,denominator:4},note:{id:'note-1',pitch:{step:'C',alter:0,octave:4}}}],graceGroups:[]}]}]}]}]});
const withGrace=()=>{const value=baseV2();value.parts[0].staves[0].measures[0].voices[0].graceGroups=[{id:'grace-group-1',anchorEventId:'event-1',placement:'before',events:[{id:'grace-event-1',kind:'note',writtenDuration:{numerator:1,denominator:8},playback:{stealTimePreviousPercent:null,stealTimeFollowingPercent:null,makeTime:null},note:{id:'grace-note-1',pitch:{step:'D',alter:0,octave:4}}}]}];return value;};
const emptyNotation=(score)=>({contractVersion:'2.0.0',documentId:score.id,revisionId:score.revision.id,measures:[],events:[],notes:[],graceEvents:[],graceNotes:[]});

test('ScoreDocumentV2 keeps grace material outside normal timed event occupancy',()=>{const score=createScoreDocumentV2(withGrace());const voice=score.parts[0].staves[0].measures[0].voices[0];assert.equal(voice.events.length,1);assert.equal(voice.events[0].duration.numerator,1);assert.equal(voice.graceGroups.length,1);assert.equal(voice.graceGroups[0].events[0].writtenDuration.denominator,8);});

test('v2 semantic addressing resolves grace group event and note identities exactly',()=>{const score=createScoreDocumentV2(withGrace());for(const id of ['grace-group-1','grace-event-1','grace-note-1']){const address=addressEntityV2(score,id);const resolved=resolveSemanticAddressV2(score,address);assert.equal(address.contractVersion,'2.0.0');assert.equal(resolved.value.id,id);}assert.equal(addressEntityV2(score,'grace-group-1').kind,'grace-group');assert.equal(addressEntityV2(score,'grace-event-1').kind,'grace-event');assert.equal(addressEntityV2(score,'grace-note-1').kind,'grace-note');});

test('v2 rejects missing same-voice grace anchor and duplicate anchor placement',()=>{const missing=withGrace();missing.parts[0].staves[0].measures[0].voices[0].graceGroups[0].anchorEventId='event-other';assert.throws(()=>createScoreDocumentV2(missing),(e)=>e instanceof ScoreDocumentV2ValidationError&&e.issues.some(x=>x.code==='INVALID_GRACE_ANCHOR'));const duplicate=withGrace();duplicate.parts[0].staves[0].measures[0].voices[0].graceGroups.push({...duplicate.parts[0].staves[0].measures[0].voices[0].graceGroups[0],id:'grace-group-2',events:[{...duplicate.parts[0].staves[0].measures[0].voices[0].graceGroups[0].events[0],id:'grace-event-2',note:{id:'grace-note-2',pitch:{step:'E',alter:0,octave:4}}}]});assert.throws(()=>createScoreDocumentV2(duplicate),(e)=>e instanceof ScoreDocumentV2ValidationError&&e.issues.some(x=>x.code==='DUPLICATE_GRACE_ANCHOR_PLACEMENT'));});

test('v2 grace playback percentages are bounded and written duration stays positive',()=>{const bad=withGrace();bad.parts[0].staves[0].measures[0].voices[0].graceGroups[0].events[0].playback.stealTimeFollowingPercent={numerator:101,denominator:1};assert.throws(()=>createScoreDocumentV2(bad),(e)=>e instanceof ScoreDocumentV2ValidationError&&e.issues.some(x=>x.code==='INVALID_GRACE_PLAYBACK'));const zero=withGrace();zero.parts[0].staves[0].measures[0].voices[0].graceGroups[0].events[0].writtenDuration={numerator:0,denominator:1};assert.throws(()=>createScoreDocumentV2(zero),ScoreDocumentV2ValidationError);});

test('legacy v1 validator remains intentionally fail-closed for schema v2',()=>{assert.throws(()=>createScoreDocument(baseV2()),ScoreDocumentValidationError);});

test('NotationDocumentV2 accepts typed articulation and simple ornament vocabulary',()=>{const score=createScoreDocumentV2(baseV2());const target=addressEntityV2(score,'event-1');const notation=createNotationDocumentV2(score,{...emptyNotation(score),events:[{target,notation:{dots:0,beams:[],tuplet:null,articulations:[{kind:'staccato',placement:'auto',direction:null}],ornaments:[{kind:'trill-mark',placement:'above',accidentalMarks:[]}]}}]});assert.equal(notation.events[0].notation.articulations[0].kind,'staccato');assert.equal(notation.events[0].notation.ornaments[0].kind,'trill-mark');});

test('NotationDocumentV2 rejects unsupported articulation direction',()=>{const score=createScoreDocumentV2(baseV2());const target=addressEntityV2(score,'event-1');assert.throws(()=>createNotationDocumentV2(score,{...emptyNotation(score),events:[{target,notation:{dots:0,beams:[],tuplet:null,articulations:[{kind:'staccato',placement:'auto',direction:'up'}],ornaments:[]}}]}),(e)=>e instanceof NotationV2Error&&e.code==='INVALID_NOTATION');});

test('NotationDocumentV2 validates spanning ornament relation endpoints atomically',()=>{const score=createScoreDocumentV2(baseV2());const target=addressEntityV2(score,'event-1');assert.throws(()=>createNotationDocumentV2(score,{...emptyNotation(score),events:[{target,notation:{dots:0,beams:[],tuplet:null,articulations:[],ornaments:[{kind:'wavy-line',type:'start',number:1,placement:'above'}]}}]}),(e)=>e instanceof NotationV2Error&&e.code==='BROKEN_ORNAMENT_RELATION');});
