import test from 'node:test';
import assert from 'node:assert/strict';
import { createScoreDocument } from '../dist/packages/score-model/src/index.js';
import { createNotationDocument } from '../dist/packages/notation-structure/src/index.js';
import { addressEntity } from '../dist/packages/addressing/src/index.js';
import { addressEntityV2 } from '../dist/packages/addressing-v2/src/index.js';
import { createScoreDocumentV2 } from '../dist/packages/score-model-v2/src/index.js';
import { createNotationDocumentV2 } from '../dist/packages/notation-structure-v2/src/index.js';
import { migrateSchemaPairV1ToV2, downgradeSchemaPairV2ToV1, SchemaMigrationError } from '../dist/packages/schema-migration-v1-v2/src/index.js';

const scoreV1=()=>createScoreDocument({schemaVersion:'1.0.0',id:'doc-migrate',revision:{id:'rev-1',parentId:null},source:{sha256:'b'.repeat(64),format:'synthetic',byteLength:null},parts:[{id:'part-1',name:'Part',staves:[{id:'staff-1',ordinal:1,measures:[{id:'measure-1',ordinal:1,displayNumber:'1',voices:[{id:'voice-1',ordinal:1,events:[{id:'event-1',kind:'note',onset:{numerator:0,denominator:1},duration:{numerator:1,denominator:4},note:{id:'note-1',pitch:{step:'C',alter:0,octave:4}}}]}]}]}]}]});
const notationV1=(score)=>createNotationDocument(score,{contractVersion:'1.0.0',documentId:score.id,revisionId:score.revision.id,measures:[{target:addressEntity(score,'measure-1'),notation:{timeSignature:{beats:4,beatType:4},keySignature:null,clef:null,barlines:[]}}],events:[{target:addressEntity(score,'event-1'),notation:{dots:1,beams:[],tuplet:null}}],notes:[{target:addressEntity(score,'note-1'),notation:{accidental:'natural',ties:[],slurs:[]}}]});

test('v1 to v2 pair migration is deterministic and preserves document/revision/source identity',()=>{const score=scoreV1(),notation=notationV1(score);const first=migrateSchemaPairV1ToV2(score,notation),second=migrateSchemaPairV1ToV2(score,notation);assert.deepEqual(first,second);assert.equal(first.score.schemaVersion,'2.0.0');assert.equal(first.notation.contractVersion,'2.0.0');assert.equal(first.score.id,score.id);assert.deepEqual(first.score.revision,score.revision);assert.deepEqual(first.score.source,score.source);assert.deepEqual(first.score.parts[0].staves[0].measures[0].voices[0].graceGroups,[]);assert.deepEqual(first.notation.events[0].notation.articulations,[]);assert.deepEqual(first.notation.events[0].notation.ornaments,[]);assert.deepEqual(first.notation.graceEvents,[]);assert.deepEqual(first.notation.graceNotes,[]);});

test('clean v2 pair downgrades to v1 without semantic loss',()=>{const score=scoreV1(),notation=notationV1(score);const v2=migrateSchemaPairV1ToV2(score,notation);const back=downgradeSchemaPairV2ToV1(v2.score,v2.notation);assert.deepEqual(back.score,score);assert.deepEqual(back.notation,notation);});

test('v2 to v1 downgrade rejects canonical grace semantics with exact loss path',()=>{const score=scoreV1(),notation=notationV1(score);const clean=migrateSchemaPairV1ToV2(score,notation);const raw=JSON.parse(JSON.stringify(clean.score));raw.parts[0].staves[0].measures[0].voices[0].graceGroups=[{id:'grace-group-1',anchorEventId:'event-1',placement:'before',events:[{id:'grace-event-1',kind:'note',writtenDuration:{numerator:1,denominator:8},playback:{stealTimePreviousPercent:null,stealTimeFollowingPercent:null,makeTime:null},note:{id:'grace-note-1',pitch:{step:'D',alter:0,octave:4}}}]}];const scoreV2=createScoreDocumentV2(raw);assert.throws(()=>downgradeSchemaPairV2ToV1(scoreV2,clean.notation),(e)=>e instanceof SchemaMigrationError&&e.code==='DOWNGRADE_UNREPRESENTABLE'&&e.details.paths.some(p=>p.endsWith('.graceGroups')));});

test('v2 to v1 downgrade rejects articulation rather than silently discarding it',()=>{const score=scoreV1(),notation=notationV1(score);const clean=migrateSchemaPairV1ToV2(score,notation);const raw=JSON.parse(JSON.stringify(clean.notation));raw.events[0].notation.articulations=[{kind:'accent',placement:'above',direction:null}];const notationV2=createNotationDocumentV2(clean.score,raw);assert.throws(()=>downgradeSchemaPairV2ToV1(clean.score,notationV2),(e)=>e instanceof SchemaMigrationError&&e.code==='DOWNGRADE_UNREPRESENTABLE'&&e.details.paths.includes('$.events[0].notation.articulations'));});

test('pure migration converts address contract versions while preserving exact entity ancestry',()=>{const score=scoreV1(),notation=notationV1(score);const v2=migrateSchemaPairV1ToV2(score,notation);const v1Target=notation.events[0].target,v2Target=v2.notation.events[0].target;assert.equal(v1Target.contractVersion,'1.0.0');assert.equal(v2Target.contractVersion,'2.0.0');for(const field of ['documentId','revisionId','partId','staffId','measureId','voiceId','eventId'])assert.equal(v2Target[field],v1Target[field]);assert.deepEqual(addressEntityV2(v2.score,'event-1'),v2Target);});
