import { createScoreDocumentV3, type ScoreDocumentV3 } from '../../score-model-v3/src/index.js';
import type { ScoreEvent } from '../../score-model/src/index.js';
import {
  addressEntityV3,
  resolveSemanticAddressV3,
  type EventAddressV3,
  type GraceEventAddressV3,
  type SemanticAddressV3
} from '../../addressing-v3/src/index.js';
import { createNotationDocumentV4, type NotationDocumentV4 } from '../../notation-structure-v4/src/index.js';
import type { EventNotationV2, GraceEventNotationV2, OrnamentSpec, PlacementV2, SimpleOrnamentSpec, TremoloOrnamentSpec } from '../../notation-structure-v2/src/index.js';

export const ORNAMENT_AUTHORING_V4_VERSION='1.0.0' as const;
export type LocalOrnamentSpecV4=SimpleOrnamentSpec|(Omit<TremoloOrnamentSpec,'type'|'number'>&{readonly type:'single';readonly number:null});
export type OrnamentTargetV4=EventAddressV3|GraceEventAddressV3;
export interface OrnamentAuthoringV4Options { readonly nextRevisionId:string }
export type OrnamentAuthoringIntentV4=
  | { readonly version:typeof ORNAMENT_AUTHORING_V4_VERSION; readonly type:'ADD_LOCAL_ORNAMENT'; readonly target:OrnamentTargetV4; readonly value:LocalOrnamentSpecV4 }
  | { readonly version:typeof ORNAMENT_AUTHORING_V4_VERSION; readonly type:'TOGGLE_LOCAL_ORNAMENT'; readonly target:OrnamentTargetV4; readonly value:LocalOrnamentSpecV4 }
  | { readonly version:typeof ORNAMENT_AUTHORING_V4_VERSION; readonly type:'REMOVE_LOCAL_ORNAMENT'; readonly target:OrnamentTargetV4; readonly value:LocalOrnamentSpecV4 }
  | { readonly version:typeof ORNAMENT_AUTHORING_V4_VERSION; readonly type:'CREATE_TREMOLO_RELATION'; readonly start:EventAddressV3; readonly stop:EventAddressV3; readonly number:number; readonly marks:number; readonly placement:PlacementV2 }
  | { readonly version:typeof ORNAMENT_AUTHORING_V4_VERSION; readonly type:'REMOVE_TREMOLO_RELATION'; readonly start:EventAddressV3; readonly stop:EventAddressV3; readonly number:number }
  | { readonly version:typeof ORNAMENT_AUTHORING_V4_VERSION; readonly type:'CREATE_WAVY_LINE_RELATION'; readonly targets:readonly EventAddressV3[]; readonly number:number; readonly placement:PlacementV2 }
  | { readonly version:typeof ORNAMENT_AUTHORING_V4_VERSION; readonly type:'REMOVE_WAVY_LINE_RELATION'; readonly targets:readonly EventAddressV3[]; readonly number:number };
export interface OrnamentAuthoringV4Result { readonly score:Readonly<ScoreDocumentV3>; readonly notation:Readonly<NotationDocumentV4>; readonly selection:SemanticAddressV3 }
export type OrnamentAuthoringV4ErrorCode='INVALID_INTENT'|'STALE_TARGET'|'INVALID_REVISION_ID'|'INVALID_LOCAL_ORNAMENT'|'DUPLICATE_ORNAMENT'|'RELATION_SCOPE_UNSUPPORTED'|'RELATION_NUMBER_IN_USE'|'RELATION_NOT_FOUND'|'INVALID_RELATION_ORDER'|'RELATION_ENDPOINT_NOT_PITCHED'|'RESULT_INVALID';
export class OrnamentAuthoringV4Error extends Error { readonly code:OrnamentAuthoringV4ErrorCode; readonly details:Readonly<Record<string,unknown>>; constructor(message:string,code:OrnamentAuthoringV4ErrorCode,details:Record<string,unknown>={}){super(message);this.name='OrnamentAuthoringV4Error';this.code=code;this.details=Object.freeze({...details});Object.freeze(this);} }

const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const rec=(v:unknown):v is Record<string,unknown>=>v!==null&&typeof v==='object'&&!Array.isArray(v);
const exact=(v:unknown,k:readonly string[]):v is Record<string,unknown>=>rec(v)&&JSON.stringify(Object.keys(v).sort())===JSON.stringify([...k].sort());
const same=(a:unknown,b:unknown):boolean=>JSON.stringify(a)===JSON.stringify(b);
const validNumber=(v:unknown):v is number=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=1&&v<=16;
const validMarks=(v:unknown):v is number=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=1&&v<=8;
const validPlacement=(v:unknown):v is PlacementV2=>v==='auto'||v==='above'||v==='below';
const fields:Record<string,readonly string[]>={ADD_LOCAL_ORNAMENT:['version','type','target','value'],TOGGLE_LOCAL_ORNAMENT:['version','type','target','value'],REMOVE_LOCAL_ORNAMENT:['version','type','target','value'],CREATE_TREMOLO_RELATION:['version','type','start','stop','number','marks','placement'],REMOVE_TREMOLO_RELATION:['version','type','start','stop','number'],CREATE_WAVY_LINE_RELATION:['version','type','targets','number','placement'],REMOVE_WAVY_LINE_RELATION:['version','type','targets','number']};
const parse=(raw:unknown):OrnamentAuthoringIntentV4=>{if(!rec(raw)||raw.version!==ORNAMENT_AUTHORING_V4_VERSION||typeof raw.type!=='string'||fields[raw.type]===undefined||!exact(raw,fields[raw.type]!))throw new OrnamentAuthoringV4Error('Ornament intent is invalid.','INVALID_INTENT');return raw as unknown as OrnamentAuthoringIntentV4;};
const isLocal=(v:unknown):v is LocalOrnamentSpecV4=>rec(v)&&typeof v.kind==='string'&&v.kind!=='wavy-line'&&(v.kind!=='tremolo'||(v.type==='single'&&v.number===null));
const validateLocal=(score:ScoreDocumentV3,target:OrnamentTargetV4):void=>{try{const r=resolveSemanticAddressV3(score,target);if(r.kind!=='event'&&r.kind!=='grace-event')throw new Error(`observed ${r.kind}`);}catch(error){throw new OrnamentAuthoringV4Error('Ornament target is stale or invalid.','STALE_TARGET',{cause:error instanceof Error?error.message:String(error)});}};
const normalEvent=(score:ScoreDocumentV3,target:EventAddressV3):ScoreEvent=>{try{const r=resolveSemanticAddressV3(score,target);if(r.kind!=='event')throw new Error(`observed ${r.kind}`);return r.value;}catch(error){throw new OrnamentAuthoringV4Error('Relation endpoint is stale or invalid.','STALE_TARGET',{cause:error instanceof Error?error.message:String(error)});}};
const defaultEvent=():EventNotationV2=>({dots:0,beams:[],tuplet:null,articulations:[],ornaments:[]});
const defaultGrace=():GraceEventNotationV2=>({slash:false,dots:0,beams:[],articulations:[],ornaments:[]});
const sameScope=(targets:readonly EventAddressV3[]):boolean=>targets.length>0&&targets.every(t=>t.partId===targets[0]!.partId&&t.staffId===targets[0]!.staffId&&t.frameId===targets[0]!.frameId&&t.measureId===targets[0]!.measureId&&t.voiceId===targets[0]!.voiceId);
const ordered=(score:ScoreDocumentV3,targets:readonly EventAddressV3[]):readonly number[]=>{if(targets.length<2||targets.length>32||!sameScope(targets))throw new OrnamentAuthoringV4Error('Spanning ornament targets must contain 2..32 normal events in one exact frame/measure/voice.','RELATION_SCOPE_UNSUPPORTED');const first=targets[0]!;const part=score.parts.find(p=>p.id===first.partId);const staff=part?.staves.find(s=>s.id===first.staffId);if(!staff||staff.role==='tablature-linked')throw new OrnamentAuthoringV4Error('Relation staff is invalid.','STALE_TARGET');const measure=staff.measures.find(m=>m.id===first.measureId&&m.frameId===first.frameId);const voice=measure?.voices.find(v=>v.id===first.voiceId);if(!voice)throw new OrnamentAuthoringV4Error('Relation voice no longer exists.','STALE_TARGET');const indices=targets.map(t=>{const e=normalEvent(score,t);if(e.kind==='rest')throw new OrnamentAuthoringV4Error('Spanning ornament members must be pitched events.','RELATION_ENDPOINT_NOT_PITCHED',{eventId:e.id});const i=voice.events.findIndex(x=>x.id===t.eventId);if(i<0)throw new OrnamentAuthoringV4Error('Relation target is outside addressed voice.','STALE_TARGET');return i;});if(new Set(indices).size!==indices.length||indices.some((v,i)=>i>0&&v<=(indices[i-1]??-1)))throw new OrnamentAuthoringV4Error('Relation targets must be unique and strictly increasing.','INVALID_RELATION_ORDER',{indices});return Object.freeze(indices);};
const relationMatches=(o:OrnamentSpec,kind:'tremolo'|'wavy-line',number:number):boolean=>kind==='wavy-line'?o.kind==='wavy-line'&&o.number===number:o.kind==='tremolo'&&o.type!=='single'&&o.number===number;
const all=(n:NotationDocumentV4):readonly OrnamentSpec[]=>[...n.events.flatMap(e=>e.notation.ornaments),...n.graceEvents.flatMap(e=>e.notation.ornaments)];
const relationInUse=(n:NotationDocumentV4,kind:'tremolo'|'wavy-line',number:number):boolean=>all(n).some(o=>relationMatches(o,kind,number));
const relationMembers=(n:NotationDocumentV4,kind:'tremolo'|'wavy-line',number:number):readonly string[]=>{const members=n.events.filter(e=>e.notation.ornaments.some(o=>relationMatches(o,kind,number))).map(e=>e.target.eventId);if(n.graceEvents.some(e=>e.notation.ornaments.some(o=>relationMatches(o,kind,number))))throw new OrnamentAuthoringV4Error('Spanning relations across grace events are unsupported.','RELATION_SCOPE_UNSUPPORTED',{kind,number});return Object.freeze(members);};
const without=(items:readonly OrnamentSpec[],kind:'tremolo'|'wavy-line',number:number):readonly OrnamentSpec[]=>items.filter(o=>!relationMatches(o,kind,number));
const targetId=(a:SemanticAddressV3):string=>{switch(a.kind){case'document':return a.documentId;case'measure-frame':return a.frameId;case'part':return a.partId;case'staff':return a.staffId;case'measure':return a.measureId;case'voice':return a.voiceId;case'event':return a.eventId;case'note':return a.noteId;case'grace-group':return a.graceGroupId;case'grace-event':return a.graceEventId;case'grace-note':return a.graceNoteId;}};
const rebind=(score:ScoreDocumentV3,a:SemanticAddressV3):SemanticAddressV3=>addressEntityV3(score,targetId(a));

export const executeOrnamentAuthoringV4=(scoreInput:ScoreDocumentV3,notationInput:NotationDocumentV4,rawIntent:unknown,options:OrnamentAuthoringV4Options):Readonly<OrnamentAuthoringV4Result>=>{
  const score=createScoreDocumentV3(scoreInput);const notation=createNotationDocumentV4(score,notationInput);const intent=parse(rawIntent);if(!ID.test(options.nextRevisionId)||options.nextRevisionId===score.revision.id)throw new OrnamentAuthoringV4Error('A fresh stable next revision id is required.','INVALID_REVISION_ID');
  const normal=new Map(notation.events.map(e=>[e.target.eventId,e.notation]));const grace=new Map(notation.graceEvents.map(e=>[e.target.graceEventId,e.notation]));let selectionId:string;
  if(intent.type==='ADD_LOCAL_ORNAMENT'||intent.type==='TOGGLE_LOCAL_ORNAMENT'||intent.type==='REMOVE_LOCAL_ORNAMENT'){
    validateLocal(score,intent.target);if(!isLocal(intent.value))throw new OrnamentAuthoringV4Error('Local ornament operation accepts only simple ornaments or single-note tremolo.','INVALID_LOCAL_ORNAMENT');selectionId=intent.target.kind==='event'?intent.target.eventId:intent.target.graceEventId;const current=intent.target.kind==='event'?(normal.get(selectionId)??defaultEvent()):(grace.get(selectionId)??defaultGrace());const existing=current.ornaments.findIndex(x=>same(x,intent.value));let ornaments:readonly OrnamentSpec[];if(intent.type==='ADD_LOCAL_ORNAMENT'){if(existing>=0)throw new OrnamentAuthoringV4Error('Ornament already exists.','DUPLICATE_ORNAMENT');ornaments=[...current.ornaments,intent.value];}else if(intent.type==='TOGGLE_LOCAL_ORNAMENT'){ornaments=existing>=0?current.ornaments.filter((_,i)=>i!==existing):[...current.ornaments,intent.value];}else ornaments=existing>=0?current.ornaments.filter((_,i)=>i!==existing):current.ornaments;if(intent.target.kind==='event')normal.set(selectionId,{...(current as EventNotationV2),ornaments});else grace.set(selectionId,{...(current as GraceEventNotationV2),ornaments});
  }else if(intent.type==='CREATE_TREMOLO_RELATION'){
    if(!validNumber(intent.number)||!validMarks(intent.marks)||!validPlacement(intent.placement))throw new OrnamentAuthoringV4Error('Tremolo relation parameters are invalid.','INVALID_INTENT');ordered(score,[intent.start,intent.stop]);if(relationInUse(notation,'tremolo',intent.number))throw new OrnamentAuthoringV4Error('Tremolo relation number is already in use.','RELATION_NUMBER_IN_USE',{number:intent.number});const start=normal.get(intent.start.eventId)??defaultEvent(),stop=normal.get(intent.stop.eventId)??defaultEvent();normal.set(intent.start.eventId,{...start,ornaments:[...start.ornaments,{kind:'tremolo',type:'start',marks:intent.marks,number:intent.number,placement:intent.placement}]});normal.set(intent.stop.eventId,{...stop,ornaments:[...stop.ornaments,{kind:'tremolo',type:'stop',marks:intent.marks,number:intent.number,placement:intent.placement}]});selectionId=intent.start.eventId;
  }else if(intent.type==='REMOVE_TREMOLO_RELATION'){
    if(!validNumber(intent.number))throw new OrnamentAuthoringV4Error('Tremolo relation number is invalid.','INVALID_INTENT');ordered(score,[intent.start,intent.stop]);const members=relationMembers(notation,'tremolo',intent.number);if(!same(members,[intent.start.eventId,intent.stop.eventId]))throw new OrnamentAuthoringV4Error('Exact tremolo endpoints were not found.','RELATION_NOT_FOUND',{members});const start=normal.get(intent.start.eventId)??defaultEvent(),stop=normal.get(intent.stop.eventId)??defaultEvent();normal.set(intent.start.eventId,{...start,ornaments:without(start.ornaments,'tremolo',intent.number)});normal.set(intent.stop.eventId,{...stop,ornaments:without(stop.ornaments,'tremolo',intent.number)});selectionId=intent.start.eventId;
  }else if(intent.type==='CREATE_WAVY_LINE_RELATION'){
    if(!Array.isArray(intent.targets)||!validNumber(intent.number)||!validPlacement(intent.placement))throw new OrnamentAuthoringV4Error('Wavy-line parameters are invalid.','INVALID_INTENT');ordered(score,intent.targets);if(relationInUse(notation,'wavy-line',intent.number))throw new OrnamentAuthoringV4Error('Wavy-line relation number is already in use.','RELATION_NUMBER_IN_USE',{number:intent.number});intent.targets.forEach((t,i)=>{const current=normal.get(t.eventId)??defaultEvent();const type=i===0?'start':i===intent.targets.length-1?'stop':'continue';normal.set(t.eventId,{...current,ornaments:[...current.ornaments,{kind:'wavy-line',type,number:intent.number,placement:intent.placement}]});});selectionId=intent.targets[0]!.eventId;
  }else{
    if(!Array.isArray(intent.targets)||!validNumber(intent.number))throw new OrnamentAuthoringV4Error('Wavy-line parameters are invalid.','INVALID_INTENT');ordered(score,intent.targets);const members=relationMembers(notation,'wavy-line',intent.number),expected=intent.targets.map(t=>t.eventId);if(!same(members,expected))throw new OrnamentAuthoringV4Error('Exact wavy-line relation members were not found.','RELATION_NOT_FOUND',{members,expected});for(const t of intent.targets){const current=normal.get(t.eventId)??defaultEvent();normal.set(t.eventId,{...current,ornaments:without(current.ornaments,'wavy-line',intent.number)});}selectionId=intent.targets[0]!.eventId;
  }
  const candidate=structuredClone(score) as ScoreDocumentV3;(candidate as {revision:{id:string;parentId:string|null}}).revision={id:options.nextRevisionId,parentId:score.revision.id};const nextScore=createScoreDocumentV3(candidate);
  try{const nextNotation=createNotationDocumentV4(nextScore,{contractVersion:'4.0.0',documentId:nextScore.id,revisionId:nextScore.revision.id,frames:notation.frames.map(e=>({target:rebind(nextScore,e.target) as typeof e.target,notation:e.notation})),measures:notation.measures.map(e=>({target:rebind(nextScore,e.target) as typeof e.target,notation:e.notation})),events:[...normal].map(([id,value])=>({target:addressEntityV3(nextScore,id) as EventAddressV3,notation:value})),notes:notation.notes.map(e=>({target:rebind(nextScore,e.target) as typeof e.target,notation:e.notation})),graceEvents:[...grace].map(([id,value])=>({target:addressEntityV3(nextScore,id) as GraceEventAddressV3,notation:value})),graceNotes:notation.graceNotes.map(e=>({target:rebind(nextScore,e.target) as typeof e.target,notation:e.notation})),crossStaffPlacements:notation.crossStaffPlacements.map(p=>({source:rebind(nextScore,p.source) as EventAddressV3,displayStaffId:p.displayStaffId}))});return Object.freeze({score:nextScore,notation:nextNotation,selection:addressEntityV3(nextScore,selectionId)});}catch(error){throw new OrnamentAuthoringV4Error('Ornament result failed V4 validation.','RESULT_INVALID',{cause:error instanceof Error?error.message:String(error)});}
};
