import { createScoreDocumentV2 } from '../../score-model-v2/src/index.js';
import { createNotationDocumentV2, type EventNotationV2, type GraceEventNotationV2, type GraceNoteNotationV2 } from '../../notation-structure-v2/src/index.js';
import type { BarlineSpec, ClefSpec, KeySignature, NoteNotation, TimeSignature } from '../../notation-structure/src/index.js';
import { addressEntityV2, type EventAddressV2, type GraceEventAddressV2, type GraceNoteAddressV2, type MeasureAddressV2, type NoteAddressV2 } from '../../addressing-v2/src/index.js';
import { addressEntityV3, resolveSemanticAddressV3, type EventAddressV3, type GraceEventAddressV3, type GraceNoteAddressV3, type MeasureAddressV3, type MeasureFrameAddressV3, type NoteAddressV3, type SemanticAddressV3 } from '../../addressing-v3/src/index.js';
import { createScoreDocumentV3, type ContentStaffV3, type ScoreDocumentV3 } from '../../score-model-v3/src/index.js';

export const NOTATION_DOCUMENT_V3_VERSION='3.0.0' as const;
export interface MeasureFrameNotationV3 { readonly timeSignature:TimeSignature|null; readonly barlines:readonly BarlineSpec[] }
export interface StaffMeasureNotationV3 { readonly keySignature:KeySignature|null; readonly clef:ClefSpec|null }
export interface FrameNotationEntryV3 { readonly target:MeasureFrameAddressV3; readonly notation:MeasureFrameNotationV3 }
export interface StaffMeasureNotationEntryV3 { readonly target:MeasureAddressV3; readonly notation:StaffMeasureNotationV3 }
export interface EventNotationEntryV3 { readonly target:EventAddressV3; readonly notation:EventNotationV2 }
export interface NoteNotationEntryV3 { readonly target:NoteAddressV3; readonly notation:NoteNotation }
export interface GraceEventNotationEntryV3 { readonly target:GraceEventAddressV3; readonly notation:GraceEventNotationV2 }
export interface GraceNoteNotationEntryV3 { readonly target:GraceNoteAddressV3; readonly notation:GraceNoteNotationV2 }
export interface NotationDocumentV3 { readonly contractVersion:typeof NOTATION_DOCUMENT_V3_VERSION; readonly documentId:string; readonly revisionId:string; readonly frames:readonly FrameNotationEntryV3[]; readonly measures:readonly StaffMeasureNotationEntryV3[]; readonly events:readonly EventNotationEntryV3[]; readonly notes:readonly NoteNotationEntryV3[]; readonly graceEvents:readonly GraceEventNotationEntryV3[]; readonly graceNotes:readonly GraceNoteNotationEntryV3[] }
export class NotationV3Error extends Error { readonly code:'INVALID_NOTATION'|'STALE_NOTATION'|'DUPLICATE_TARGET'|'TARGET_KIND_MISMATCH'; constructor(message:string,code:'INVALID_NOTATION'|'STALE_NOTATION'|'DUPLICATE_TARGET'|'TARGET_KIND_MISMATCH'){super(message);this.name='NotationV3Error';this.code=code;} }

type R=Record<string,unknown>;
const rec=(v:unknown):v is R=>v!==null&&typeof v==='object'&&!Array.isArray(v);
const exact=(v:unknown,keys:readonly string[]):v is R=>rec(v)&&JSON.stringify(Object.keys(v).sort())===JSON.stringify([...keys].sort());
const projectScore=(score:ScoreDocumentV3)=>createScoreDocumentV2({schemaVersion:'2.0.0',id:score.id,revision:score.revision,source:score.source,parts:score.parts.map(part=>({id:part.id,name:part.name,staves:part.staves.filter((s):s is ContentStaffV3=>s.role!=='tablature-linked').map((staff,si)=>({id:staff.id,ordinal:si+1,measures:staff.measures.map((measure,mi)=>({id:measure.id,ordinal:mi+1,displayNumber:score.measureFrames[mi]?.displayNumber??null,voices:measure.voices}))}))}))});
const ensureTarget=(score:ScoreDocumentV3,target:SemanticAddressV3,kind:SemanticAddressV3['kind']):void=>{try{const resolved=resolveSemanticAddressV3(score,target);if(resolved.kind!==kind)throw new Error(`observed ${resolved.kind}`);}catch(error){throw new NotationV3Error(`Notation target is invalid: ${error instanceof Error?error.message:String(error)}`,'TARGET_KIND_MISMATCH');}};
const assertUniqueStrings=(values:readonly string[]):void=>{const seen=new Set<string>();for(const value of values){if(seen.has(value))throw new NotationV3Error(`Duplicate notation target: ${value}`,'DUPLICATE_TARGET');seen.add(value);}};
const mapEventEntries=(projected:ReturnType<typeof projectScore>,items:readonly EventNotationEntryV3[]):{target:EventAddressV2;notation:EventNotationV2}[]=>items.map(entry=>{const a=addressEntityV2(projected,entry.target.eventId);if(a.kind!=='event')throw new NotationV3Error('Projected event address changed kind.','INVALID_NOTATION');return {target:a,notation:entry.notation};});
const mapNoteEntries=(projected:ReturnType<typeof projectScore>,items:readonly NoteNotationEntryV3[]):{target:NoteAddressV2;notation:NoteNotation}[]=>items.map(entry=>{const a=addressEntityV2(projected,entry.target.noteId);if(a.kind!=='note')throw new NotationV3Error('Projected note address changed kind.','INVALID_NOTATION');return {target:a,notation:entry.notation};});
const mapGraceEventEntries=(projected:ReturnType<typeof projectScore>,items:readonly GraceEventNotationEntryV3[]):{target:GraceEventAddressV2;notation:GraceEventNotationV2}[]=>items.map(entry=>{const a=addressEntityV2(projected,entry.target.graceEventId);if(a.kind!=='grace-event')throw new NotationV3Error('Projected grace-event address changed kind.','INVALID_NOTATION');return {target:a,notation:entry.notation};});
const mapGraceNoteEntries=(projected:ReturnType<typeof projectScore>,items:readonly GraceNoteNotationEntryV3[]):{target:GraceNoteAddressV2;notation:GraceNoteNotationV2}[]=>items.map(entry=>{const a=addressEntityV2(projected,entry.target.graceNoteId);if(a.kind!=='grace-note')throw new NotationV3Error('Projected grace-note address changed kind.','INVALID_NOTATION');return {target:a,notation:entry.notation};});

export const createNotationDocumentV3=(scoreInput:ScoreDocumentV3,input:NotationDocumentV3):Readonly<NotationDocumentV3>=>{
  const score=createScoreDocumentV3(scoreInput);if(!exact(input,['contractVersion','documentId','revisionId','frames','measures','events','notes','graceEvents','graceNotes'])||input.contractVersion!==NOTATION_DOCUMENT_V3_VERSION)throw new NotationV3Error('NotationDocumentV3 envelope is invalid.','INVALID_NOTATION');if(input.documentId!==score.id||input.revisionId!==score.revision.id)throw new NotationV3Error('NotationDocumentV3 belongs to another revision.','STALE_NOTATION');
  input.frames.forEach(entry=>ensureTarget(score,entry.target,'measure-frame'));input.measures.forEach(entry=>ensureTarget(score,entry.target,'measure'));input.events.forEach(entry=>ensureTarget(score,entry.target,'event'));input.notes.forEach(entry=>ensureTarget(score,entry.target,'note'));input.graceEvents.forEach(entry=>ensureTarget(score,entry.target,'grace-event'));input.graceNotes.forEach(entry=>ensureTarget(score,entry.target,'grace-note'));
  assertUniqueStrings(input.frames.map(entry=>entry.target.frameId));assertUniqueStrings(input.measures.map(entry=>entry.target.measureId));assertUniqueStrings(input.events.map(entry=>entry.target.eventId));assertUniqueStrings(input.notes.map(entry=>entry.target.noteId));assertUniqueStrings(input.graceEvents.map(entry=>entry.target.graceEventId));assertUniqueStrings(input.graceNotes.map(entry=>entry.target.graceNoteId));
  const projected=projectScore(score);const frameById=new Map(input.frames.map(entry=>[entry.target.frameId,entry.notation]));const measureById=new Map(input.measures.map(entry=>[entry.target.measureId,entry.notation]));const measures:{target:MeasureAddressV2;notation:{timeSignature:TimeSignature|null;keySignature:KeySignature|null;clef:ClefSpec|null;barlines:readonly BarlineSpec[]}}[]=[];
  for(const part of score.parts)for(const staff of part.staves){if(staff.role==='tablature-linked')continue;for(const measure of staff.measures){const frame=frameById.get(measure.frameId);const local=measureById.get(measure.id);if(frame===undefined&&local===undefined)continue;const a=addressEntityV2(projected,measure.id);if(a.kind!=='measure')throw new NotationV3Error('Projected measure address changed kind.','INVALID_NOTATION');measures.push({target:a,notation:{timeSignature:frame?.timeSignature??null,keySignature:local?.keySignature??null,clef:local?.clef??null,barlines:frame?.barlines??[]}});}}
  createNotationDocumentV2(projected,{contractVersion:'2.0.0',documentId:projected.id,revisionId:projected.revision.id,measures,events:mapEventEntries(projected,input.events),notes:mapNoteEntries(projected,input.notes),graceEvents:mapGraceEventEntries(projected,input.graceEvents),graceNotes:mapGraceNoteEntries(projected,input.graceNotes)});
  const cloned=structuredClone(input) as NotationDocumentV3;Object.freeze(cloned.frames);Object.freeze(cloned.measures);Object.freeze(cloned.events);Object.freeze(cloned.notes);Object.freeze(cloned.graceEvents);Object.freeze(cloned.graceNotes);return Object.freeze(cloned);
};
export const emptyNotationDocumentV3=(score:ScoreDocumentV3):Readonly<NotationDocumentV3>=>createNotationDocumentV3(score,{contractVersion:'3.0.0',documentId:score.id,revisionId:score.revision.id,frames:[],measures:[],events:[],notes:[],graceEvents:[],graceNotes:[]});
export const defaultFrameNotationV3=():MeasureFrameNotationV3=>Object.freeze({timeSignature:null,barlines:Object.freeze([])});
export const defaultStaffMeasureNotationV3=():StaffMeasureNotationV3=>Object.freeze({keySignature:null,clef:null});
export const frameAddressV3=(score:ScoreDocumentV3,frameId:string):MeasureFrameAddressV3=>{const a=addressEntityV3(score,frameId);if(a.kind!=='measure-frame')throw new NotationV3Error('Target is not a measure frame.','TARGET_KIND_MISMATCH');return a;};
