import { createScoreDocumentV2 } from '../../score-model-v2/src/index.js';
import { createNotationDocumentV2, type EventNotationV2, type GraceEventNotationV2, type GraceNoteNotationV2 } from '../../notation-structure-v2/src/index.js';
import type { BarlineSpec, ClefSpec, KeySignature, NoteNotation, TimeSignature } from '../../notation-structure/src/index.js';
import { addressEntityV2, type EventAddressV2, type GraceEventAddressV2, type GraceNoteAddressV2, type MeasureAddressV2, type NoteAddressV2 } from '../../addressing-v2/src/index.js';
import { addressEntityV3, resolveSemanticAddressV3, type EventAddressV3, type GraceEventAddressV3, type GraceNoteAddressV3, type MeasureAddressV3, type MeasureFrameAddressV3, type NoteAddressV3 } from '../../addressing-v3/src/index.js';
import { createScoreDocumentV3, type ContentStaffV3, type ScoreDocumentV3 } from '../../score-model-v3/src/index.js';

export const NOTATION_DOCUMENT_V3_VERSION='3.0.0' as const;
export interface MeasureFrameNotationV3 { readonly timeSignature:TimeSignature|null; readonly barlines:readonly BarlineSpec[] }
export interface StaffMeasureNotationV3 { readonly keySignature:KeySignature|null; readonly clef:ClefSpec|null }
export interface FrameNotationEntryV3 { readonly target:MeasureFrameAddressV3; readonly notation:MeasureFrameNotationV3 }
export interface StaffMeasureNotationEntryV3 { readonly target:MeasureAddressV3; readonly notation:StaffMeasureNotationV3 }
export interface EventNotationEntryV3 { readonly target:EventAddressV3; readonly notation:EventNotationV2 }
export interface NoteNotationEntryV3 { readonly target:NoteAddressV3; readonly notation:NoteNotation }
export interface GraceEventNotationEntryV3 { readonly target:GraceEventAddressV3; readonly notation:GraceEventNotationV2 }
export interface GraceNoteNotationEntryV3 { readonly target:GraceNoteAddressV3; readonly notation:GraceNoteNotationV2 }
export interface NotationDocumentV3 { readonly contractVersion:typeof NOTATION_DOCUMENT_V3_VERSION; readonly documentId:string; readonly revisionId:string; readonly frames:readonly FrameNotationEntryV3[]; readonly measures:readonly StaffMeasureNotationEntryV3[]; readonly events:readonly EventNotationEntryV3[]; readonly notes:readonly NoteNotationEntryV3[]; readonly graceEvents:readonly GraceEventNotationEntryV3[]; readonly graceNotes:readonly GraceNoteNotationEntryV3[] }
export class NotationV3Error extends Error { readonly code:'INVALID_NOTATION'|'STALE_NOTATION'|'DUPLICATE_TARGET'|'TARGET_KIND_MISMATCH'; constructor(message:string,code:'INVALID_NOTATION'|'STALE_NOTATION'|'DUPLICATE_TARGET'|'TARGET_KIND_MISMATCH'){super(message);this.name='NotationV3Error';this.code=code;} }
const rec=(v:unknown):v is Record<string,unknown>=>v!==null&&typeof v==='object'&&!Array.isArray(v);
const exact=(v:unknown,keys:readonly string[])=>rec(v)&&JSON.stringify(Object.keys(v).sort())===JSON.stringify([...keys].sort());
const content=(staff:ContentStaffV3)=>staff;
const projectScore=(score:ScoreDocumentV3)=>createScoreDocumentV2({schemaVersion:'2.0.0',id:score.id,revision:score.revision,source:score.source,parts:score.parts.map(part=>({id:part.id,name:part.name,staves:part.staves.filter((s):s is ContentStaffV3=>s.role!=='tablature-linked').map((staff,si)=>({id:staff.id,ordinal:si+1,measures:content(staff).measures.map((measure,mi)=>({id:measure.id,ordinal:mi+1,displayNumber:score.measureFrames[mi]?.displayNumber??null,voices:measure.voices}))}))}))});
const ensureTarget=(score:ScoreDocumentV3,target:unknown,kind:string):void=>{try{const resolved=resolveSemanticAddressV3(score,target as never);if(resolved.kind!==kind)throw new Error(`observed ${resolved.kind}`);}catch(error){throw new NotationV3Error(`Notation target is invalid: ${error instanceof Error?error.message:String(error)}`,'TARGET_KIND_MISMATCH');}};
const unique=(items:readonly {readonly target:unknown}[],identity:(t:never)=>string)=>{const seen=new Set<string>();for(const entry of items){const key=identity(entry.target as never);if(seen.has(key))throw new NotationV3Error(`Duplicate notation target: ${key}`,'DUPLICATE_TARGET');seen.add(key);}};
export const createNotationDocumentV3=(scoreInput:ScoreDocumentV3,input:NotationDocumentV3):Readonly<NotationDocumentV3>=>{const score=createScoreDocumentV3(scoreInput);if(!exact(input,['contractVersion','documentId','revisionId','frames','measures','events','notes','graceEvents','graceNotes'])||input.contractVersion!==NOTATION_DOCUMENT_V3_VERSION)throw new NotationV3Error('NotationDocumentV3 envelope is invalid.','INVALID_NOTATION');if(input.documentId!==score.id||input.revisionId!==score.revision.id)throw new NotationV3Error('NotationDocumentV3 belongs to another revision.','STALE_NOTATION');for(const [list,kind] of [[input.frames,'measure-frame'],[input.measures,'measure'],[input.events,'event'],[input.notes,'note'],[input.graceEvents,'grace-event'],[input.graceNotes,'grace-note']] as const)for(const entry of list)ensureTarget(score,entry.target,kind);
  unique(input.frames,t=>t.frameId);unique(input.measures,t=>t.measureId);unique(input.events,t=>t.eventId);unique(input.notes,t=>t.noteId);unique(input.graceEvents,t=>t.graceEventId);unique(input.graceNotes,t=>t.graceNoteId);
  const projected=projectScore(score);const frameById=new Map(input.frames.map(entry=>[entry.target.frameId,entry.notation]));const measureById=new Map(input.measures.map(entry=>[entry.target.measureId,entry.notation]));
  const measures:{target:MeasureAddressV2;notation:{timeSignature:TimeSignature|null;keySignature:KeySignature|null;clef:ClefSpec|null;barlines:readonly BarlineSpec[]}}[]=[];for(const part of score.parts)for(const staff of part.staves){if(staff.role==='tablature-linked')continue;for(const measure of staff.measures){const frame=frameById.get(measure.frameId);const local=measureById.get(measure.id);if(!frame&&!local)continue;const a=addressEntityV2(projected,measure.id);if(a.kind!=='measure')throw new NotationV3Error('Projected measure address changed kind.','INVALID_NOTATION');measures.push({target:a,notation:{timeSignature:frame?.timeSignature??null,keySignature:local?.keySignature??null,clef:local?.clef??null,barlines:frame?.barlines??[]}});}}
  const map=<T extends {readonly target:{readonly kind:string}}>(items:readonly T[],kind:string,idOf:(t:T['target'])=>string)=>items.map(entry=>{const a=addressEntityV2(projected,idOf(entry.target));if(a.kind!==kind)throw new NotationV3Error('Projected notation address changed kind.','INVALID_NOTATION');return {target:a,notation:(entry as T&{readonly notation:unknown}).notation};});
  createNotationDocumentV2(projected,{contractVersion:'2.0.0',documentId:projected.id,revisionId:projected.revision.id,measures,events:map(input.events,'event',t=>(t as EventAddressV3).eventId) as {target:EventAddressV2;notation:EventNotationV2}[],notes:map(input.notes,'note',t=>(t as NoteAddressV3).noteId) as {target:NoteAddressV2;notation:NoteNotation}[],graceEvents:map(input.graceEvents,'grace-event',t=>(t as GraceEventAddressV3).graceEventId) as {target:GraceEventAddressV2;notation:GraceEventNotationV2}[],graceNotes:map(input.graceNotes,'grace-note',t=>(t as GraceNoteAddressV3).graceNoteId) as {target:GraceNoteAddressV2;notation:GraceNoteNotationV2}[]});
  const clone=structuredClone(input) as NotationDocumentV3;Object.freeze(clone.frames);Object.freeze(clone.measures);Object.freeze(clone.events);Object.freeze(clone.notes);Object.freeze(clone.graceEvents);Object.freeze(clone.graceNotes);return Object.freeze(clone);
};
export const emptyNotationDocumentV3=(score:ScoreDocumentV3):Readonly<NotationDocumentV3>=>createNotationDocumentV3(score,{contractVersion:'3.0.0',documentId:score.id,revisionId:score.revision.id,frames:[],measures:[],events:[],notes:[],graceEvents:[],graceNotes:[]});
export const defaultFrameNotationV3=():MeasureFrameNotationV3=>Object.freeze({timeSignature:null,barlines:Object.freeze([])});
export const defaultStaffMeasureNotationV3=():StaffMeasureNotationV3=>Object.freeze({keySignature:null,clef:null});
export const frameAddressV3=(score:ScoreDocumentV3,frameId:string):MeasureFrameAddressV3=>{const a=addressEntityV3(score,frameId);if(a.kind!=='measure-frame')throw new NotationV3Error('Target is not a measure frame.','TARGET_KIND_MISMATCH');return a;};
