import { createScoreDocumentV3, type ScoreDocumentV3 } from '../../score-model-v3/src/index.js';
import { createNotationDocumentV4, type NotationDocumentV4 } from '../../notation-structure-v4/src/index.js';
import { addressEntityV3, resolveSemanticAddressV3, type EventAddressV3, type NoteAddressV3, type SemanticAddressV3 } from '../../addressing-v3/src/index.js';
import type { Pitch, Rational, ScoreEvent } from '../../score-model/src/index.js';

export const BASIC_AUTHORING_V4_VERSION='1.0.0' as const;
interface IntentBase { readonly version:typeof BASIC_AUTHORING_V4_VERSION; readonly type:string }
export interface SetNotePitchIntentV4 extends IntentBase { readonly type:'SET_NOTE_PITCH'; readonly target:NoteAddressV3; readonly pitch:Pitch }
export interface SetEventDurationIntentV4 extends IntentBase { readonly type:'SET_EVENT_DURATION'; readonly target:EventAddressV3; readonly duration:Rational }
export interface ReplaceRestWithNoteIntentV4 extends IntentBase { readonly type:'REPLACE_REST_WITH_NOTE'; readonly target:EventAddressV3; readonly noteId:string; readonly pitch:Pitch }
export interface ReplacePitchedEventWithRestIntentV4 extends IntentBase { readonly type:'REPLACE_PITCHED_EVENT_WITH_REST'; readonly target:EventAddressV3 }
export interface AddChordToneIntentV4 extends IntentBase { readonly type:'ADD_CHORD_TONE'; readonly target:EventAddressV3; readonly noteId:string; readonly pitch:Pitch }
export interface RemoveChordToneIntentV4 extends IntentBase { readonly type:'REMOVE_CHORD_TONE'; readonly target:NoteAddressV3 }
export type BasicAuthoringIntentV4=SetNotePitchIntentV4|SetEventDurationIntentV4|ReplaceRestWithNoteIntentV4|ReplacePitchedEventWithRestIntentV4|AddChordToneIntentV4|RemoveChordToneIntentV4;
export interface BasicAuthoringV4Options { readonly nextRevisionId:string }
export interface BasicAuthoringV4Result { readonly score:Readonly<ScoreDocumentV3>; readonly notation:Readonly<NotationDocumentV4>; readonly selection:SemanticAddressV3 }
export type BasicAuthoringV4ErrorCode='INVALID_INTENT'|'STALE_TARGET'|'TARGET_KIND_MISMATCH'|'EVENT_KIND_MISMATCH'|'IDENTITY_COLLISION'|'NOTATION_ORPHAN_RISK'|'CROSS_STAFF_CONFLICT'|'RESULT_INVALID';
export class BasicAuthoringV4Error extends Error { readonly code:BasicAuthoringV4ErrorCode; readonly details:Readonly<Record<string,unknown>>; constructor(message:string,code:BasicAuthoringV4ErrorCode,details:Record<string,unknown>={}){super(message);this.name='BasicAuthoringV4Error';this.code=code;this.details=Object.freeze({...details});} }

type R=Record<string,unknown>;
const rec=(v:unknown):v is R=>v!==null&&typeof v==='object'&&!Array.isArray(v);
const exact=(v:unknown,keys:readonly string[]):v is R=>rec(v)&&JSON.stringify(Object.keys(v).sort())===JSON.stringify([...keys].sort());
const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;const STEPS=new Set(['A','B','C','D','E','F','G']);
const gcd=(a:number,b:number):number=>{let x=Math.abs(a),y=Math.abs(b);while(y!==0)[x,y]=[y,x%y];return x;};
const parseId=(v:unknown,label:string):string=>{if(typeof v!=='string'||!ID.test(v))throw new BasicAuthoringV4Error(`${label} is invalid.`,'INVALID_INTENT');return v;};
const parsePitch=(v:unknown):Pitch=>{if(!exact(v,['step','alter','octave'])||typeof v.step!=='string'||!STEPS.has(v.step)||typeof v.alter!=='number'||!Number.isInteger(v.alter)||v.alter<-2||v.alter>2||typeof v.octave!=='number'||!Number.isInteger(v.octave)||v.octave<-1||v.octave>9)throw new BasicAuthoringV4Error('Pitch is invalid.','INVALID_INTENT');return {step:v.step as Pitch['step'],alter:v.alter,octave:v.octave};};
const parseRational=(v:unknown):Rational=>{if(!exact(v,['numerator','denominator'])||typeof v.numerator!=='number'||typeof v.denominator!=='number'||!Number.isSafeInteger(v.numerator)||!Number.isSafeInteger(v.denominator)||v.numerator<=0||v.denominator<=0||gcd(v.numerator,v.denominator)!==1)throw new BasicAuthoringV4Error('Duration must be a positive reduced rational.','INVALID_INTENT');return {numerator:v.numerator,denominator:v.denominator};};
const parseIntent=(raw:unknown):BasicAuthoringIntentV4=>{if(!rec(raw)||raw.version!==BASIC_AUTHORING_V4_VERSION||typeof raw.type!=='string')throw new BasicAuthoringV4Error('Basic authoring intent envelope is invalid.','INVALID_INTENT');switch(raw.type){case'SET_NOTE_PITCH':if(!exact(raw,['version','type','target','pitch']))throw new BasicAuthoringV4Error('SET_NOTE_PITCH field set is invalid.','INVALID_INTENT');return{version:'1.0.0',type:raw.type,target:raw.target as NoteAddressV3,pitch:parsePitch(raw.pitch)};case'SET_EVENT_DURATION':if(!exact(raw,['version','type','target','duration']))throw new BasicAuthoringV4Error('SET_EVENT_DURATION field set is invalid.','INVALID_INTENT');return{version:'1.0.0',type:raw.type,target:raw.target as EventAddressV3,duration:parseRational(raw.duration)};case'REPLACE_REST_WITH_NOTE':if(!exact(raw,['version','type','target','noteId','pitch']))throw new BasicAuthoringV4Error('REPLACE_REST_WITH_NOTE field set is invalid.','INVALID_INTENT');return{version:'1.0.0',type:raw.type,target:raw.target as EventAddressV3,noteId:parseId(raw.noteId,'noteId'),pitch:parsePitch(raw.pitch)};case'REPLACE_PITCHED_EVENT_WITH_REST':if(!exact(raw,['version','type','target']))throw new BasicAuthoringV4Error('REPLACE_PITCHED_EVENT_WITH_REST field set is invalid.','INVALID_INTENT');return{version:'1.0.0',type:raw.type,target:raw.target as EventAddressV3};case'ADD_CHORD_TONE':if(!exact(raw,['version','type','target','noteId','pitch']))throw new BasicAuthoringV4Error('ADD_CHORD_TONE field set is invalid.','INVALID_INTENT');return{version:'1.0.0',type:raw.type,target:raw.target as EventAddressV3,noteId:parseId(raw.noteId,'noteId'),pitch:parsePitch(raw.pitch)};case'REMOVE_CHORD_TONE':if(!exact(raw,['version','type','target']))throw new BasicAuthoringV4Error('REMOVE_CHORD_TONE field set is invalid.','INVALID_INTENT');return{version:'1.0.0',type:raw.type,target:raw.target as NoteAddressV3};default:throw new BasicAuthoringV4Error('Unsupported basic authoring intent.','INVALID_INTENT',{type:raw.type});}};

const resolveCurrent=<K extends 'event'|'note'>(score:ScoreDocumentV3,address:SemanticAddressV3,kind:K):Extract<ReturnType<typeof resolveSemanticAddressV3>,{kind:K}>=>{try{const resolved=resolveSemanticAddressV3(score,address);if(resolved.kind!==kind)throw new BasicAuthoringV4Error('Target kind does not match intent.','TARGET_KIND_MISMATCH',{expected:kind,observed:resolved.kind});return resolved as Extract<ReturnType<typeof resolveSemanticAddressV3>,{kind:K}>;}catch(error){if(error instanceof BasicAuthoringV4Error)throw error;const code=error instanceof Error&&'code'in error?String((error as{code?:unknown}).code):null;if(code==='STALE_REVISION'||code==='DOCUMENT_MISMATCH')throw new BasicAuthoringV4Error('Target belongs to another canonical revision.','STALE_TARGET',{addressingCode:code});throw new BasicAuthoringV4Error('Target does not resolve exactly.','TARGET_KIND_MISMATCH',{addressingCode:code});}};
const eventAddressForNote=(a:NoteAddressV3):EventAddressV3=>Object.freeze({contractVersion:'3.0.0',kind:'event',documentId:a.documentId,revisionId:a.revisionId,partId:a.partId,staffId:a.staffId,frameId:a.frameId,measureId:a.measureId,voiceId:a.voiceId,eventId:a.eventId});
const eventAt=(score:ScoreDocumentV3,address:EventAddressV3):ScoreEvent=>resolveCurrent(score,address,'event').value;
const allIds=(score:ScoreDocumentV3):Set<string>=>{const ids=new Set<string>();const visit=(v:unknown):void=>{if(Array.isArray(v)){v.forEach(visit);return;}if(rec(v)){for(const[k,item]of Object.entries(v)){if(k==='id'&&typeof item==='string')ids.add(item);visit(item);}}};visit(score);return ids;};
const ensureFreshId=(score:ScoreDocumentV3,value:string):void=>{if(allIds(score).has(value))throw new BasicAuthoringV4Error('New note identity collides with current canonical identity.','IDENTITY_COLLISION',{id:value});};
const targetId=(address:SemanticAddressV3):string=>{switch(address.kind){case'document':return address.documentId;case'measure-frame':return address.frameId;case'part':return address.partId;case'staff':return address.staffId;case'measure':return address.measureId;case'voice':return address.voiceId;case'event':return address.eventId;case'note':return address.noteId;case'grace-group':return address.graceGroupId;case'grace-event':return address.graceEventId;case'grace-note':return address.graceNoteId;}};
const rebindAddress=(score:ScoreDocumentV3,address:SemanticAddressV3):SemanticAddressV3=>{try{const next=addressEntityV3(score,targetId(address));if(next.kind!==address.kind)throw new Error('kind changed');return next;}catch(error){throw new BasicAuthoringV4Error('Authoring result would orphan current notation.','NOTATION_ORPHAN_RISK',{targetKind:address.kind,targetId:targetId(address),cause:error instanceof Error?error.message:String(error)});}};
const rebindNotation=(score:ScoreDocumentV3,notation:NotationDocumentV4):Readonly<NotationDocumentV4>=>createNotationDocumentV4(score,{contractVersion:'4.0.0',documentId:score.id,revisionId:score.revision.id,frames:notation.frames.map(entry=>({target:rebindAddress(score,entry.target)as typeof entry.target,notation:entry.notation})),measures:notation.measures.map(entry=>({target:rebindAddress(score,entry.target)as typeof entry.target,notation:entry.notation})),events:notation.events.map(entry=>({target:rebindAddress(score,entry.target)as typeof entry.target,notation:entry.notation})),notes:notation.notes.map(entry=>({target:rebindAddress(score,entry.target)as typeof entry.target,notation:entry.notation})),graceEvents:notation.graceEvents.map(entry=>({target:rebindAddress(score,entry.target)as typeof entry.target,notation:entry.notation})),graceNotes:notation.graceNotes.map(entry=>({target:rebindAddress(score,entry.target)as typeof entry.target,notation:entry.notation})),crossStaffPlacements:notation.crossStaffPlacements.map(item=>({source:rebindAddress(score,item.source)as EventAddressV3,displayStaffId:item.displayStaffId}))});
const mutateEvent=(score:ScoreDocumentV3,address:EventAddressV3,replace:(event:ScoreEvent)=>ScoreEvent,nextRevisionId:string):Readonly<ScoreDocumentV3>=>{const candidate=structuredClone(score)as ScoreDocumentV3;const part=candidate.parts.find(item=>item.id===address.partId);const staff=part?.staves.find(item=>item.id===address.staffId);if(!part||!staff||staff.role==='tablature-linked')throw new BasicAuthoringV4Error('Event target path is invalid.','TARGET_KIND_MISMATCH');const measure=staff.measures.find(item=>item.id===address.measureId);const voice=measure?.voices.find(item=>item.id===address.voiceId);if(!measure||!voice)throw new BasicAuthoringV4Error('Event target path is invalid.','TARGET_KIND_MISMATCH');const index=voice.events.findIndex(item=>item.id===address.eventId);if(index<0)throw new BasicAuthoringV4Error('Event target path is invalid.','TARGET_KIND_MISMATCH');const events=[...voice.events];events[index]=replace(events[index]as ScoreEvent);(voice as{events:readonly ScoreEvent[]}).events=events;(candidate as{revision:{id:string;parentId:string|null}}).revision={id:parseId(nextRevisionId,'nextRevisionId'),parentId:score.revision.id};try{return createScoreDocumentV3(candidate);}catch(error){throw new BasicAuthoringV4Error('Basic authoring result failed canonical score validation.','RESULT_INVALID',{cause:error instanceof Error?error.message:String(error)});}};
const noteNotationExists=(notation:NotationDocumentV4,noteIds:readonly string[]):boolean=>notation.notes.some(entry=>noteIds.includes(entry.target.noteId));
const crossStaffExists=(notation:NotationDocumentV4,eventId:string):boolean=>notation.crossStaffPlacements.some(item=>item.source.eventId===eventId);

export const executeBasicAuthoringV4=(scoreInput:ScoreDocumentV3,notationInput:NotationDocumentV4,rawIntent:unknown,options:BasicAuthoringV4Options):Readonly<BasicAuthoringV4Result>=>{
  const score=createScoreDocumentV3(scoreInput),notation=createNotationDocumentV4(score,notationInput),intent=parseIntent(rawIntent);let nextScore:Readonly<ScoreDocumentV3>;let selectionId:string;
  if(intent.type==='SET_NOTE_PITCH'){resolveCurrent(score,intent.target,'note');const eventTarget=eventAddressForNote(intent.target);eventAt(score,eventTarget);nextScore=mutateEvent(score,eventTarget,event=>event.kind==='note'?{...event,note:{...event.note,pitch:intent.pitch}}:event.kind==='chord'?{...event,notes:event.notes.map(note=>note.id===intent.target.noteId?{...note,pitch:intent.pitch}:note)}:(()=>{throw new BasicAuthoringV4Error('Rest has no note pitch.','EVENT_KIND_MISMATCH');})(),options.nextRevisionId);selectionId=intent.target.noteId;}
  else if(intent.type==='SET_EVENT_DURATION'){const event=eventAt(score,intent.target);nextScore=mutateEvent(score,intent.target,current=>({...current,duration:intent.duration}),options.nextRevisionId);selectionId=event.id;}
  else if(intent.type==='REPLACE_REST_WITH_NOTE'){const event=eventAt(score,intent.target);if(event.kind!=='rest')throw new BasicAuthoringV4Error('Target event is not a rest.','EVENT_KIND_MISMATCH');ensureFreshId(score,intent.noteId);nextScore=mutateEvent(score,intent.target,current=>({id:current.id,kind:'note',onset:current.onset,duration:current.duration,note:{id:intent.noteId,pitch:intent.pitch}}),options.nextRevisionId);selectionId=intent.noteId;}
  else if(intent.type==='REPLACE_PITCHED_EVENT_WITH_REST'){const event=eventAt(score,intent.target);if(event.kind==='rest')throw new BasicAuthoringV4Error('Target event is already a rest.','EVENT_KIND_MISMATCH');const removed=event.kind==='note'?[event.note.id]:event.notes.map(note=>note.id);if(noteNotationExists(notation,removed))throw new BasicAuthoringV4Error('Replacing this event with a rest would orphan note notation.','NOTATION_ORPHAN_RISK',{noteIds:removed});if(crossStaffExists(notation,event.id))throw new BasicAuthoringV4Error('Cross-staff placement must be explicitly removed before converting its source event to a rest.','CROSS_STAFF_CONFLICT',{eventId:event.id});nextScore=mutateEvent(score,intent.target,current=>({id:current.id,kind:'rest',onset:current.onset,duration:current.duration}),options.nextRevisionId);selectionId=event.id;}
  else if(intent.type==='ADD_CHORD_TONE'){const event=eventAt(score,intent.target);if(event.kind==='rest')throw new BasicAuthoringV4Error('Cannot add a chord tone to a rest.','EVENT_KIND_MISMATCH');ensureFreshId(score,intent.noteId);nextScore=mutateEvent(score,intent.target,current=>current.kind==='note'?{id:current.id,kind:'chord',onset:current.onset,duration:current.duration,notes:[current.note,{id:intent.noteId,pitch:intent.pitch}]}:current.kind==='chord'?{...current,notes:[...current.notes,{id:intent.noteId,pitch:intent.pitch}]}:current,options.nextRevisionId);selectionId=intent.noteId;}
  else{const note=resolveCurrent(score,intent.target,'note').value;const eventTarget=eventAddressForNote(intent.target);const event=eventAt(score,eventTarget);if(event.kind!=='chord')throw new BasicAuthoringV4Error('REMOVE_CHORD_TONE requires a chord event.','EVENT_KIND_MISMATCH');if(noteNotationExists(notation,[note.id]))throw new BasicAuthoringV4Error('Removing this chord tone would orphan note notation.','NOTATION_ORPHAN_RISK',{noteId:note.id});const remaining=event.notes.filter(item=>item.id!==note.id);if(remaining.length===0)throw new BasicAuthoringV4Error('Cannot implicitly turn an empty chord into a rest.','EVENT_KIND_MISMATCH');nextScore=mutateEvent(score,eventTarget,current=>{if(current.kind!=='chord')return current;const left=current.notes.filter(item=>item.id!==intent.target.noteId);return left.length===1?{id:current.id,kind:'note',onset:current.onset,duration:current.duration,note:left[0]!}:{...current,notes:left};},options.nextRevisionId);selectionId=remaining[0]!.id;}
  let nextNotation:Readonly<NotationDocumentV4>;try{nextNotation=rebindNotation(nextScore,notation);}catch(error){if(error instanceof BasicAuthoringV4Error)throw error;throw new BasicAuthoringV4Error('Basic authoring result failed notation validation.','RESULT_INVALID',{cause:error instanceof Error?error.message:String(error)});}const selection=addressEntityV3(nextScore,selectionId);return Object.freeze({score:nextScore,notation:nextNotation,selection});
};
