import { createScoreDocumentV3, type ContentStaffV3, type MeasureFrameV3, type PartV3, type ScoreDocumentV3, type StaffMeasureV3, type StaffV3 } from '../../score-model-v3/src/index.js';
import type { GraceEvent, GraceGroup, NoteAtom, VoiceV2 } from '../../score-model-v2/src/index.js';
import type { ScoreEvent } from '../../score-model/src/index.js';

export const SEMANTIC_ADDRESS_V3_VERSION='3.0.0' as const;
export type AddressKindV3='document'|'measure-frame'|'part'|'staff'|'measure'|'voice'|'event'|'note'|'grace-group'|'grace-event'|'grace-note';
interface Base { readonly contractVersion:typeof SEMANTIC_ADDRESS_V3_VERSION; readonly kind:AddressKindV3; readonly documentId:string; readonly revisionId:string }
export interface DocumentAddressV3 extends Base { readonly kind:'document' }
export interface MeasureFrameAddressV3 extends Base { readonly kind:'measure-frame'; readonly frameId:string }
export interface PartAddressV3 extends Base { readonly kind:'part'; readonly partId:string }
export interface StaffAddressV3 extends Base { readonly kind:'staff'; readonly partId:string; readonly staffId:string }
export interface MeasureAddressV3 extends Base { readonly kind:'measure'; readonly partId:string; readonly staffId:string; readonly frameId:string; readonly measureId:string }
export interface VoiceAddressV3 extends Base { readonly kind:'voice'; readonly partId:string; readonly staffId:string; readonly frameId:string; readonly measureId:string; readonly voiceId:string }
export interface EventAddressV3 extends Base { readonly kind:'event'; readonly partId:string; readonly staffId:string; readonly frameId:string; readonly measureId:string; readonly voiceId:string; readonly eventId:string }
export interface NoteAddressV3 extends Base { readonly kind:'note'; readonly partId:string; readonly staffId:string; readonly frameId:string; readonly measureId:string; readonly voiceId:string; readonly eventId:string; readonly noteId:string }
export interface GraceGroupAddressV3 extends Base { readonly kind:'grace-group'; readonly partId:string; readonly staffId:string; readonly frameId:string; readonly measureId:string; readonly voiceId:string; readonly graceGroupId:string }
export interface GraceEventAddressV3 extends Base { readonly kind:'grace-event'; readonly partId:string; readonly staffId:string; readonly frameId:string; readonly measureId:string; readonly voiceId:string; readonly graceGroupId:string; readonly graceEventId:string }
export interface GraceNoteAddressV3 extends Base { readonly kind:'grace-note'; readonly partId:string; readonly staffId:string; readonly frameId:string; readonly measureId:string; readonly voiceId:string; readonly graceGroupId:string; readonly graceEventId:string; readonly graceNoteId:string }
export type SemanticAddressV3=DocumentAddressV3|MeasureFrameAddressV3|PartAddressV3|StaffAddressV3|MeasureAddressV3|VoiceAddressV3|EventAddressV3|NoteAddressV3|GraceGroupAddressV3|GraceEventAddressV3|GraceNoteAddressV3;
export type ResolvedSemanticTargetV3={readonly kind:'document';readonly value:ScoreDocumentV3}|{readonly kind:'measure-frame';readonly value:MeasureFrameV3}|{readonly kind:'part';readonly value:PartV3}|{readonly kind:'staff';readonly value:StaffV3}|{readonly kind:'measure';readonly value:StaffMeasureV3}|{readonly kind:'voice';readonly value:VoiceV2}|{readonly kind:'event';readonly value:ScoreEvent}|{readonly kind:'note';readonly value:NoteAtom}|{readonly kind:'grace-group';readonly value:GraceGroup}|{readonly kind:'grace-event';readonly value:GraceEvent}|{readonly kind:'grace-note';readonly value:NoteAtom};
export type AddressingV3ErrorCode='INVALID_ADDRESS'|'DOCUMENT_MISMATCH'|'STALE_REVISION'|'TARGET_NOT_FOUND'|'ADDRESS_PATH_MISMATCH'|'NON_CONTENT_STAFF';
export class AddressingV3Error extends Error { readonly code:AddressingV3ErrorCode; readonly details:Readonly<Record<string,unknown>>; constructor(message:string,code:AddressingV3ErrorCode,details:Record<string,unknown>={}){super(message);this.name='AddressingV3Error';this.code=code;this.details=Object.freeze({...details});Object.freeze(this);} }
const fields:Record<AddressKindV3,readonly string[]>={document:['contractVersion','kind','documentId','revisionId'],'measure-frame':['contractVersion','kind','documentId','revisionId','frameId'],part:['contractVersion','kind','documentId','revisionId','partId'],staff:['contractVersion','kind','documentId','revisionId','partId','staffId'],measure:['contractVersion','kind','documentId','revisionId','partId','staffId','frameId','measureId'],voice:['contractVersion','kind','documentId','revisionId','partId','staffId','frameId','measureId','voiceId'],event:['contractVersion','kind','documentId','revisionId','partId','staffId','frameId','measureId','voiceId','eventId'],note:['contractVersion','kind','documentId','revisionId','partId','staffId','frameId','measureId','voiceId','eventId','noteId'],'grace-group':['contractVersion','kind','documentId','revisionId','partId','staffId','frameId','measureId','voiceId','graceGroupId'],'grace-event':['contractVersion','kind','documentId','revisionId','partId','staffId','frameId','measureId','voiceId','graceGroupId','graceEventId'],'grace-note':['contractVersion','kind','documentId','revisionId','partId','staffId','frameId','measureId','voiceId','graceGroupId','graceEventId','graceNoteId']};
const rec=(v:unknown):v is Record<string,unknown>=>v!==null&&typeof v==='object'&&!Array.isArray(v);
const validateEnvelope=(doc:ScoreDocumentV3,a:SemanticAddressV3)=>{if(!rec(a)||typeof a.kind!=='string'||!(a.kind in fields))throw new AddressingV3Error('Unsupported v3 semantic address.','INVALID_ADDRESS');if(JSON.stringify(Object.keys(a).sort())!==JSON.stringify([...fields[a.kind]].sort()))throw new AddressingV3Error('V3 semantic address field set is invalid.','INVALID_ADDRESS');if(a.contractVersion!==SEMANTIC_ADDRESS_V3_VERSION)throw new AddressingV3Error('Unsupported address version.','INVALID_ADDRESS');if(a.documentId!==doc.id)throw new AddressingV3Error('Address belongs to another document.','DOCUMENT_MISMATCH');if(a.revisionId!==doc.revision.id)throw new AddressingV3Error('Address belongs to stale revision.','STALE_REVISION');};
const child=<T extends {readonly id:string}>(items:readonly T[],target:string,label:string):T=>{const found=items.find(item=>item.id===target);if(!found)throw new AddressingV3Error(`${label} does not resolve in addressed parent.`,'ADDRESS_PATH_MISMATCH',{target});return found;};
const content=(staff:StaffV3):ContentStaffV3=>{if(staff.role==='tablature-linked')throw new AddressingV3Error('Linked TAB staff owns no canonical measure descendants.','NON_CONTENT_STAFF',{staffId:staff.id});return staff;};
const normalNotes=(event:ScoreEvent):readonly NoteAtom[]=>event.kind==='note'?[event.note]:event.kind==='chord'?event.notes:[];
const graceNotes=(event:GraceEvent):readonly NoteAtom[]=>event.kind==='note'?[event.note]:event.kind==='chord'?event.notes:[];
export const resolveSemanticAddressV3=(input:ScoreDocumentV3,address:SemanticAddressV3):ResolvedSemanticTargetV3=>{const doc=createScoreDocumentV3(input);validateEnvelope(doc,address);if(address.kind==='document')return {kind:'document',value:doc};if(address.kind==='measure-frame')return {kind:'measure-frame',value:child(doc.measureFrames,address.frameId,'measure-frame')};const part=child(doc.parts,address.partId,'part');if(address.kind==='part')return {kind:'part',value:part};const staff=child(part.staves,address.staffId,'staff');if(address.kind==='staff')return {kind:'staff',value:staff};const c=content(staff);const measure=child(c.measures,address.measureId,'measure');if(measure.frameId!==address.frameId)throw new AddressingV3Error('Address frame does not match staff measure frame.','ADDRESS_PATH_MISMATCH');if(address.kind==='measure')return {kind:'measure',value:measure};const voice=child(measure.voices,address.voiceId,'voice');if(address.kind==='voice')return {kind:'voice',value:voice};if(address.kind==='event'||address.kind==='note'){const event=child(voice.events,address.eventId,'event');if(address.kind==='event')return {kind:'event',value:event};return {kind:'note',value:child(normalNotes(event),address.noteId,'note')};}const group=child(voice.graceGroups,address.graceGroupId,'grace-group');if(address.kind==='grace-group')return {kind:'grace-group',value:group};const ge=child(group.events,address.graceEventId,'grace-event');if(address.kind==='grace-event')return {kind:'grace-event',value:ge};return {kind:'grace-note',value:child(graceNotes(ge),address.graceNoteId,'grace-note')};};
const common=(doc:ScoreDocumentV3,kind:AddressKindV3)=>({contractVersion:SEMANTIC_ADDRESS_V3_VERSION,kind,documentId:doc.id,revisionId:doc.revision.id});
export interface SemanticAddressIndexV3 { readonly document:DocumentAddressV3; readonly byEntityId:ReadonlyMap<string,SemanticAddressV3> }
export const createSemanticAddressIndexV3=(input:ScoreDocumentV3):SemanticAddressIndexV3=>{const doc=createScoreDocumentV3(input);const root=Object.freeze({...common(doc,'document'),kind:'document'} as DocumentAddressV3);const map=new Map<string,SemanticAddressV3>([[doc.id,root]]);const add=(id:string,a:SemanticAddressV3)=>{if(map.has(id))throw new AddressingV3Error('Duplicate v3 identity prevents deterministic addressing.','INVALID_ADDRESS',{id});map.set(id,Object.freeze(a));};for(const frame of doc.measureFrames)add(frame.id,{...common(doc,'measure-frame'),kind:'measure-frame',frameId:frame.id});for(const part of doc.parts){add(part.id,{...common(doc,'part'),kind:'part',partId:part.id});add(part.instrument.id,{...common(doc,'part'),kind:'part',partId:part.id});for(const staff of part.staves){add(staff.id,{...common(doc,'staff'),kind:'staff',partId:part.id,staffId:staff.id});if(staff.role==='tablature-linked')continue;for(const measure of staff.measures){add(measure.id,{...common(doc,'measure'),kind:'measure',partId:part.id,staffId:staff.id,frameId:measure.frameId,measureId:measure.id});for(const voice of measure.voices){add(voice.id,{...common(doc,'voice'),kind:'voice',partId:part.id,staffId:staff.id,frameId:measure.frameId,measureId:measure.id,voiceId:voice.id});for(const event of voice.events){add(event.id,{...common(doc,'event'),kind:'event',partId:part.id,staffId:staff.id,frameId:measure.frameId,measureId:measure.id,voiceId:voice.id,eventId:event.id});for(const note of normalNotes(event))add(note.id,{...common(doc,'note'),kind:'note',partId:part.id,staffId:staff.id,frameId:measure.frameId,measureId:measure.id,voiceId:voice.id,eventId:event.id,noteId:note.id});}for(const group of voice.graceGroups){add(group.id,{...common(doc,'grace-group'),kind:'grace-group',partId:part.id,staffId:staff.id,frameId:measure.frameId,measureId:measure.id,voiceId:voice.id,graceGroupId:group.id});for(const ge of group.events){add(ge.id,{...common(doc,'grace-event'),kind:'grace-event',partId:part.id,staffId:staff.id,frameId:measure.frameId,measureId:measure.id,voiceId:voice.id,graceGroupId:group.id,graceEventId:ge.id});for(const note of graceNotes(ge))add(note.id,{...common(doc,'grace-note'),kind:'grace-note',partId:part.id,staffId:staff.id,frameId:measure.frameId,measureId:measure.id,voiceId:voice.id,graceGroupId:group.id,graceEventId:ge.id,graceNoteId:note.id});}}}}}}return Object.freeze({document:root,byEntityId:map});};
export const addressEntityV3=(doc:ScoreDocumentV3,entityId:string):SemanticAddressV3=>{const a=createSemanticAddressIndexV3(doc).byEntityId.get(entityId);if(!a)throw new AddressingV3Error('Entity target not found.','TARGET_NOT_FOUND',{entityId});return a;};
