import type { AccidentalDisplay, BarlineSpec, BeamSpec, BoundaryMark, ClefSpec, KeySignature, MeasureNotation, NoteNotation, TimeSignature, TupletSpec } from '../../notation-structure/src/index.js';
import { resolveSemanticAddressV2, type EventAddressV2, type GraceEventAddressV2, type GraceNoteAddressV2, type MeasureAddressV2, type NoteAddressV2 } from '../../addressing-v2/src/index.js';
import { createScoreDocumentV2, type ScoreDocumentV2 } from '../../score-model-v2/src/index.js';

export const NOTATION_DOCUMENT_V2_VERSION='2.0.0' as const;
export type PlacementV2='auto'|'above'|'below';
export type ArticulationKind='accent'|'strong-accent'|'staccato'|'tenuto'|'detached-legato'|'staccatissimo'|'spiccato'|'scoop'|'plop'|'doit'|'falloff'|'breath-mark'|'caesura'|'stress'|'unstress'|'soft-accent';
export interface ArticulationSpec { readonly kind:ArticulationKind; readonly placement:PlacementV2; readonly direction:'up'|'down'|null }
export type SimpleOrnamentKind='trill-mark'|'turn'|'delayed-turn'|'inverted-turn'|'delayed-inverted-turn'|'vertical-turn'|'inverted-vertical-turn'|'shake'|'mordent'|'inverted-mordent'|'schleifer'|'haydn';
export interface OrnamentAccidentalMark { readonly accidental:AccidentalDisplay; readonly placement:PlacementV2 }
export interface SimpleOrnamentSpec { readonly kind:SimpleOrnamentKind; readonly placement:PlacementV2; readonly accidentalMarks:readonly OrnamentAccidentalMark[] }
export interface TremoloOrnamentSpec { readonly kind:'tremolo'; readonly type:'single'|'start'|'stop'; readonly marks:number; readonly number:number|null; readonly placement:PlacementV2 }
export interface WavyLineOrnamentSpec { readonly kind:'wavy-line'; readonly type:'start'|'continue'|'stop'; readonly number:number; readonly placement:PlacementV2 }
export type OrnamentSpec=SimpleOrnamentSpec|TremoloOrnamentSpec|WavyLineOrnamentSpec;
export interface EventNotationV2 { readonly dots:number; readonly beams:readonly BeamSpec[]; readonly tuplet:TupletSpec|null; readonly articulations:readonly ArticulationSpec[]; readonly ornaments:readonly OrnamentSpec[] }
export interface GraceEventNotationV2 { readonly slash:boolean; readonly dots:number; readonly beams:readonly BeamSpec[]; readonly articulations:readonly ArticulationSpec[]; readonly ornaments:readonly OrnamentSpec[] }
export interface GraceNoteNotationV2 { readonly accidental:AccidentalDisplay|null; readonly ties:readonly BoundaryMark[]; readonly slurs:readonly BoundaryMark[] }
export interface MeasureNotationEntryV2 { readonly target:MeasureAddressV2; readonly notation:MeasureNotation }
export interface EventNotationEntryV2 { readonly target:EventAddressV2; readonly notation:EventNotationV2 }
export interface NoteNotationEntryV2 { readonly target:NoteAddressV2; readonly notation:NoteNotation }
export interface GraceEventNotationEntryV2 { readonly target:GraceEventAddressV2; readonly notation:GraceEventNotationV2 }
export interface GraceNoteNotationEntryV2 { readonly target:GraceNoteAddressV2; readonly notation:GraceNoteNotationV2 }
export interface NotationDocumentV2 { readonly contractVersion:typeof NOTATION_DOCUMENT_V2_VERSION; readonly documentId:string; readonly revisionId:string; readonly measures:readonly MeasureNotationEntryV2[]; readonly events:readonly EventNotationEntryV2[]; readonly notes:readonly NoteNotationEntryV2[]; readonly graceEvents:readonly GraceEventNotationEntryV2[]; readonly graceNotes:readonly GraceNoteNotationEntryV2[] }
export type NotationV2ErrorCode='INVALID_NOTATION'|'DUPLICATE_TARGET'|'STALE_NOTATION'|'TARGET_KIND_MISMATCH'|'BROKEN_ORNAMENT_RELATION';
export class NotationV2Error extends Error { readonly code:NotationV2ErrorCode; readonly details:Readonly<Record<string,unknown>>; constructor(message:string,code:NotationV2ErrorCode,details:Record<string,unknown>={}){super(message);this.name='NotationV2Error';this.code=code;this.details=Object.freeze({...details});Object.freeze(this);} }

const rec=(v:unknown):v is Record<string,unknown>=>v!==null&&typeof v==='object'&&!Array.isArray(v);
const exact=(v:unknown,keys:readonly string[],label:string):Record<string,unknown>=>{if(!rec(v)||JSON.stringify(Object.keys(v).sort())!==JSON.stringify([...keys].sort()))throw new NotationV2Error(`${label} field set is invalid.`,'INVALID_NOTATION');return v;};
const integer=(v:unknown,min:number,max:number,label:string):number=>{if(typeof v!=='number'||!Number.isSafeInteger(v)||v<min||v>max)throw new NotationV2Error(`${label} is outside admitted range.`,'INVALID_NOTATION',{v,min,max});return v;};
const enumValue=<T extends string>(v:unknown,allowed:readonly T[],label:string):T=>{if(typeof v!=='string'||!allowed.includes(v as T))throw new NotationV2Error(`${label} is unsupported.`,'INVALID_NOTATION',{v});return v as T;};
const placement=(v:unknown,label:string):PlacementV2=>enumValue(v,['auto','above','below'] as const,label);
const accidental=(v:unknown,label:string):AccidentalDisplay=>enumValue(v,['sharp','flat','natural','double-sharp','double-flat'] as const,label);
const boundaries=(v:unknown,label:string):readonly BoundaryMark[]=>{if(!Array.isArray(v))throw new NotationV2Error(`${label} must be an array.`,'INVALID_NOTATION');const seen=new Set<string>();return Object.freeze(v.map((raw,i)=>{const x=exact(raw,['number','type'],`${label}[${i}]`);const number=integer(x.number,1,16,`${label}[${i}].number`);const type=enumValue(x.type,['start','stop'] as const,`${label}[${i}].type`);const key=`${number}:${type}`;if(seen.has(key))throw new NotationV2Error(`${label} duplicate boundary mark.`,'INVALID_NOTATION',{key});seen.add(key);return Object.freeze({number,type});}));};
const beams=(v:unknown,label:string):readonly BeamSpec[]=>{if(!Array.isArray(v)||v.length>8)throw new NotationV2Error(`${label} must contain at most 8 beams.`,'INVALID_NOTATION');const seen=new Set<number>();return Object.freeze(v.map((raw,i)=>{const x=exact(raw,['number','value'],`${label}[${i}]`);const number=integer(x.number,1,8,`${label}[${i}].number`);if(seen.has(number))throw new NotationV2Error(`${label} duplicate beam number.`,'INVALID_NOTATION');seen.add(number);return Object.freeze({number,value:enumValue(x.value,['begin','continue','end','forward-hook','backward-hook'] as const,`${label}[${i}].value`)});}));};
const tuplet=(v:unknown):TupletSpec|null=>{if(v===null)return null;const x=exact(v,['actualNotes','normalNotes','marks'],'TupletSpec');return Object.freeze({actualNotes:integer(x.actualNotes,1,32,'TupletSpec.actualNotes'),normalNotes:integer(x.normalNotes,1,32,'TupletSpec.normalNotes'),marks:boundaries(x.marks,'TupletSpec.marks')});};
const measureNotation=(v:unknown):MeasureNotation=>{const x=exact(v,['timeSignature','keySignature','clef','barlines'],'MeasureNotation');let timeSignature:TimeSignature|null=null;if(x.timeSignature!==null){const t=exact(x.timeSignature,['beats','beatType'],'TimeSignature');const beats=integer(t.beats,1,32,'TimeSignature.beats'),beatType=integer(t.beatType,1,64,'TimeSignature.beatType');if(![1,2,4,8,16,32,64].includes(beatType))throw new NotationV2Error('Unsupported beat type.','INVALID_NOTATION');timeSignature=Object.freeze({beats,beatType});}let keySignature:KeySignature|null=null;if(x.keySignature!==null){const k=exact(x.keySignature,['fifths'],'KeySignature');keySignature=Object.freeze({fifths:integer(k.fifths,-7,7,'KeySignature.fifths')});}let clef:ClefSpec|null=null;if(x.clef!==null){const c=exact(x.clef,['sign','line','octaveChange'],'ClefSpec');clef=Object.freeze({sign:enumValue(c.sign,['G','F','C','percussion','TAB'] as const,'ClefSpec.sign'),line:integer(c.line,1,5,'ClefSpec.line'),octaveChange:integer(c.octaveChange,-2,2,'ClefSpec.octaveChange')});}if(!Array.isArray(x.barlines)||x.barlines.length>2)throw new NotationV2Error('barlines must contain at most left/right.','INVALID_NOTATION');const seen=new Set<string>();const barlines=Object.freeze(x.barlines.map((raw,i)=>{const b=exact(raw,['location','style','repeat'],`barlines[${i}]`);const location=enumValue(b.location,['left','right'] as const,'Barline.location');if(seen.has(location))throw new NotationV2Error('duplicate barline location.','INVALID_NOTATION');seen.add(location);const style=enumValue(b.style,['regular','light-light','light-heavy','heavy-light','heavy-heavy','dashed','dotted','none'] as const,'Barline.style');const repeat=b.repeat===null?null:enumValue(b.repeat,['forward','backward'] as const,'Barline.repeat');return Object.freeze({location,style,repeat});}));return Object.freeze({timeSignature,keySignature,clef,barlines});};
const noteNotation=(v:unknown):NoteNotation=>{const x=exact(v,['accidental','ties','slurs'],'NoteNotation');return Object.freeze({accidental:x.accidental===null?null:accidental(x.accidental,'NoteNotation.accidental'),ties:boundaries(x.ties,'NoteNotation.ties'),slurs:boundaries(x.slurs,'NoteNotation.slurs')});};
const articulation=(v:unknown,label:string):ArticulationSpec=>{const x=exact(v,['kind','placement','direction'],label);const kind=enumValue(x.kind,['accent','strong-accent','staccato','tenuto','detached-legato','staccatissimo','spiccato','scoop','plop','doit','falloff','breath-mark','caesura','stress','unstress','soft-accent'] as const,`${label}.kind`);const direction=x.direction===null?null:enumValue(x.direction,['up','down'] as const,`${label}.direction`);if(kind!=='strong-accent'&&direction!==null)throw new NotationV2Error('direction is admitted only for strong-accent.','INVALID_NOTATION',{kind});return Object.freeze({kind,placement:placement(x.placement,`${label}.placement`),direction});};
const articulations=(v:unknown,label:string):readonly ArticulationSpec[]=>{if(!Array.isArray(v))throw new NotationV2Error(`${label} must be array.`,'INVALID_NOTATION');const seen=new Set<string>();return Object.freeze(v.map((raw,i)=>{const a=articulation(raw,`${label}[${i}]`);const key=JSON.stringify(a);if(seen.has(key))throw new NotationV2Error('duplicate articulation.','INVALID_NOTATION',{key});seen.add(key);return a;}));};
const ornament=(v:unknown,label:string):OrnamentSpec=>{if(!rec(v)||typeof v.kind!=='string')throw new NotationV2Error(`${label} is invalid.`,'INVALID_NOTATION');if(v.kind==='tremolo'){const x=exact(v,['kind','type','marks','number','placement'],label);const type=enumValue(x.type,['single','start','stop'] as const,`${label}.type`);const number=x.number===null?null:integer(x.number,1,16,`${label}.number`);if(type==='single'&&number!==null)throw new NotationV2Error('single tremolo must not have relation number.','INVALID_NOTATION');if(type!=='single'&&number===null)throw new NotationV2Error('spanning tremolo requires relation number.','INVALID_NOTATION');return Object.freeze({kind:'tremolo',type,marks:integer(x.marks,1,8,`${label}.marks`),number,placement:placement(x.placement,`${label}.placement`)});}if(v.kind==='wavy-line'){const x=exact(v,['kind','type','number','placement'],label);return Object.freeze({kind:'wavy-line',type:enumValue(x.type,['start','continue','stop'] as const,`${label}.type`),number:integer(x.number,1,16,`${label}.number`),placement:placement(x.placement,`${label}.placement`)});}const x=exact(v,['kind','placement','accidentalMarks'],label);const kind=enumValue(x.kind,['trill-mark','turn','delayed-turn','inverted-turn','delayed-inverted-turn','vertical-turn','inverted-vertical-turn','shake','mordent','inverted-mordent','schleifer','haydn'] as const,`${label}.kind`);if(!Array.isArray(x.accidentalMarks))throw new NotationV2Error('accidentalMarks must be array.','INVALID_NOTATION');const accidentalMarks=Object.freeze(x.accidentalMarks.map((raw,i)=>{const m=exact(raw,['accidental','placement'],`${label}.accidentalMarks[${i}]`);return Object.freeze({accidental:accidental(m.accidental,'OrnamentAccidentalMark.accidental'),placement:placement(m.placement,'OrnamentAccidentalMark.placement')});}));return Object.freeze({kind,placement:placement(x.placement,`${label}.placement`),accidentalMarks});};
const ornaments=(v:unknown,label:string):readonly OrnamentSpec[]=>{if(!Array.isArray(v))throw new NotationV2Error(`${label} must be array.`,'INVALID_NOTATION');const seen=new Set<string>();return Object.freeze(v.map((raw,i)=>{const o=ornament(raw,`${label}[${i}]`);const key=JSON.stringify(o);if(seen.has(key))throw new NotationV2Error('duplicate ornament.','INVALID_NOTATION',{key});seen.add(key);return o;}));};
const eventNotation=(v:unknown):EventNotationV2=>{const x=exact(v,['dots','beams','tuplet','articulations','ornaments'],'EventNotationV2');return Object.freeze({dots:integer(x.dots,0,3,'EventNotationV2.dots'),beams:beams(x.beams,'EventNotationV2.beams'),tuplet:tuplet(x.tuplet),articulations:articulations(x.articulations,'EventNotationV2.articulations'),ornaments:ornaments(x.ornaments,'EventNotationV2.ornaments')});};
const graceEventNotation=(v:unknown):GraceEventNotationV2=>{const x=exact(v,['slash','dots','beams','articulations','ornaments'],'GraceEventNotationV2');if(typeof x.slash!=='boolean')throw new NotationV2Error('slash must be boolean.','INVALID_NOTATION');return Object.freeze({slash:x.slash,dots:integer(x.dots,0,3,'GraceEventNotationV2.dots'),beams:beams(x.beams,'GraceEventNotationV2.beams'),articulations:articulations(x.articulations,'GraceEventNotationV2.articulations'),ornaments:ornaments(x.ornaments,'GraceEventNotationV2.ornaments')});};

export interface NotationDocumentV2Input extends NotationDocumentV2 {}
const targetId=(kind:string,target:MeasureAddressV2|EventAddressV2|NoteAddressV2|GraceEventAddressV2|GraceNoteAddressV2):string=>kind==='measure'?(target as MeasureAddressV2).measureId:kind==='event'?(target as EventAddressV2).eventId:kind==='note'?(target as NoteAddressV2).noteId:kind==='grace-event'?(target as GraceEventAddressV2).graceEventId:(target as GraceNoteAddressV2).graceNoteId;
const relationFacts=(document:NotationDocumentV2):void=>{const facts=new Map<string,{start:number;stop:number;continues:number}>();const consume=(list:readonly OrnamentSpec[])=>{for(const o of list){if(o.kind==='tremolo'&&o.type!=='single'){const key=`tremolo:${o.number}`;const f=facts.get(key)??{start:0,stop:0,continues:0};if(o.type==='start')f.start++;else f.stop++;facts.set(key,f);}if(o.kind==='wavy-line'){const key=`wavy-line:${o.number}`;const f=facts.get(key)??{start:0,stop:0,continues:0};if(o.type==='start')f.start++;else if(o.type==='stop')f.stop++;else f.continues++;facts.set(key,f);}}};document.events.forEach(e=>consume(e.notation.ornaments));document.graceEvents.forEach(e=>consume(e.notation.ornaments));for(const [key,f] of facts){if(f.start!==1||f.stop!==1)throw new NotationV2Error('ornament relation must contain exactly one start and one stop.','BROKEN_ORNAMENT_RELATION',{key,...f});}};
export const createNotationDocumentV2=(scoreInput:ScoreDocumentV2,input:NotationDocumentV2Input):Readonly<NotationDocumentV2>=>{const score=createScoreDocumentV2(scoreInput);exact(input,['contractVersion','documentId','revisionId','measures','events','notes','graceEvents','graceNotes'],'NotationDocumentV2');if(input.contractVersion!==NOTATION_DOCUMENT_V2_VERSION)throw new NotationV2Error('NotationDocumentV2 version unsupported.','INVALID_NOTATION');if(input.documentId!==score.id||input.revisionId!==score.revision.id)throw new NotationV2Error('NotationDocumentV2 belongs to another score revision.','STALE_NOTATION');const validateEntries=<T extends {readonly target:MeasureAddressV2|EventAddressV2|NoteAddressV2|GraceEventAddressV2|GraceNoteAddressV2;readonly notation:unknown}>(raw:readonly T[],kind:'measure'|'event'|'note'|'grace-event'|'grace-note',validator:(v:unknown)=>unknown):readonly T[]=>{if(!Array.isArray(raw))throw new NotationV2Error('notation entries must be arrays.','INVALID_NOTATION');const seen=new Set<string>();return Object.freeze(raw.map((entry)=>{exact(entry,['target','notation'],`${kind} notation entry`);const resolved=resolveSemanticAddressV2(score,entry.target);if(resolved.kind!==kind)throw new NotationV2Error('notation target kind mismatch.','TARGET_KIND_MISMATCH',{expected:kind,observed:resolved.kind});const id=targetId(kind,entry.target);if(seen.has(id))throw new NotationV2Error('duplicate notation target.','DUPLICATE_TARGET',{id});seen.add(id);return Object.freeze({target:Object.freeze({...entry.target}),notation:validator(entry.notation)}) as T;}));};const document=Object.freeze({contractVersion:NOTATION_DOCUMENT_V2_VERSION,documentId:score.id,revisionId:score.revision.id,measures:validateEntries(input.measures,'measure',measureNotation) as readonly MeasureNotationEntryV2[],events:validateEntries(input.events,'event',eventNotation) as readonly EventNotationEntryV2[],notes:validateEntries(input.notes,'note',noteNotation) as readonly NoteNotationEntryV2[],graceEvents:validateEntries(input.graceEvents,'grace-event',graceEventNotation) as readonly GraceEventNotationEntryV2[],graceNotes:validateEntries(input.graceNotes,'grace-note',noteNotation) as readonly GraceNoteNotationEntryV2[]});relationFacts(document);return document;};
export const emptyNotationDocumentV2=(score:ScoreDocumentV2):Readonly<NotationDocumentV2>=>createNotationDocumentV2(score,{contractVersion:NOTATION_DOCUMENT_V2_VERSION,documentId:score.id,revisionId:score.revision.id,measures:[],events:[],notes:[],graceEvents:[],graceNotes:[]});
export const notationForEventV2=(document:NotationDocumentV2,eventId:string):EventNotationV2|null=>document.events.find(e=>e.target.eventId===eventId)?.notation??null;
export const notationForGraceEventV2=(document:NotationDocumentV2,eventId:string):GraceEventNotationV2|null=>document.graceEvents.find(e=>e.target.graceEventId===eventId)?.notation??null;
export type { AccidentalDisplay, BarlineSpec, BeamSpec, BoundaryMark, ClefSpec, KeySignature, MeasureNotation, NoteNotation, TimeSignature, TupletSpec };
