import { createScoreDocumentV2, type ScoreDocumentV2 } from '../../score-model-v2/src/index.js';
import { createNotationDocumentV2, type NotationDocumentV2 } from '../../notation-structure-v2/src/index.js';
import { addressEntityV2 } from '../../addressing-v2/src/index.js';
import { createScoreDocumentV3, type ScoreDocumentV3 } from '../../score-model-v3/src/index.js';
import { addressEntityV3, type EventAddressV3, type GraceEventAddressV3, type GraceNoteAddressV3, type MeasureAddressV3, type NoteAddressV3 } from '../../addressing-v3/src/index.js';
import { createNotationDocumentV3, type MeasureFrameNotationV3, type NotationDocumentV3, type StaffMeasureNotationV3 } from '../../notation-structure-v3/src/index.js';
import type { BarlineSpec, ClefSpec, KeySignature, TimeSignature } from '../../notation-structure/src/index.js';

export const SCHEMA_MIGRATION_V2_V3_VERSION='1.0.0' as const;
export type MigrationV2V3ErrorCode='TOPOLOGY_MISALIGNED'|'NOTATION_OWNERSHIP_CONFLICT'|'DOWNGRADE_UNREPRESENTABLE'|'MIGRATION_INVALID';
export class MigrationV2V3Error extends Error { readonly code:MigrationV2V3ErrorCode; readonly path:string; constructor(message:string,code:MigrationV2V3ErrorCode,path:string){super(message);this.name='MigrationV2V3Error';this.code=code;this.path=path;} }
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
const allIdsV2=(score:ScoreDocumentV2):Set<string>=>{const ids=new Set<string>([score.id,score.revision.id]);for(const p of score.parts){ids.add(p.id);for(const s of p.staves){ids.add(s.id);for(const m of s.measures){ids.add(m.id);for(const v of m.voices){ids.add(v.id);for(const e of v.events){ids.add(e.id);if(e.kind==='note')ids.add(e.note.id);if(e.kind==='chord')e.notes.forEach(n=>ids.add(n.id));}for(const g of v.graceGroups){ids.add(g.id);for(const e of g.events){ids.add(e.id);if(e.kind==='note')ids.add(e.note.id);if(e.kind==='chord')e.notes.forEach(n=>ids.add(n.id));}}}}}}return ids;};
const fresh=(base:string,ids:Set<string>):string=>{const clean=base.slice(0,118);let candidate=clean;let i=1;while(ids.has(candidate))candidate=`${clean.slice(0,112)}:${i++}`;ids.add(candidate);return candidate;};
const frameBase=(index:number)=>`frame:${index+1}`;
const instrumentBase=(partId:string)=>`instrument:${partId}`;
const findMeasureNotation=(notation:NotationDocumentV2,measureId:string)=>notation.measures.find(entry=>entry.target.measureId===measureId)?.notation??{timeSignature:null,keySignature:null,clef:null,barlines:[]};
const chooseShared=<T>(values:readonly T[],empty:(v:T)=>boolean,path:string):T=>{const nonEmpty=values.filter(v=>!empty(v));if(nonEmpty.length===0)return values[0] as T;const first=nonEmpty[0] as T;if(nonEmpty.some(v=>!same(v,first)))throw new MigrationV2V3Error('Aligned staff notation conflicts at frame ownership boundary.','NOTATION_OWNERSHIP_CONFLICT',path);return first;};
export const migrateScoreNotationV2ToV3=(scoreInput:ScoreDocumentV2,notationInput:NotationDocumentV2):Readonly<{score:Readonly<ScoreDocumentV3>;notation:Readonly<NotationDocumentV3>}>=>{const score=createScoreDocumentV2(scoreInput);const notation=createNotationDocumentV2(score,notationInput);const reference=score.parts[0]?.staves[0]?.measures;if(!reference||reference.length===0)throw new MigrationV2V3Error('V2 topology has no reference measure sequence.','TOPOLOGY_MISALIGNED','$.parts');for(const [pi,part] of score.parts.entries())for(const [si,staff] of part.staves.entries()){if(staff.measures.length!==reference.length)throw new MigrationV2V3Error('All v2 staves must have equal measure count for v3 migration.','TOPOLOGY_MISALIGNED',`$.parts[${pi}].staves[${si}].measures`);staff.measures.forEach((m,mi)=>{const r=reference[mi];if(!r||m.ordinal!==r.ordinal||m.displayNumber!==r.displayNumber)throw new MigrationV2V3Error('Measure ordinal/display number alignment is inconsistent.','TOPOLOGY_MISALIGNED',`$.parts[${pi}].staves[${si}].measures[${mi}]`);});}
  const ids=allIdsV2(score);const frames=reference.map((m,i)=>({id:fresh(frameBase(i),ids),ordinal:i+1,displayNumber:m.displayNumber}));const parts=score.parts.map((part,pi)=>({id:part.id,ordinal:pi+1,name:part.name,instrument:{id:fresh(instrumentBase(part.id),ids),name:part.name,shortName:null},staves:part.staves.map((staff,si)=>({id:staff.id,ordinal:si+1,role:'standard' as const,measures:staff.measures.map((m,mi)=>({id:m.id,frameId:(frames[mi] as {id:string}).id,voices:m.voices}))}))}));const v3=createScoreDocumentV3({schemaVersion:'3.0.0',id:score.id,revision:score.revision,source:score.source,measureFrames:frames,parts});
  const frameEntries=[] as NotationDocumentV3['frames'] extends readonly (infer E)[]?E[]:never;for(const [mi,frame] of v3.measureFrames.entries()){const sourceMeasures=score.parts.flatMap(p=>p.staves.map(s=>s.measures[mi])).filter((m):m is NonNullable<typeof m>=>Boolean(m));const sourceNotations=sourceMeasures.map(m=>findMeasureNotation(notation,m.id));const time=chooseShared(sourceNotations.map(n=>n.timeSignature),v=>v===null,`$.measureFrames[${mi}].timeSignature`);const bars=chooseShared(sourceNotations.map(n=>n.barlines),v=>Array.isArray(v)&&v.length===0,`$.measureFrames[${mi}].barlines`);if(time!==null||bars.length>0){const a=addressEntityV3(v3,frame.id);if(a.kind!=='measure-frame')throw new MigrationV2V3Error('Frame address kind mismatch.','MIGRATION_INVALID',`$.measureFrames[${mi}]`);frameEntries.push({target:a,notation:{timeSignature:time,barlines:bars} as MeasureFrameNotationV3});}}
  const measureEntries=[] as NotationDocumentV3['measures'] extends readonly (infer E)[]?E[]:never;for(const part of v3.parts)for(const staff of part.staves){if(staff.role==='tablature-linked')continue;for(const measure of staff.measures){const n=findMeasureNotation(notation,measure.id);if(n.keySignature!==null||n.clef!==null){const a=addressEntityV3(v3,measure.id);if(a.kind!=='measure')throw new MigrationV2V3Error('Measure address kind mismatch.','MIGRATION_INVALID',`measure:${measure.id}`);measureEntries.push({target:a,notation:{keySignature:n.keySignature,clef:n.clef} as StaffMeasureNotationV3});}}}
  const map=(entries:readonly {target:{kind:string};notation:unknown}[],kind:string,idOf:(t:any)=>string)=>entries.map(entry=>{const a=addressEntityV3(v3,idOf(entry.target));if(a.kind!==kind)throw new MigrationV2V3Error('Notation target kind changed during migration.','MIGRATION_INVALID',idOf(entry.target));return {target:a,notation:entry.notation};});
  const v3Notation=createNotationDocumentV3(v3,{contractVersion:'3.0.0',documentId:v3.id,revisionId:v3.revision.id,frames:frameEntries,measures:measureEntries,events:map(notation.events,'event',t=>t.eventId) as any,notes:map(notation.notes,'note',t=>t.noteId) as any,graceEvents:map(notation.graceEvents,'grace-event',t=>t.graceEventId) as any,graceNotes:map(notation.graceNotes,'grace-note',t=>t.graceNoteId) as any});return Object.freeze({score:v3,notation:v3Notation});};

const expectedDeterministicIds=(score:ScoreDocumentV3):{frames:string[];instruments:string[]}=>{const ids=new Set<string>([score.id,score.revision.id]);for(const p of score.parts){ids.add(p.id);for(const s of p.staves){ids.add(s.id);if(s.role!=='tablature-linked')for(const m of s.measures){ids.add(m.id);for(const v of m.voices){ids.add(v.id);for(const e of v.events){ids.add(e.id);if(e.kind==='note')ids.add(e.note.id);if(e.kind==='chord')e.notes.forEach(n=>ids.add(n.id));}for(const g of v.graceGroups){ids.add(g.id);for(const e of g.events){ids.add(e.id);if(e.kind==='note')ids.add(e.note.id);if(e.kind==='chord')e.notes.forEach(n=>ids.add(n.id));}}}}}}const frames=score.measureFrames.map((_,i)=>fresh(frameBase(i),ids));const instruments=score.parts.map(p=>fresh(instrumentBase(p.id),ids));return {frames,instruments};};
export const downgradeScoreNotationV3ToV2=(scoreInput:ScoreDocumentV3,notationInput:NotationDocumentV3):Readonly<{score:Readonly<ScoreDocumentV2>;notation:Readonly<NotationDocumentV2>}>=>{const score=createScoreDocumentV3(scoreInput);const notation=createNotationDocumentV3(score,notationInput);if(score.parts.some(p=>p.staves.some(s=>s.role==='tablature-linked')))throw new MigrationV2V3Error('Linked TAB topology cannot be represented by v2.','DOWNGRADE_UNREPRESENTABLE','$.parts[].staves');if(score.parts.some(p=>p.staves.some(s=>s.role!=='standard')))throw new MigrationV2V3Error('Non-standard v3 staff role cannot be represented losslessly by v2.','DOWNGRADE_UNREPRESENTABLE','$.parts[].staves[].role');const expected=expectedDeterministicIds(score);score.measureFrames.forEach((f,i)=>{if(f.id!==expected.frames[i])throw new MigrationV2V3Error('Custom measure-frame identity would be lost in v2.','DOWNGRADE_UNREPRESENTABLE',`$.measureFrames[${i}].id`);});score.parts.forEach((p,i)=>{if(p.instrument.id!==expected.instruments[i]||p.instrument.name!==p.name||p.instrument.shortName!==null)throw new MigrationV2V3Error('Instrument topology metadata would be lost in v2.','DOWNGRADE_UNREPRESENTABLE',`$.parts[${i}].instrument`);});
  const v2=createScoreDocumentV2({schemaVersion:'2.0.0',id:score.id,revision:score.revision,source:score.source,parts:score.parts.map(part=>({id:part.id,name:part.name,staves:part.staves.map((staff,si)=>{if(staff.role==='tablature-linked')throw new Error('unreachable');return {id:staff.id,ordinal:si+1,measures:staff.measures.map((m,mi)=>({id:m.id,ordinal:mi+1,displayNumber:score.measureFrames[mi]?.displayNumber??null,voices:m.voices}))};})}))});
  const frameById=new Map(notation.frames.map(e=>[e.target.frameId,e.notation]));const localById=new Map(notation.measures.map(e=>[e.target.measureId,e.notation]));const measures=[] as any[];for(const part of score.parts)for(const staff of part.staves){if(staff.role==='tablature-linked')continue;for(const measure of staff.measures){const frame=frameById.get(measure.frameId);const local=localById.get(measure.id);if(!frame&&!local)continue;const a=addressEntityV2(v2,measure.id);if(a.kind!=='measure')throw new MigrationV2V3Error('Projected v2 measure kind mismatch.','MIGRATION_INVALID',measure.id);measures.push({target:a,notation:{timeSignature:frame?.timeSignature??null,keySignature:local?.keySignature??null,clef:local?.clef??null,barlines:frame?.barlines??[]}});}}
  const map=(entries:readonly {target:any;notation:unknown}[],kind:string,idOf:(t:any)=>string)=>entries.map(entry=>{const a=addressEntityV2(v2,idOf(entry.target));if(a.kind!==kind)throw new MigrationV2V3Error('Projected notation target kind mismatch.','MIGRATION_INVALID',idOf(entry.target));return {target:a,notation:entry.notation};});const v2Notation=createNotationDocumentV2(v2,{contractVersion:'2.0.0',documentId:v2.id,revisionId:v2.revision.id,measures,events:map(notation.events,'event',t=>t.eventId) as any,notes:map(notation.notes,'note',t=>t.noteId) as any,graceEvents:map(notation.graceEvents,'grace-event',t=>t.graceEventId) as any,graceNotes:map(notation.graceNotes,'grace-note',t=>t.graceNoteId) as any});return Object.freeze({score:v2,notation:v2Notation});};
