import { createScoreDocumentV3, type ContentStaffV3, type PartV3, type ScoreDocumentV3, type StaffRoleV3, type TabProfileV3 } from '../../score-model-v3/src/index.js';
import { addressEntityV3, resolveSemanticAddressV3, type DocumentAddressV3, type PartAddressV3, type SemanticAddressV3, type StaffAddressV3 } from '../../addressing-v3/src/index.js';
import { createNotationDocumentV3, type NotationDocumentV3 } from '../../notation-structure-v3/src/index.js';
import type { Rational, RevisionIdentity } from '../../score-model/src/index.js';

export const TOPOLOGY_AUTHORING_V3_VERSION='1.0.0' as const;
export interface FrameRestIdentityPlanV3 { readonly frameId:string; readonly measureId:string; readonly voiceId:string; readonly restEventId:string }
interface IntentBase { readonly version:typeof TOPOLOGY_AUTHORING_V3_VERSION; readonly type:string }
export interface AddPartIntentV3 extends IntentBase { readonly type:'ADD_STANDARD_OR_PERCUSSION_PART'; readonly target:DocumentAddressV3; readonly index:number; readonly partId:string; readonly partName:string|null; readonly instrumentId:string; readonly instrumentName:string|null; readonly instrumentShortName:string|null; readonly staffId:string; readonly staffRole:'standard'|'percussion'; readonly frameRestIds:readonly FrameRestIdentityPlanV3[] }
export interface RemovePartIntentV3 extends IntentBase { readonly type:'REMOVE_PART'; readonly target:PartAddressV3 }
export interface ReorderPartIntentV3 extends IntentBase { readonly type:'REORDER_PART'; readonly target:PartAddressV3; readonly toIndex:number }
export interface AddStaffIntentV3 extends IntentBase { readonly type:'ADD_STANDARD_OR_PERCUSSION_STAFF'; readonly target:PartAddressV3; readonly index:number; readonly staffId:string; readonly staffRole:'standard'|'percussion'; readonly frameRestIds:readonly FrameRestIdentityPlanV3[] }
export interface RemoveContentStaffIntentV3 extends IntentBase { readonly type:'REMOVE_CONTENT_STAFF'; readonly target:StaffAddressV3 }
export interface ReorderStaffIntentV3 extends IntentBase { readonly type:'REORDER_STAFF'; readonly target:StaffAddressV3; readonly toIndex:number }
export interface AddLinkedTabStaffIntentV3 extends IntentBase { readonly type:'ADD_LINKED_TAB_STAFF'; readonly target:StaffAddressV3; readonly index:number; readonly staffId:string; readonly tabProfile:TabProfileV3 }
export interface RemoveLinkedTabStaffIntentV3 extends IntentBase { readonly type:'REMOVE_LINKED_TAB_STAFF'; readonly target:StaffAddressV3 }
export interface RenamePartIntentV3 extends IntentBase { readonly type:'RENAME_PART_OR_INSTRUMENT'; readonly target:PartAddressV3; readonly partName:string|null; readonly instrumentName:string|null; readonly instrumentShortName:string|null }
export type TopologyAuthoringIntentV3=AddPartIntentV3|RemovePartIntentV3|ReorderPartIntentV3|AddStaffIntentV3|RemoveContentStaffIntentV3|ReorderStaffIntentV3|AddLinkedTabStaffIntentV3|RemoveLinkedTabStaffIntentV3|RenamePartIntentV3;
export interface TopologyAuthoringV3Options { readonly nextRevisionId:string }
export interface TopologyAuthoringV3Result { readonly score:Readonly<ScoreDocumentV3>; readonly notation:Readonly<NotationDocumentV3>; readonly selectionEntityId:string }
export type TopologyAuthoringV3ErrorCode='INVALID_INTENT'|'STALE_TARGET'|'TARGET_KIND_MISMATCH'|'IDENTITY_PLAN_INVALID'|'METER_EVIDENCE_MISSING'|'LAST_PART_FORBIDDEN'|'LAST_CONTENT_STAFF_FORBIDDEN'|'TAB_SOURCE_IN_USE'|'STAFF_ROLE_MISMATCH'|'NOTATION_ORPHAN_RISK'|'RESULT_INVALID';
export class TopologyAuthoringV3Error extends Error { readonly code:TopologyAuthoringV3ErrorCode; readonly details:Readonly<Record<string,unknown>>; constructor(message:string,code:TopologyAuthoringV3ErrorCode,details:Record<string,unknown>={}){super(message);this.name='TopologyAuthoringV3Error';this.code=code;this.details=Object.freeze({...details});} }

type R=Record<string,unknown>;
const rec=(v:unknown):v is R=>v!==null&&typeof v==='object'&&!Array.isArray(v);
const exact=(v:unknown,keys:readonly string[]):v is R=>rec(v)&&JSON.stringify(Object.keys(v).sort())===JSON.stringify([...keys].sort());
const name=(v:unknown,label:string):string|null=>{if(v===null)return null;if(typeof v!=='string'||v!==v.trim()||v.length>256)throw new TopologyAuthoringV3Error(`${label} is invalid.`,'INVALID_INTENT');return v;};
const id=(v:unknown,label:string):string=>{if(typeof v!=='string'||!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(v))throw new TopologyAuthoringV3Error(`${label} is invalid.`,'INVALID_INTENT');return v;};
const index=(v:unknown,min:number,max:number,label:string):number=>{if(typeof v!=='number'||!Number.isSafeInteger(v)||v<min||v>max)throw new TopologyAuthoringV3Error(`${label} is outside admitted range.`,'INVALID_INTENT',{min,max,v});return v;};
const gcd=(a:number,b:number):number=>{let x=Math.abs(a),y=Math.abs(b);while(y!==0){const n=x%y;x=y;y=n;}return x;};
const durationFromMeter=(beats:number,beatType:number):Rational=>{const d=gcd(beats,beatType);return Object.freeze({numerator:beats/d,denominator:beatType/d});};
const deepClone=<T>(v:T):T=>structuredClone(v);
const normalizePartOrdinals=(parts:PartV3[]):void=>{parts.forEach((part,i)=>{parts[i]={...part,ordinal:i+1};});};
const normalizeStaffOrdinals=(part:PartV3):PartV3=>({...part,staves:part.staves.map((staff,i)=>({...staff,ordinal:i+1}))});
const currentTarget=(score:ScoreDocumentV3,target:SemanticAddressV3,kind:'document'|'part'|'staff')=>{try{const resolved=resolveSemanticAddressV3(score,target);if(resolved.kind!==kind)throw new TopologyAuthoringV3Error('Topology target kind is not admitted for this intent.','TARGET_KIND_MISMATCH',{expected:kind,observed:resolved.kind});return resolved;}catch(error){if(error instanceof TopologyAuthoringV3Error)throw error;const code=error instanceof Error&&'code' in error?String((error as {code?:unknown}).code):null;if(code==='STALE_REVISION'||code==='DOCUMENT_MISMATCH')throw new TopologyAuthoringV3Error('Topology target belongs to another revision.','STALE_TARGET',{addressingCode:code});throw new TopologyAuthoringV3Error('Topology target does not resolve exactly.','TARGET_KIND_MISMATCH',{addressingCode:code});}};

const effectiveMeters=(score:ScoreDocumentV3,notation:NotationDocumentV3):readonly Rational[]=>{const byFrame=new Map(notation.frames.map(entry=>[entry.target.frameId,entry.notation.timeSignature]));let active:{beats:number;beatType:number}|null=null;return Object.freeze(score.measureFrames.map((frame,i)=>{const declared=byFrame.get(frame.id);if(declared!==undefined&&declared!==null)active=declared;if(active===null)throw new TopologyAuthoringV3Error('Content topology creation requires effective meter for every frame.','METER_EVIDENCE_MISSING',{frameId:frame.id,index:i});return durationFromMeter(active.beats,active.beatType);}));};
const parsePlans=(value:unknown,score:ScoreDocumentV3):readonly FrameRestIdentityPlanV3[]=>{if(!Array.isArray(value)||value.length!==score.measureFrames.length)throw new TopologyAuthoringV3Error('frameRestIds must exactly cover every current frame.','IDENTITY_PLAN_INVALID');return Object.freeze(value.map((raw,i)=>{if(!exact(raw,['frameId','measureId','voiceId','restEventId']))throw new TopologyAuthoringV3Error('Frame rest identity plan field set is invalid.','IDENTITY_PLAN_INVALID',{index:i});const frame=score.measureFrames[i];if(!frame||raw.frameId!==frame.id)throw new TopologyAuthoringV3Error('Frame rest identity plan order must match canonical measure frames.','IDENTITY_PLAN_INVALID',{index:i,expectedFrameId:frame?.id,observedFrameId:raw.frameId});return Object.freeze({frameId:id(raw.frameId,'frameId'),measureId:id(raw.measureId,'measureId'),voiceId:id(raw.voiceId,'voiceId'),restEventId:id(raw.restEventId,'restEventId')});}));};
const createContentStaff=(score:ScoreDocumentV3,notation:NotationDocumentV3,staffId:string,role:'standard'|'percussion',ordinal:number,plans:readonly FrameRestIdentityPlanV3[]):ContentStaffV3=>{const meters=effectiveMeters(score,notation);return {id:staffId,ordinal,role,measures:plans.map((plan,i)=>({id:plan.measureId,frameId:plan.frameId,voices:[{id:plan.voiceId,ordinal:1,events:[{id:plan.restEventId,kind:'rest',onset:{numerator:0,denominator:1},duration:meters[i] as Rational}],graceGroups:[]}]}))};};

const parseIntent=(input:unknown,score:ScoreDocumentV3):TopologyAuthoringIntentV3=>{if(!rec(input)||input.version!==TOPOLOGY_AUTHORING_V3_VERSION||typeof input.type!=='string')throw new TopologyAuthoringV3Error('Topology intent envelope is invalid.','INVALID_INTENT');const t=input.type;
  if(t==='ADD_STANDARD_OR_PERCUSSION_PART'){if(!exact(input,['version','type','target','index','partId','partName','instrumentId','instrumentName','instrumentShortName','staffId','staffRole','frameRestIds']))throw new TopologyAuthoringV3Error('ADD part field set is invalid.','INVALID_INTENT');if(input.staffRole!=='standard'&&input.staffRole!=='percussion')throw new TopologyAuthoringV3Error('staffRole is invalid.','INVALID_INTENT');return {version:'1.0.0',type:t,target:input.target as DocumentAddressV3,index:index(input.index,0,score.parts.length,'index'),partId:id(input.partId,'partId'),partName:name(input.partName,'partName'),instrumentId:id(input.instrumentId,'instrumentId'),instrumentName:name(input.instrumentName,'instrumentName'),instrumentShortName:name(input.instrumentShortName,'instrumentShortName'),staffId:id(input.staffId,'staffId'),staffRole:input.staffRole,frameRestIds:parsePlans(input.frameRestIds,score)};}
  if(t==='REMOVE_PART'){if(!exact(input,['version','type','target']))throw new TopologyAuthoringV3Error('REMOVE_PART field set is invalid.','INVALID_INTENT');return {version:'1.0.0',type:t,target:input.target as PartAddressV3};}
  if(t==='REORDER_PART'){if(!exact(input,['version','type','target','toIndex']))throw new TopologyAuthoringV3Error('REORDER_PART field set is invalid.','INVALID_INTENT');return {version:'1.0.0',type:t,target:input.target as PartAddressV3,toIndex:index(input.toIndex,0,score.parts.length-1,'toIndex')};}
  if(t==='ADD_STANDARD_OR_PERCUSSION_STAFF'){if(!exact(input,['version','type','target','index','staffId','staffRole','frameRestIds']))throw new TopologyAuthoringV3Error('ADD staff field set is invalid.','INVALID_INTENT');if(input.staffRole!=='standard'&&input.staffRole!=='percussion')throw new TopologyAuthoringV3Error('staffRole is invalid.','INVALID_INTENT');const target=input.target as PartAddressV3;const resolved=currentTarget(score,target,'part');return {version:'1.0.0',type:t,target,index:index(input.index,0,resolved.value.staves.length,'index'),staffId:id(input.staffId,'staffId'),staffRole:input.staffRole,frameRestIds:parsePlans(input.frameRestIds,score)};}
  if(t==='REMOVE_CONTENT_STAFF'){if(!exact(input,['version','type','target']))throw new TopologyAuthoringV3Error('REMOVE_CONTENT_STAFF field set is invalid.','INVALID_INTENT');return {version:'1.0.0',type:t,target:input.target as StaffAddressV3};}
  if(t==='REORDER_STAFF'){if(!exact(input,['version','type','target','toIndex']))throw new TopologyAuthoringV3Error('REORDER_STAFF field set is invalid.','INVALID_INTENT');const target=input.target as StaffAddressV3;const part=score.parts.find(p=>p.id===target.partId);if(!part)throw new TopologyAuthoringV3Error('Staff part path does not resolve.','TARGET_KIND_MISMATCH');return {version:'1.0.0',type:t,target,toIndex:index(input.toIndex,0,part.staves.length-1,'toIndex')};}
  if(t==='ADD_LINKED_TAB_STAFF'){if(!exact(input,['version','type','target','index','staffId','tabProfile']))throw new TopologyAuthoringV3Error('ADD_LINKED_TAB_STAFF field set is invalid.','INVALID_INTENT');const target=input.target as StaffAddressV3;const part=score.parts.find(p=>p.id===target.partId);if(!part)throw new TopologyAuthoringV3Error('TAB source part does not resolve.','TARGET_KIND_MISMATCH');return {version:'1.0.0',type:t,target,index:index(input.index,0,part.staves.length,'index'),staffId:id(input.staffId,'staffId'),tabProfile:deepClone(input.tabProfile) as TabProfileV3};}
  if(t==='REMOVE_LINKED_TAB_STAFF'){if(!exact(input,['version','type','target']))throw new TopologyAuthoringV3Error('REMOVE_LINKED_TAB_STAFF field set is invalid.','INVALID_INTENT');return {version:'1.0.0',type:t,target:input.target as StaffAddressV3};}
  if(t==='RENAME_PART_OR_INSTRUMENT'){if(!exact(input,['version','type','target','partName','instrumentName','instrumentShortName']))throw new TopologyAuthoringV3Error('RENAME field set is invalid.','INVALID_INTENT');return {version:'1.0.0',type:t,target:input.target as PartAddressV3,partName:name(input.partName,'partName'),instrumentName:name(input.instrumentName,'instrumentName'),instrumentShortName:name(input.instrumentShortName,'instrumentShortName')};}
  throw new TopologyAuthoringV3Error('Unsupported topology authoring intent.','INVALID_INTENT',{type:t});};

const rebindNotation=(score:ScoreDocumentV3,notation:NotationDocumentV3):Readonly<NotationDocumentV3>=>{const bind=<T extends {target:SemanticAddressV3;notation:unknown}>(entries:readonly T[],idOf:(entry:T)=>string)=>entries.map(entry=>{try{return {target:addressEntityV3(score,idOf(entry)),notation:entry.notation};}catch(error){throw new TopologyAuthoringV3Error('Topology edit would orphan canonical notation.','NOTATION_ORPHAN_RISK',{entityId:idOf(entry),cause:error instanceof Error?error.message:String(error)});}});return createNotationDocumentV3(score,{contractVersion:'3.0.0',documentId:score.id,revisionId:score.revision.id,frames:bind(notation.frames,e=>e.target.frameId) as NotationDocumentV3['frames'],measures:bind(notation.measures,e=>e.target.measureId) as NotationDocumentV3['measures'],events:bind(notation.events,e=>e.target.eventId) as NotationDocumentV3['events'],notes:bind(notation.notes,e=>e.target.noteId) as NotationDocumentV3['notes'],graceEvents:bind(notation.graceEvents,e=>e.target.graceEventId) as NotationDocumentV3['graceEvents'],graceNotes:bind(notation.graceNotes,e=>e.target.graceNoteId) as NotationDocumentV3['graceNotes']});};
const revision=(score:ScoreDocumentV3,nextRevisionId:string):RevisionIdentity=>{const next=id(nextRevisionId,'nextRevisionId');if(next===score.revision.id)throw new TopologyAuthoringV3Error('nextRevisionId must create a new direct child.','INVALID_INTENT');return {id:next,parentId:score.revision.id};};

export const executeTopologyAuthoringV3=(scoreInput:ScoreDocumentV3,notationInput:NotationDocumentV3,intentInput:unknown,options:TopologyAuthoringV3Options):TopologyAuthoringV3Result=>{const score=createScoreDocumentV3(scoreInput);const notation=createNotationDocumentV3(score,notationInput);const intent=parseIntent(intentInput,score);const nextRevision=revision(score,options.nextRevisionId);let candidate=deepClone(score) as ScoreDocumentV3;let selection=score.id;
  if(intent.type==='ADD_STANDARD_OR_PERCUSSION_PART'){currentTarget(score,intent.target,'document');const staff=createContentStaff(score,notation,intent.staffId,intent.staffRole,1,intent.frameRestIds);const part:PartV3={id:intent.partId,ordinal:intent.index+1,name:intent.partName,instrument:{id:intent.instrumentId,name:intent.instrumentName,shortName:intent.instrumentShortName},staves:[staff]};const parts=deepClone(score.parts) as PartV3[];parts.splice(intent.index,0,part);normalizePartOrdinals(parts);candidate={...candidate,parts,revision:nextRevision};selection=intent.partId;}
  else if(intent.type==='REMOVE_PART'){const resolved=currentTarget(score,intent.target,'part');if(score.parts.length===1)throw new TopologyAuthoringV3Error('The final part cannot be removed.','LAST_PART_FORBIDDEN');const parts=deepClone(score.parts).filter(p=>p.id!==resolved.value.id) as PartV3[];normalizePartOrdinals(parts);candidate={...candidate,parts,revision:nextRevision};selection=score.id;}
  else if(intent.type==='REORDER_PART'){const resolved=currentTarget(score,intent.target,'part');const parts=deepClone(score.parts) as PartV3[];const from=parts.findIndex(p=>p.id===resolved.value.id);const [moved]=parts.splice(from,1);if(!moved)throw new TopologyAuthoringV3Error('Part disappeared during reorder.','RESULT_INVALID');parts.splice(intent.toIndex,0,moved);normalizePartOrdinals(parts);candidate={...candidate,parts,revision:nextRevision};selection=resolved.value.id;}
  else if(intent.type==='ADD_STANDARD_OR_PERCUSSION_STAFF'){const resolved=currentTarget(score,intent.target,'part');const parts=deepClone(score.parts) as PartV3[];const pi=parts.findIndex(p=>p.id===resolved.value.id);const part=parts[pi];if(!part)throw new TopologyAuthoringV3Error('Part disappeared during staff addition.','RESULT_INVALID');const staff=createContentStaff(score,notation,intent.staffId,intent.staffRole,intent.index+1,intent.frameRestIds);const staves=[...part.staves];staves.splice(intent.index,0,staff);parts[pi]=normalizeStaffOrdinals({...part,staves});candidate={...candidate,parts,revision:nextRevision};selection=intent.staffId;}
  else if(intent.type==='REMOVE_CONTENT_STAFF'){const resolved=currentTarget(score,intent.target,'staff');if(resolved.value.role==='tablature-linked')throw new TopologyAuthoringV3Error('REMOVE_CONTENT_STAFF requires a content-bearing staff.','STAFF_ROLE_MISMATCH');const part=score.parts.find(p=>p.id===intent.target.partId);if(!part)throw new TopologyAuthoringV3Error('Staff part path disappeared.','RESULT_INVALID');const contentCount=part.staves.filter(s=>s.role!=='tablature-linked').length;if(contentCount<=1)throw new TopologyAuthoringV3Error('A part must retain at least one content-bearing staff.','LAST_CONTENT_STAFF_FORBIDDEN');if(part.staves.some(s=>s.role==='tablature-linked'&&s.sourceStaffId===resolved.value.id))throw new TopologyAuthoringV3Error('A standard staff referenced by linked TAB cannot be removed independently.','TAB_SOURCE_IN_USE',{staffId:resolved.value.id});const parts=deepClone(score.parts) as PartV3[];const pi=parts.findIndex(p=>p.id===part.id);const nextPart=parts[pi];if(!nextPart)throw new TopologyAuthoringV3Error('Part disappeared during staff removal.','RESULT_INVALID');parts[pi]=normalizeStaffOrdinals({...nextPart,staves:nextPart.staves.filter(s=>s.id!==resolved.value.id)});candidate={...candidate,parts,revision:nextRevision};selection=part.id;}
  else if(intent.type==='REORDER_STAFF'){const resolved=currentTarget(score,intent.target,'staff');const parts=deepClone(score.parts) as PartV3[];const pi=parts.findIndex(p=>p.id===intent.target.partId);const part=parts[pi];if(!part)throw new TopologyAuthoringV3Error('Part disappeared during staff reorder.','RESULT_INVALID');const staves=[...part.staves];const from=staves.findIndex(s=>s.id===resolved.value.id);const [moved]=staves.splice(from,1);if(!moved)throw new TopologyAuthoringV3Error('Staff disappeared during reorder.','RESULT_INVALID');staves.splice(intent.toIndex,0,moved);parts[pi]=normalizeStaffOrdinals({...part,staves});candidate={...candidate,parts,revision:nextRevision};selection=resolved.value.id;}
  else if(intent.type==='ADD_LINKED_TAB_STAFF'){const resolved=currentTarget(score,intent.target,'staff');if(resolved.value.role!=='standard')throw new TopologyAuthoringV3Error('Linked TAB source must be a standard staff.','STAFF_ROLE_MISMATCH');const parts=deepClone(score.parts) as PartV3[];const pi=parts.findIndex(p=>p.id===intent.target.partId);const part=parts[pi];if(!part)throw new TopologyAuthoringV3Error('Part disappeared during TAB addition.','RESULT_INVALID');const staves=[...part.staves];staves.splice(intent.index,0,{id:intent.staffId,ordinal:intent.index+1,role:'tablature-linked',sourceStaffId:resolved.value.id,tabProfile:deepClone(intent.tabProfile),measures:[]});parts[pi]=normalizeStaffOrdinals({...part,staves});candidate={...candidate,parts,revision:nextRevision};selection=intent.staffId;}
  else if(intent.type==='REMOVE_LINKED_TAB_STAFF'){const resolved=currentTarget(score,intent.target,'staff');if(resolved.value.role!=='tablature-linked')throw new TopologyAuthoringV3Error('REMOVE_LINKED_TAB_STAFF requires linked TAB staff.','STAFF_ROLE_MISMATCH');const parts=deepClone(score.parts) as PartV3[];const pi=parts.findIndex(p=>p.id===intent.target.partId);const part=parts[pi];if(!part)throw new TopologyAuthoringV3Error('Part disappeared during TAB removal.','RESULT_INVALID');parts[pi]=normalizeStaffOrdinals({...part,staves:part.staves.filter(s=>s.id!==resolved.value.id)});candidate={...candidate,parts,revision:nextRevision};selection=intent.target.partId;}
  else {const resolved=currentTarget(score,intent.target,'part');const parts=deepClone(score.parts) as PartV3[];const pi=parts.findIndex(p=>p.id===resolved.value.id);const part=parts[pi];if(!part)throw new TopologyAuthoringV3Error('Part disappeared during rename.','RESULT_INVALID');parts[pi]={...part,name:intent.partName,instrument:{...part.instrument,name:intent.instrumentName,shortName:intent.instrumentShortName}};candidate={...candidate,parts,revision:nextRevision};selection=part.id;}
  let nextScore:Readonly<ScoreDocumentV3>;try{nextScore=createScoreDocumentV3(candidate);}catch(error){throw new TopologyAuthoringV3Error('Topology candidate failed v3 validation.','RESULT_INVALID',{cause:error instanceof Error?error.message:String(error)});}const nextNotation=rebindNotation(nextScore,notation);return Object.freeze({score:nextScore,notation:nextNotation,selectionEntityId:selection});};
