import { createScoreDocumentV3, type ScoreDocumentV3 } from '../../score-model-v3/src/index.js';
import { createNotationDocumentV3, type NotationDocumentV3 } from '../../notation-structure-v3/src/index.js';

export const EDITOR_HISTORY_V3_VERSION='3.0.0' as const;
export interface EditorSnapshotV3 { readonly score:Readonly<ScoreDocumentV3>; readonly notation:Readonly<NotationDocumentV3> }
export interface EditorHistoryStateV3 { readonly version:typeof EDITOR_HISTORY_V3_VERSION; readonly past:readonly EditorSnapshotV3[]; readonly present:EditorSnapshotV3; readonly future:readonly EditorSnapshotV3[] }
export class EditorHistoryV3Error extends Error { readonly code:'INVALID_PAIR'|'NON_DIRECT_CHILD'|'NO_HISTORY'; constructor(message:string,code:'INVALID_PAIR'|'NON_DIRECT_CHILD'|'NO_HISTORY'){super(message);this.name='EditorHistoryV3Error';this.code=code;} }
const pair=(scoreInput:ScoreDocumentV3,notationInput:NotationDocumentV3):EditorSnapshotV3=>{const score=createScoreDocumentV3(scoreInput);const notation=createNotationDocumentV3(score,notationInput);return Object.freeze({score,notation});};
export const createEditorHistoryV3=(score:ScoreDocumentV3,notation:NotationDocumentV3):Readonly<EditorHistoryStateV3>=>Object.freeze({version:EDITOR_HISTORY_V3_VERSION,past:Object.freeze([]),present:pair(score,notation),future:Object.freeze([])});
export const commitEditorHistoryV3=(history:EditorHistoryStateV3,nextScore:ScoreDocumentV3,nextNotation:NotationDocumentV3):Readonly<EditorHistoryStateV3>=>{const next=pair(nextScore,nextNotation);if(next.score.revision.parentId!==history.present.score.revision.id)throw new EditorHistoryV3Error('V3 history accepts only direct-child revisions.','NON_DIRECT_CHILD');return Object.freeze({version:EDITOR_HISTORY_V3_VERSION,past:Object.freeze([...history.past,history.present]),present:next,future:Object.freeze([])});};
export const navigateEditorHistoryV3=(history:EditorHistoryStateV3,direction:'UNDO'|'REDO'):Readonly<EditorHistoryStateV3>=>{if(direction==='UNDO'){const previous=history.past.at(-1);if(!previous)throw new EditorHistoryV3Error('No v3 undo snapshot exists.','NO_HISTORY');return Object.freeze({version:EDITOR_HISTORY_V3_VERSION,past:Object.freeze(history.past.slice(0,-1)),present:previous,future:Object.freeze([history.present,...history.future])});}const next=history.future[0];if(!next)throw new EditorHistoryV3Error('No v3 redo snapshot exists.','NO_HISTORY');return Object.freeze({version:EDITOR_HISTORY_V3_VERSION,past:Object.freeze([...history.past,history.present]),present:next,future:Object.freeze(history.future.slice(1))});};
