import { createScoreDocumentV3, type ScoreDocumentV3 } from '../../score-model-v3/src/index.js';
import { createNotationDocumentV3, type NotationDocumentV3 } from '../../notation-structure-v3/src/index.js';
import { createSemanticAddressIndexV3, resolveSemanticAddressV3, type SemanticAddressV3 } from '../../addressing-v3/src/index.js';
import { downgradeScoreNotationV3ToV2, MigrationV2V3Error } from '../../schema-migration-v2-v3/src/index.js';
import { createRendererRequestV2WithProfile, type RenderProjectionStatusV2 } from '../../renderer-contract-v2/src/index.js';
import { assertRendererProfile, rendererProfile, type RendererFamily, type RendererProfile } from '../../renderer-contract/src/index.js';
import { MusicXmlError } from '../../musicxml/src/index.js';

export const RENDER_REQUEST_V3_VERSION='3.0.0' as const;
export const RENDER_MANIFEST_V3_VERSION='3.0.0' as const;
export type RenderProjectionStatusV3='V2_COMPATIBLE_XML'|'V3_XML_PENDING';
export interface RenderManifestEntryV3 { readonly token:string; readonly address:SemanticAddressV3 }
export interface RenderManifestV3 { readonly contractVersion:typeof RENDER_MANIFEST_V3_VERSION; readonly documentId:string; readonly revisionId:string; readonly entries:readonly RenderManifestEntryV3[] }
export interface RendererRequestV3 { readonly contractVersion:typeof RENDER_REQUEST_V3_VERSION; readonly renderer:RendererProfile; readonly documentId:string; readonly revisionId:string; readonly projectionStatus:RenderProjectionStatusV3; readonly sourceProjectionStatus:RenderProjectionStatusV2|null; readonly musicXml:string|null; readonly manifest:Readonly<RenderManifestV3> }
export type RendererContractV3ErrorCode='INVALID_RENDER_REQUEST'|'STALE_RENDER_REQUEST'|'UNKNOWN_RENDER_TOKEN'|'RENDER_TOKEN_PATH_MISMATCH';
export class RendererContractV3Error extends Error { readonly code:RendererContractV3ErrorCode; readonly details:Readonly<Record<string,unknown>>; constructor(message:string,code:RendererContractV3ErrorCode,details:Record<string,unknown>={}){super(message);this.name='RendererContractV3Error';this.code=code;this.details=Object.freeze({...details});} }
const tokenFor=(index:number)=>`stse-r3-${index.toString(36)}`;
export const createRenderManifestV3=(scoreInput:ScoreDocumentV3):Readonly<RenderManifestV3>=>{const score=createScoreDocumentV3(scoreInput);const addresses=[...createSemanticAddressIndexV3(score).byEntityId.values()];return Object.freeze({contractVersion:RENDER_MANIFEST_V3_VERSION,documentId:score.id,revisionId:score.revision.id,entries:Object.freeze(addresses.map((address,index)=>Object.freeze({token:tokenFor(index+1),address})))});};
export const createRendererRequestV3WithProfile=(scoreInput:ScoreDocumentV3,notationInput:NotationDocumentV3,profile:RendererProfile):Readonly<RendererRequestV3>=>{const score=createScoreDocumentV3(scoreInput);const notation=createNotationDocumentV3(score,notationInput);assertRendererProfile(profile);let projectionStatus:RenderProjectionStatusV3='V3_XML_PENDING';let sourceProjectionStatus:RenderProjectionStatusV2|null=null;let musicXml:string|null=null;try{const v2=downgradeScoreNotationV3ToV2(score,notation);const request=createRendererRequestV2WithProfile(v2.score,v2.notation,profile);if(request.musicXml!==null&&request.projectionStatus!=='VNEXT_XML_PENDING'){projectionStatus='V2_COMPATIBLE_XML';sourceProjectionStatus=request.projectionStatus;musicXml=request.musicXml;}}catch(error){const expectedMigrationLoss=error instanceof MigrationV2V3Error&&error.code==='DOWNGRADE_UNREPRESENTABLE';const expectedProjectionGap=error instanceof MusicXmlError;if(!expectedMigrationLoss&&!expectedProjectionGap)throw error;}return Object.freeze({contractVersion:RENDER_REQUEST_V3_VERSION,renderer:profile,documentId:score.id,revisionId:score.revision.id,projectionStatus,sourceProjectionStatus,musicXml,manifest:createRenderManifestV3(score)});};
export const createRendererRequestV3=(score:ScoreDocumentV3,notation:NotationDocumentV3,family:RendererFamily='osmd')=>createRendererRequestV3WithProfile(score,notation,rendererProfile(family));
export const renderableMusicXmlV3=(request:RendererRequestV3):string=>{if(request.contractVersion!==RENDER_REQUEST_V3_VERSION)throw new RendererContractV3Error('RendererRequestV3 version is invalid.','INVALID_RENDER_REQUEST');assertRendererProfile(request.renderer);if(request.projectionStatus==='V3_XML_PENDING'){if(request.musicXml!==null||request.sourceProjectionStatus!==null)throw new RendererContractV3Error('Pending v3 request must carry no XML projection.','INVALID_RENDER_REQUEST');throw new RendererContractV3Error('Current v3 topology has no lossless admitted MusicXML renderer projection.','INVALID_RENDER_REQUEST',{projectionStatus:request.projectionStatus});}if(request.projectionStatus!=='V2_COMPATIBLE_XML'||typeof request.musicXml!=='string'||request.musicXml.length===0||request.sourceProjectionStatus===null||request.sourceProjectionStatus==='VNEXT_XML_PENDING')throw new RendererContractV3Error('Renderable v3 request is internally inconsistent.','INVALID_RENDER_REQUEST');return request.musicXml;};
const same=(a:SemanticAddressV3,b:SemanticAddressV3)=>JSON.stringify(a)===JSON.stringify(b);
export const resolveRenderTokenV3=(scoreInput:ScoreDocumentV3,request:RendererRequestV3,token:string):SemanticAddressV3=>{const score=createScoreDocumentV3(scoreInput);if(request.contractVersion!==RENDER_REQUEST_V3_VERSION||request.documentId!==score.id||request.revisionId!==score.revision.id)throw new RendererContractV3Error('Renderer request belongs to another v3 revision.','STALE_RENDER_REQUEST');if(request.manifest.contractVersion!==RENDER_MANIFEST_V3_VERSION||request.manifest.documentId!==request.documentId||request.manifest.revisionId!==request.revisionId)throw new RendererContractV3Error('V3 render manifest envelope mismatch.','RENDER_TOKEN_PATH_MISMATCH');const supplied=request.manifest.entries.find(entry=>entry.token===token);if(!supplied)throw new RendererContractV3Error('Unknown v3 render token.','UNKNOWN_RENDER_TOKEN',{token});const canonical=createRenderManifestV3(score).entries.find(entry=>entry.token===token);if(!canonical||!same(supplied.address,canonical.address))throw new RendererContractV3Error('V3 render token mapping differs from canonical manifest.','RENDER_TOKEN_PATH_MISMATCH',{token});try{resolveSemanticAddressV3(score,canonical.address);}catch(error){throw new RendererContractV3Error('V3 render token no longer resolves exactly.','RENDER_TOKEN_PATH_MISMATCH',{cause:error instanceof Error?error.message:String(error)});}return canonical.address;};
