import { createScoreDocumentV3, type ScoreDocumentV3 } from '../../score-model-v3/src/index.js';
import type { Pitch, Rational, ScoreEvent } from '../../score-model/src/index.js';
import {
  addressEntityV3,
  resolveSemanticAddressV3,
  type EventAddressV3,
  type NoteAddressV3,
  type SemanticAddressV3
} from '../../addressing-v3/src/index.js';
import { createNotationDocumentV4, type NotationDocumentV4 } from '../../notation-structure-v4/src/index.js';
import type { EventNotationV2 } from '../../notation-structure-v2/src/index.js';
import type { BoundaryMark, NoteNotation, TupletSpec } from '../../notation-structure/src/index.js';
import { parseEditorKeypadAction, type EditorKeypadAction, type EditorKeypadActionId } from '../../editor-keypad/src/index.js';

export const EDITOR_KEYPAD_EXECUTION_V4_VERSION='1.0.0' as const;
export interface EditorKeypadV4Options { readonly nextRevisionId:string }
export interface EditorKeypadEventRangeTargetV4 { readonly version:typeof EDITOR_KEYPAD_EXECUTION_V4_VERSION; readonly kind:'EVENT_RANGE'; readonly targets:readonly EventAddressV3[] }
export interface EditorKeypadNotePairTargetV4 { readonly version:typeof EDITOR_KEYPAD_EXECUTION_V4_VERSION; readonly kind:'NOTE_PAIR'; readonly start:NoteAddressV3; readonly stop:NoteAddressV3 }
export type EditorKeypadAdvancedTargetV4=EditorKeypadEventRangeTargetV4|EditorKeypadNotePairTargetV4;
export interface EditorKeypadExecutionV4Result { readonly version:typeof EDITOR_KEYPAD_EXECUTION_V4_VERSION; readonly action:Readonly<EditorKeypadAction>; readonly score:Readonly<ScoreDocumentV3>; readonly notation:Readonly<NotationDocumentV4>; readonly selection:SemanticAddressV3|null }
export type EditorKeypadExecutionV4ErrorCode='INVALID_REVISION_ID'|'NO_SELECTION'|'STALE_SELECTION'|'SELECTION_KIND'|'ACTION_NOT_IMPLEMENTED'|'DURATION_DOT_INCONSISTENCY'|'NOTATION_ORPHAN_RISK'|'CROSS_STAFF_CONFLICT'|'EXPLICIT_TARGET_REQUIRED'|'INVALID_TARGET_SPEC'|'SELECTION_SCOPE_MISMATCH'|'RANGE_NOT_EXACT'|'TUPLET_TIMING_INCONSISTENT'|'TUPLET_STATE_UNSUPPORTED'|'RELATION_ENDPOINT_INVALID'|'RELATION_AMBIGUOUS'|'RELATION_NUMBER_EXHAUSTED'|'RESULT_INVALID';
export class EditorKeypadExecutionV4Error extends Error { readonly code:EditorKeypadExecutionV4ErrorCode; readonly details:Readonly<Record<string,unknown>>; constructor(message:string,code:EditorKeypadExecutionV4ErrorCode,details:Record<string,unknown>={}){super(message);this.name='EditorKeypadExecutionV4Error';this.code=code;this.details=Object.freeze({...details});Object.freeze(this);} }

const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const SIMPLE:Readonly<Record<string,Readonly<Rational>>>=Object.freeze({whole:Object.freeze({numerator:1,denominator:1}),half:Object.freeze({numerator:1,denominator:2}),quarter:Object.freeze({numerator:1,denominator:4}),eighth:Object.freeze({numerator:1,denominator:8}),'16th':Object.freeze({numerator:1,denominator:16}),'32nd':Object.freeze({numerator:1,denominator:32})});
const DOT_FACTORS=Object.freeze([{numerator:1,denominator:1},{numerator:3,denominator:2},{numerator:7,denominator:4},{numerator:15,denominator:8}] as const);
const defaultEvent=():EventNotationV2=>({dots:0,beams:[],tuplet:null,articulations:[],ornaments:[]});
const defaultNote=():NoteNotation=>({accidental:null,ties:[],slurs:[]});
const gcd=(a:bigint,b:bigint):bigint=>{let x=a<0n?-a:a,y=b<0n?-b:b;while(y!==0n)[x,y]=[y,x%y];return x;};
const rational=(n:bigint,d:bigint):Readonly<Rational>=>{if(n<0n||d<=0n)throw new EditorKeypadExecutionV4Error('Computed keypad rational is invalid.','DURATION_DOT_INCONSISTENCY');const g=gcd(n,d),nn=n/g,dd=d/g;if(nn>BigInt(Number.MAX_SAFE_INTEGER)||dd>BigInt(Number.MAX_SAFE_INTEGER))throw new EditorKeypadExecutionV4Error('Computed keypad rational exceeds safe integer bounds.','DURATION_DOT_INCONSISTENCY');return Object.freeze({numerator:Number(nn),denominator:Number(dd)});};
const multiply=(v:Rational,n:number,d:number):Readonly<Rational>=>rational(BigInt(v.numerator)*BigInt(n),BigInt(v.denominator)*BigInt(d));
const add=(a:Rational,b:Rational):Readonly<Rational>=>rational(BigInt(a.numerator)*BigInt(b.denominator)+BigInt(b.numerator)*BigInt(a.denominator),BigInt(a.denominator)*BigInt(b.denominator));
const sameR=(a:Rational,b:Rational):boolean=>BigInt(a.numerator)*BigInt(b.denominator)===BigInt(b.numerator)*BigInt(a.denominator);
const simpleFor=(id:EditorKeypadActionId):Readonly<Rational>|null=>{const m=/^(?:duration|rest)\.(whole|half|quarter|eighth|16th|32nd)$/.exec(id);return m?.[1]===undefined?null:SIMPLE[m[1]]??null;};
const dotFor=(id:EditorKeypadActionId):0|1|2|3|null=>{const m=/^dot\.set\.([0-3])$/.exec(id);if(!m)return null;const n=Number(m[1]);return n===0||n===1||n===2||n===3?n:null;};
const alterFor=(id:EditorKeypadActionId):-1|0|1|null=>id==='accidental.flat'?-1:id==='accidental.natural'?0:id==='accidental.sharp'?1:null;
const assertRevision=(score:ScoreDocumentV3,id:string):void=>{if(!ID.test(id)||id===score.revision.id)throw new EditorKeypadExecutionV4Error('A fresh stable next revision id is required.','INVALID_REVISION_ID');};
const currentSelection=(score:ScoreDocumentV3,selection:SemanticAddressV3|null):SemanticAddressV3=>{if(selection===null)throw new EditorKeypadExecutionV4Error('Keypad action requires semantic selection.','NO_SELECTION');try{resolveSemanticAddressV3(score,selection);return selection;}catch(error){throw new EditorKeypadExecutionV4Error('Keypad selection is stale or invalid.','STALE_SELECTION',{cause:error instanceof Error?error.message:String(error)});}};
const eventTarget=(score:ScoreDocumentV3,primary:SemanticAddressV3):EventAddressV3=>{if(primary.kind==='event')return primary;if(primary.kind==='note'){const a=addressEntityV3(score,primary.eventId);if(a.kind==='event')return a;}throw new EditorKeypadExecutionV4Error('Keypad action requires event or note selection.','SELECTION_KIND',{kind:primary.kind});};
const noteTarget=(primary:SemanticAddressV3):NoteAddressV3=>{if(primary.kind!=='note')throw new EditorKeypadExecutionV4Error('This keypad action requires exact note selection.','SELECTION_KIND',{kind:primary.kind});return primary;};
const eventValue=(score:ScoreDocumentV3,target:EventAddressV3):ScoreEvent=>{const r=resolveSemanticAddressV3(score,target);if(r.kind!=='event')throw new EditorKeypadExecutionV4Error('Event target changed kind.','SELECTION_KIND');return r.value;};
const noteValue=(score:ScoreDocumentV3,target:NoteAddressV3)=>{const r=resolveSemanticAddressV3(score,target);if(r.kind!=='note')throw new EditorKeypadExecutionV4Error('Note target changed kind.','RELATION_ENDPOINT_INVALID');return r.value;};
const noteIds=(e:ScoreEvent):readonly string[]=>e.kind==='note'?[e.note.id]:e.kind==='chord'?e.notes.map(n=>n.id):[];
const targetId=(a:SemanticAddressV3):string=>{switch(a.kind){case'document':return a.documentId;case'measure-frame':return a.frameId;case'part':return a.partId;case'staff':return a.staffId;case'measure':return a.measureId;case'voice':return a.voiceId;case'event':return a.eventId;case'note':return a.noteId;case'grace-group':return a.graceGroupId;case'grace-event':return a.graceEventId;case'grace-note':return a.graceNoteId;}};
const rebind=(score:ScoreDocumentV3,a:SemanticAddressV3):SemanticAddressV3=>addressEntityV3(score,targetId(a));
const rebindSelection=(score:ScoreDocumentV3,a:SemanticAddressV3):SemanticAddressV3|null=>{try{const next=rebind(score,a);return next.kind===a.kind?next:null;}catch{return null;}};

const revisionScore=(score:ScoreDocumentV3,nextRevisionId:string,mutate?:(candidate:ScoreDocumentV3)=>void):Readonly<ScoreDocumentV3>=>{const candidate=structuredClone(score) as ScoreDocumentV3;if(mutate)mutate(candidate);(candidate as {revision:{id:string;parentId:string|null}}).revision={id:nextRevisionId,parentId:score.revision.id};try{return createScoreDocumentV3(candidate);}catch(error){throw new EditorKeypadExecutionV4Error('Keypad score candidate failed canonical validation.','RESULT_INVALID',{cause:error instanceof Error?error.message:String(error)});}};
const mutableEvent=(candidate:ScoreDocumentV3,target:EventAddressV3):{events:ScoreEvent[];index:number}=>{const part=candidate.parts.find(p=>p.id===target.partId);const staff=part?.staves.find(s=>s.id===target.staffId);if(!staff||staff.role==='tablature-linked')throw new EditorKeypadExecutionV4Error('Event target path is invalid.','STALE_SELECTION');const measure=staff.measures.find(m=>m.id===target.measureId&&m.frameId===target.frameId);const voice=measure?.voices.find(v=>v.id===target.voiceId);if(!voice)throw new EditorKeypadExecutionV4Error('Event target path is invalid.','STALE_SELECTION');const index=voice.events.findIndex(e=>e.id===target.eventId);if(index<0)throw new EditorKeypadExecutionV4Error('Event target path is invalid.','STALE_SELECTION');const events=[...voice.events] as ScoreEvent[];(voice as {events:readonly ScoreEvent[]}).events=events;return {events,index};};
const mutateDuration=(candidate:ScoreDocumentV3,target:EventAddressV3,duration:Rational,replaceWithRest:boolean):void=>{const {events,index}=mutableEvent(candidate,target);const e=events[index]!;events[index]=replaceWithRest&&e.kind!=='rest'?{id:e.id,kind:'rest',onset:e.onset,duration}:{...e,duration};};
const mutatePitch=(candidate:ScoreDocumentV3,target:NoteAddressV3,pitch:Pitch):void=>{const eventAddress=addressEntityV3(candidate,target.eventId);if(eventAddress.kind!=='event')throw new EditorKeypadExecutionV4Error('Selected note parent event is invalid.','SELECTION_KIND');const {events,index}=mutableEvent(candidate,eventAddress);const e=events[index]!;if(e.kind==='note'){if(e.note.id!==target.noteId)throw new EditorKeypadExecutionV4Error('Selected note no longer belongs to event.','STALE_SELECTION');events[index]={...e,note:{...e.note,pitch}};}else if(e.kind==='chord'){events[index]={...e,notes:e.notes.map(n=>n.id===target.noteId?{...n,pitch}:n)};}else throw new EditorKeypadExecutionV4Error('Rest has no pitch.','SELECTION_KIND');};

const buildNotation=(score:ScoreDocumentV3,base:NotationDocumentV4,eventMap:ReadonlyMap<string,EventNotationV2>,noteMap:ReadonlyMap<string,NoteNotation>):Readonly<NotationDocumentV4>=>{try{return createNotationDocumentV4(score,{contractVersion:'4.0.0',documentId:score.id,revisionId:score.revision.id,frames:base.frames.map(e=>({target:rebind(score,e.target) as typeof e.target,notation:e.notation})),measures:base.measures.map(e=>({target:rebind(score,e.target) as typeof e.target,notation:e.notation})),events:[...eventMap].map(([id,notation])=>({target:addressEntityV3(score,id) as EventAddressV3,notation})),notes:[...noteMap].map(([id,notation])=>({target:addressEntityV3(score,id) as NoteAddressV3,notation})),graceEvents:base.graceEvents.map(e=>({target:rebind(score,e.target) as typeof e.target,notation:e.notation})),graceNotes:base.graceNotes.map(e=>({target:rebind(score,e.target) as typeof e.target,notation:e.notation})),crossStaffPlacements:base.crossStaffPlacements.map(p=>({source:rebind(score,p.source) as EventAddressV3,displayStaffId:p.displayStaffId}))});}catch(error){throw new EditorKeypadExecutionV4Error('Keypad notation candidate failed V4 validation.','RESULT_INVALID',{cause:error instanceof Error?error.message:String(error)});}};
const maps=(n:NotationDocumentV4)=>({events:new Map(n.events.map(e=>[e.target.eventId,e.notation])),notes:new Map(n.notes.map(e=>[e.target.noteId,e.notation]))});
const durationDots=(score:ScoreDocumentV3,notation:NotationDocumentV4,primary:SemanticAddressV3,duration:Rational,dots:0|1|2|3,replaceWithRest:boolean,nextRevisionId:string):{score:Readonly<ScoreDocumentV3>;notation:Readonly<NotationDocumentV4>;selection:SemanticAddressV3|null}=>{
  const target=eventTarget(score,primary),event=eventValue(score,target);
  if(replaceWithRest&&event.kind!=='rest'){
    const removed=noteIds(event);if(notation.notes.some(e=>removed.includes(e.target.noteId)))throw new EditorKeypadExecutionV4Error('Rest replacement would orphan note notation.','NOTATION_ORPHAN_RISK',{noteIds:removed});if(notation.crossStaffPlacements.some(p=>p.source.eventId===event.id))throw new EditorKeypadExecutionV4Error('Cross-staff placement must be removed before converting its source to a rest.','CROSS_STAFF_CONFLICT',{eventId:event.id});
  }
  const nextScore=revisionScore(score,nextRevisionId,c=>mutateDuration(c,target,duration,replaceWithRest));const {events,notes}=maps(notation);const current=events.get(target.eventId)??defaultEvent();events.set(target.eventId,{...current,dots});const nextNotation=buildNotation(nextScore,notation,events,notes);return {score:nextScore,notation:nextNotation,selection:replaceWithRest&&event.kind!=='rest'&&primary.kind==='note'?null:rebindSelection(nextScore,primary)};
};
const dottedDuration=(event:ScoreEvent,currentDots:number,requested:0|1|2|3):Readonly<Rational>=>{if(!Number.isSafeInteger(currentDots)||currentDots<0||currentDots>3)throw new EditorKeypadExecutionV4Error('Current dot state is invalid.','DURATION_DOT_INCONSISTENCY',{currentDots});const cf=DOT_FACTORS[currentDots]!,rf=DOT_FACTORS[requested]!;const base=multiply(event.duration,cf.denominator,cf.numerator);const admitted=Object.values(SIMPLE).find(v=>sameR(v,base));if(!admitted)throw new EditorKeypadExecutionV4Error('Current duration/dot state is not an admitted simple keypad value.','DURATION_DOT_INCONSISTENCY',{duration:event.duration,currentDots});return multiply(admitted,rf.numerator,rf.denominator);};

const parseAdvanced=(score:ScoreDocumentV3,raw:unknown):Readonly<EditorKeypadAdvancedTargetV4>=>{if(raw===null||raw===undefined)throw new EditorKeypadExecutionV4Error('Advanced keypad action requires explicit semantic target.','EXPLICIT_TARGET_REQUIRED');if(typeof raw!=='object'||Array.isArray(raw))throw new EditorKeypadExecutionV4Error('Advanced keypad target must be an object.','INVALID_TARGET_SPEC');const r=raw as Record<string,unknown>;if(r.version!==EDITOR_KEYPAD_EXECUTION_V4_VERSION)throw new EditorKeypadExecutionV4Error('Advanced keypad target version is invalid.','INVALID_TARGET_SPEC');if(r.kind==='EVENT_RANGE'&&Array.isArray(r.targets)&&r.targets.length===3){const targets=r.targets as EventAddressV3[];for(const t of targets){try{const x=resolveSemanticAddressV3(score,t);if(x.kind!=='event')throw new Error();}catch{throw new EditorKeypadExecutionV4Error('Triplet target contains stale/non-event address.','INVALID_TARGET_SPEC');}}if(new Set(targets.map(t=>t.eventId)).size!==3)throw new EditorKeypadExecutionV4Error('Triplet target contains duplicate events.','INVALID_TARGET_SPEC');return Object.freeze({version:EDITOR_KEYPAD_EXECUTION_V4_VERSION,kind:'EVENT_RANGE',targets:Object.freeze([...targets])});}if(r.kind==='NOTE_PAIR'&&r.start&&r.stop){const start=r.start as NoteAddressV3,stop=r.stop as NoteAddressV3;try{if(resolveSemanticAddressV3(score,start).kind!=='note'||resolveSemanticAddressV3(score,stop).kind!=='note')throw new Error();}catch{throw new EditorKeypadExecutionV4Error('Connection target contains stale/non-note address.','INVALID_TARGET_SPEC');}if(start.noteId===stop.noteId)throw new EditorKeypadExecutionV4Error('Connection endpoints must be distinct.','RELATION_ENDPOINT_INVALID');return Object.freeze({version:EDITOR_KEYPAD_EXECUTION_V4_VERSION,kind:'NOTE_PAIR',start,stop});}throw new EditorKeypadExecutionV4Error('Advanced keypad target shape is invalid.','INVALID_TARGET_SPEC');};
const eventIdForSelection=(a:SemanticAddressV3):string|null=>a.kind==='event'||a.kind==='note'?a.eventId:null;
const triplet=(score:ScoreDocumentV3,notation:NotationDocumentV4,primary:SemanticAddressV3,target:EditorKeypadEventRangeTargetV4,nextRevisionId:string)=>{
  const selected=eventIdForSelection(primary);if(selected===null||!target.targets.some(t=>t.eventId===selected))throw new EditorKeypadExecutionV4Error('Selection must belong to explicit triplet range.','SELECTION_SCOPE_MISMATCH');const [first,second,third]=target.targets;if(!first||!second||!third)throw new EditorKeypadExecutionV4Error('Triplet range incomplete.','RANGE_NOT_EXACT');if(!target.targets.every(t=>t.partId===first.partId&&t.staffId===first.staffId&&t.frameId===first.frameId&&t.measureId===first.measureId&&t.voiceId===first.voiceId))throw new EditorKeypadExecutionV4Error('Triplet range must stay in one exact source measure voice.','RANGE_NOT_EXACT');const voice=resolveSemanticAddressV3(score,addressEntityV3(score,first.voiceId));if(voice.kind!=='voice')throw new EditorKeypadExecutionV4Error('Triplet voice unavailable.','RANGE_NOT_EXACT');const indices=target.targets.map(t=>voice.value.events.findIndex(e=>e.id===t.eventId));if(indices[0]!<0||indices[1]!==indices[0]!+1||indices[2]!==indices[1]!+1)throw new EditorKeypadExecutionV4Error('Triplet requires three consecutive canonical events.','RANGE_NOT_EXACT',{indices});const values=target.targets.map(t=>eventValue(score,t));if(!values.every(e=>sameR(e.duration,values[0]!.duration)))throw new EditorKeypadExecutionV4Error('Triplet requires equal canonical durations.','TUPLET_TIMING_INCONSISTENT');if(!sameR(add(values[0]!.onset,values[0]!.duration),values[1]!.onset)||!sameR(add(values[1]!.onset,values[1]!.duration),values[2]!.onset))throw new EditorKeypadExecutionV4Error('Triplet events must be canonically contiguous.','TUPLET_TIMING_INCONSISTENT');const written=multiply(values[0]!.duration,3,2);if(!Object.values(SIMPLE).some(v=>sameR(v,written)))throw new EditorKeypadExecutionV4Error('Triplet timing does not map to admitted written base.','TUPLET_TIMING_INCONSISTENT');const {events,notes}=maps(notation);for(const t of target.targets){const current=events.get(t.eventId)??defaultEvent();if(current.dots!==0)throw new EditorKeypadExecutionV4Error('Triplet v1 does not combine with dots.','TUPLET_TIMING_INCONSISTENT',{eventId:t.eventId});if(current.tuplet!==null)throw new EditorKeypadExecutionV4Error('Triplet target already has tuplet metadata.','TUPLET_STATE_UNSUPPORTED',{eventId:t.eventId});}const tuplets:readonly TupletSpec[]=[{actualNotes:3,normalNotes:2,marks:[{number:1,type:'start'}]},{actualNotes:3,normalNotes:2,marks:[]},{actualNotes:3,normalNotes:2,marks:[{number:1,type:'stop'}]}];target.targets.forEach((t,i)=>{const c=events.get(t.eventId)??defaultEvent();events.set(t.eventId,{...c,tuplet:tuplets[i]!});});const nextScore=revisionScore(score,nextRevisionId);return {score:nextScore,notation:buildNotation(nextScore,notation,events,notes),selection:rebindSelection(nextScore,primary)};
};
const voiceOrdinal=(score:ScoreDocumentV3,a:NoteAddressV3):number=>{const v=resolveSemanticAddressV3(score,addressEntityV3(score,a.voiceId));if(v.kind!=='voice')throw new EditorKeypadExecutionV4Error('Connection voice cannot be resolved.','RELATION_ENDPOINT_INVALID');return v.value.ordinal;};
const logicalEvents=(score:ScoreDocumentV3,a:NoteAddressV3,ordinal:number):readonly string[]=>{const part=score.parts.find(p=>p.id===a.partId),staff=part?.staves.find(s=>s.id===a.staffId);if(!staff||staff.role==='tablature-linked')throw new EditorKeypadExecutionV4Error('Connection source staff invalid.','RELATION_ENDPOINT_INVALID');const ids:string[]=[];for(const measure of staff.measures){const voice=measure.voices.find(v=>v.ordinal===ordinal);if(voice)ids.push(...voice.events.map(e=>e.id));}return ids;};
const shared=(start:readonly BoundaryMark[],stop:readonly BoundaryMark[]):readonly number[]=>{const starts=new Set(start.filter(m=>m.type==='start').map(m=>m.number));return [...new Set(stop.filter(m=>m.type==='stop'&&starts.has(m.number)).map(m=>m.number))].sort((a,b)=>a-b);};
const nextNumber=(start:readonly BoundaryMark[],stop:readonly BoundaryMark[]):number=>{const used=new Set([...start,...stop].map(m=>m.number));for(let n=1;n<=16;n++)if(!used.has(n))return n;throw new EditorKeypadExecutionV4Error('No relation number remains.','RELATION_NUMBER_EXHAUSTED');};
const sorted=(marks:readonly BoundaryMark[]):readonly BoundaryMark[]=>[...marks].sort((a,b)=>a.number-b.number||a.type.localeCompare(b.type));
const connection=(score:ScoreDocumentV3,notation:NotationDocumentV4,primary:SemanticAddressV3,target:EditorKeypadNotePairTargetV4,nextRevisionId:string,relation:'tie'|'slur')=>{if(primary.kind!=='note'||primary.noteId!==target.start.noteId)throw new EditorKeypadExecutionV4Error('Selection must be explicit connection start note.','SELECTION_SCOPE_MISMATCH');if(target.start.partId!==target.stop.partId||target.start.staffId!==target.stop.staffId)throw new EditorKeypadExecutionV4Error('Connection endpoints must remain in one source part/staff.','RELATION_ENDPOINT_INVALID');const so=voiceOrdinal(score,target.start),eo=voiceOrdinal(score,target.stop);if(so!==eo)throw new EditorKeypadExecutionV4Error('Connection endpoints must use same voice ordinal.','RELATION_ENDPOINT_INVALID',{so,eo});const ids=logicalEvents(score,target.start,so),si=ids.indexOf(target.start.eventId),ei=ids.indexOf(target.stop.eventId);if(si<0||ei<=si)throw new EditorKeypadExecutionV4Error('Connection stop must occur after start in canonical voice order.','RELATION_ENDPOINT_INVALID',{si,ei});const sn=noteValue(score,target.start),en=noteValue(score,target.stop);if(relation==='tie'){if(ei!==si+1)throw new EditorKeypadExecutionV4Error('Tie requires consecutive canonical events.','RELATION_ENDPOINT_INVALID');if(sn.pitch.step!==en.pitch.step||sn.pitch.alter!==en.pitch.alter||sn.pitch.octave!==en.pitch.octave)throw new EditorKeypadExecutionV4Error('Tie endpoints require exact same pitch.','RELATION_ENDPOINT_INVALID');}const {events,notes}=maps(notation),s=notes.get(target.start.noteId)??defaultNote(),e=notes.get(target.stop.noteId)??defaultNote(),sm=relation==='tie'?s.ties:s.slurs,em=relation==='tie'?e.ties:e.slurs,sh=shared(sm,em);if(sh.length>1)throw new EditorKeypadExecutionV4Error('Connection matches multiple relations.','RELATION_AMBIGUOUS',{shared:sh});let ns:readonly BoundaryMark[],ne:readonly BoundaryMark[];if(sh.length===1){const n=sh[0]!;ns=sorted(sm.filter(m=>!(m.number===n&&m.type==='start')));ne=sorted(em.filter(m=>!(m.number===n&&m.type==='stop')));}else{if(relation==='tie'&&(sm.some(m=>m.type==='start')||em.some(m=>m.type==='stop')))throw new EditorKeypadExecutionV4Error('Tie endpoint already participates in another tie.','RELATION_AMBIGUOUS');const n=nextNumber(sm,em);ns=sorted([...sm,{number:n,type:'start'}]);ne=sorted([...em,{number:n,type:'stop'}]);}notes.set(target.start.noteId,relation==='tie'?{...s,ties:ns}:{...s,slurs:ns});notes.set(target.stop.noteId,relation==='tie'?{...e,ties:ne}:{...e,slurs:ne});const nextScore=revisionScore(score,nextRevisionId);return {score:nextScore,notation:buildNotation(nextScore,notation,events,notes),selection:addressEntityV3(nextScore,target.start.noteId)};};

export const executeEditorKeypadActionV4=(scoreInput:ScoreDocumentV3,notationInput:NotationDocumentV4,selectionInput:SemanticAddressV3|null,rawAction:unknown,rawAdvancedTarget:unknown,options:EditorKeypadV4Options):Readonly<EditorKeypadExecutionV4Result>=>{
  const score=createScoreDocumentV3(scoreInput),notation=createNotationDocumentV4(score,notationInput),action=parseEditorKeypadAction(rawAction),primary=currentSelection(score,selectionInput);assertRevision(score,options.nextRevisionId);
  const simple=simpleFor(action.actionId);if(simple!==null){const r=durationDots(score,notation,primary,simple,0,action.actionId.startsWith('rest.'),options.nextRevisionId);return Object.freeze({version:EDITOR_KEYPAD_EXECUTION_V4_VERSION,action,score:r.score,notation:r.notation,selection:r.selection});}
  const alter=alterFor(action.actionId);if(alter!==null){const target=noteTarget(primary),note=noteValue(score,target),pitch=Object.freeze({...note.pitch,alter});const nextScore=revisionScore(score,options.nextRevisionId,c=>mutatePitch(c,target,pitch));const {events,notes}=maps(notation),current=notes.get(target.noteId)??defaultNote(),accidental=alter===-1?'flat':alter===0?'natural':'sharp';notes.set(target.noteId,{...current,accidental});const nextNotation=buildNotation(nextScore,notation,events,notes);return Object.freeze({version:EDITOR_KEYPAD_EXECUTION_V4_VERSION,action,score:nextScore,notation:nextNotation,selection:addressEntityV3(nextScore,target.noteId)});}
  const requested=dotFor(action.actionId);if(requested!==null){const target=eventTarget(score,primary),event=eventValue(score,target),current=maps(notation).events.get(target.eventId)??defaultEvent(),duration=dottedDuration(event,current.dots,requested),r=durationDots(score,notation,primary,duration,requested,false,options.nextRevisionId);return Object.freeze({version:EDITOR_KEYPAD_EXECUTION_V4_VERSION,action,score:r.score,notation:r.notation,selection:r.selection});}
  const advanced=parseAdvanced(score,rawAdvancedTarget);let r:{score:Readonly<ScoreDocumentV3>;notation:Readonly<NotationDocumentV4>;selection:SemanticAddressV3|null};if(action.actionId==='tuplet.triplet'){if(advanced.kind!=='EVENT_RANGE')throw new EditorKeypadExecutionV4Error('Triplet requires EVENT_RANGE target.','INVALID_TARGET_SPEC');r=triplet(score,notation,primary,advanced,options.nextRevisionId);}else if(action.actionId==='tie.edit'||action.actionId==='slur.edit'){if(advanced.kind!=='NOTE_PAIR')throw new EditorKeypadExecutionV4Error('Connection action requires NOTE_PAIR target.','INVALID_TARGET_SPEC');r=connection(score,notation,primary,advanced,options.nextRevisionId,action.actionId==='tie.edit'?'tie':'slur');}else throw new EditorKeypadExecutionV4Error('Admitted keypad action is not implemented in V4.','ACTION_NOT_IMPLEMENTED',{actionId:action.actionId});return Object.freeze({version:EDITOR_KEYPAD_EXECUTION_V4_VERSION,action,score:r.score,notation:r.notation,selection:r.selection});
};
